### ISSUE TITLE
Not Starting on OpenWRT Docker

### ISSUE THREAD

**Issue by f0banzai** [gotson/komga#1002]
### Steps to reproduce

1.Pulled Image gotson/komga latest
2.Added users,ports...etc. as a container
3.Start

### Expected behavior

Start

### Actual behavior

Not Starting because "file:/config/" in "--spring.config.additional-location=file:/config/" is missing.

I dont' know where to change this "file:/config/" even a workaround for creating directories is OK.

### Logs

```
stdout: 16:46:20.847 [main] DEBUG org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter - Application failed to start due to an exception
stdout: org.springframework.boot.context.config.ConfigDataLocationNotFoundException: Config data location 'file:/config/' cannot be found
stdout: 	at org.springframework.boot.context.config.ConfigDataEnvironment.checkMandatoryLocations(ConfigDataEnvironment.java:383)
stdout: 	at org.springframework.boot.context.config.ConfigDataEnvironment.applyToEnvironment(ConfigDataEnvironment.java:326)
stdout: 	at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:233)
stdout: 	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:102)
stdout: 	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:94)
stdout: 	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:102)
stdout: 	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:87)
stdout: 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
stdout: 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
stdout: 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
stdout: 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
stdout: 	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
stdout: 	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
stdout: 	at java.base/java.util.ArrayList.forEach(Unknown Source)
stdout: 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
stdout: 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
stdout: 	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
stdout: 	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:344)
stdout: 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
stdout: 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
stdout: 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
stdout: 	at org.gotson.komga.ApplicationKt.main(Application.kt:16)
stdout: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
stdout: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
stdout: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
stdout: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
stdout: 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
stdout: 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
stdout: 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
stdout: 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
stdout: 16:46:20.865 [main] ERROR org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter - 
stdout: 
stdout: ***************************
stdout: APPLICATION FAILED TO START
stdout: ***************************
stdout: 
stdout: Description:
stdout: 
stdout: Config data location 'file:/config/' does not exist
stdout: 
stdout: Action:
stdout: 
stdout: Check that the value 'file:/config/' is correct, or prefix it with 'optional:'
stdout: 
```

### Komga version

latest

### Operating system

OpenWrt R22.7.19 / LuCI Master (git-22.200.61437-0c3c82f)

### Other details

Docker Version 20.10.17
API 1.41

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Most likely the docker mounts are incorrect. Can you provide how you create the container (docker run or docker-compose)?

**Comment by f0banzai** [comment]
LEDE/OpenWRT uses luci-app-dockerman
then container interface are added like this:

Docker - Containers

Create new docker container

Container Name:(blank)

Interactive (-i): Y/N

TTY (-t): Y/N

Docker Image: (Images List)

Always pull image first: Y/N

Privileged: Y/N

Restart Policy: (4 Policies)

Networks: (bridge | bridge | 172.17.0.0/16 default)

Links with other containers: (container_name)

Set custom DNS servers:(8.8.8.8 default)

User(-u):(1000:1000 defalut)

Environmental Variable(-e): (eg. TZ=Asia/Shanghai)

Bind Mount(-v): (/media:/media:slave)

Exposed Ports(-p): (2200:22/tcp default)

Run command: (/bin/sh init.sh default)
![QQ截图20221114112223](https://user-images.githubusercontent.com/1592850/201568426-da921387-fab6-4ebb-97ee-cb0b6f687819.jpg)

There is no option to configure the spring boot options.

**Comment by gotson** [comment]
You need to bind a `/config` folder inside the container, that's why the app complains at startup.

**Comment by f0banzai** [comment]
Now it's clear.My fault. I wrote two configs in one row. Sigh.

**Comment by gotson** [comment]
I'll be closing this since it seems you found the issue
