### ISSUE TITLE
Couldn't update, modify or remove book or even modify metadata

### ISSUE THREAD

**Issue by ThierBug** [gotson/komga#1061]
### Steps to reproduce

1. Recently, when I want to remove a book, I have this pop up.
![Sans titre](https://user-images.githubusercontent.com/123402429/215276877-4dcf37da-883c-4a9c-815d-cf205d940e2c.jpg)
2. I can't even modify a book metadata: when I click on Save even Save changes, nothing: the windows don't close and komga does not save anything.
3. 

### Expected behavior

I managed to add books with metadata 2 days ago without any problems.

### Actual behavior

I try to downgrade to 0.160.0.
Same issue.

Komga turn on Docker Container.

### Logs

```
2023-01-28 16:13:16.710  INFO 1 --- [ntContainer#0-1] o.s.j.c.CachingConnectionFactory         : Encountered a JMSException - resetting the underlying JMS Connection
javax.jms.JMSException: Failed to create session factory
	at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnectionInternal(ActiveMQConnectionFactory.java:882) ~[artemis-jms-client-2.19.1.jar:2.19.1]
	at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:299) ~[artemis-jms-client-2.19.1.jar:2.19.1]
	at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:294) ~[artemis-jms-client-2.19.1.jar:2.19.1]
	at org.springframework.jms.connection.SingleConnectionFactory.doCreateConnection(SingleConnectionFactory.java:410) ~[spring-jms-5.3.23.jar:5.3.23]
	at org.springframework.jms.connection.SingleConnectionFactory.initConnection(SingleConnectionFactory.java:350) ~[spring-jms-5.3.23.jar:5.3.23]
	at org.springframework.jms.connection.SingleConnectionFactory.getConnection(SingleConnectionFactory.java:328) ~[spring-jms-5.3.23.jar:5.3.23]
	at org.springframework.jms.connection.SingleConnectionFactory.createConnection(SingleConnectionFactory.java:243) ~[spring-jms-5.3.23.jar:5.3.23]
	at org.springframework.jms.support.JmsAccessor.createConnection(JmsAccessor.java:196) ~[spring-jms-5.3.23.jar:5.3.23]
	at org.springframework.jms.listener.AbstractJmsListeningContainer.createSharedConnection(AbstractJmsListeningContainer.java:412) ~[spring-jms-5.3.23.jar:5.3.23]
	at org.springframework.jms.listener.AbstractJmsListeningContainer.refreshSharedConnection(AbstractJmsListeningContainer.java:397) ~[spring-jms-5.3.23.jar:5.3.23]
	at org.springframework.jms.listener.DefaultMessageListenerContainer.refreshConnectionUntilSuccessful(DefaultMessageListenerContainer.java:985) ~[spring-jms-5.3.23.jar:5.3.23]
	at org.springframework.jms.listener.DefaultMessageListenerContainer.recoverAfterListenerSetupFailure(DefaultMessageListenerContainer.java:959) ~[spring-jms-5.3.23.jar:5.3.23]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1146) ~[spring-jms-5.3.23.jar:5.3.23]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: org.apache.activemq.artemis.api.core.ActiveMQNotConnectedException: AMQ219007: Cannot connect to server(s). Tried with all available servers.
	at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl.createSessionFactory(ServerLocatorImpl.java:708) ~[artemis-core-client-2.19.1.jar:2.19.1]
	at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnectionInternal(ActiveMQConnectionFactory.java:880) ~[artemis-jms-client-2.19.1.jar:2.19.1]
	... 13 common frames omitted

2023-01-28 16:12:31.705 ERROR 1 --- [ntContainer#0-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'domain.events' - retrying using FixedBackOff{interval=5000, currentAttempts=168, maxAttempts=unlimited}. Cause: Failed to create session factory; nested exception is ActiveMQNotConnectedException[errorType=NOT_CONNECTED message=AMQ219007: Cannot connect to server(s). Tried with all available servers.]
```

### Komga version

v0.161.0

### Operating system

Docker 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
please provide complete logs from startup until symptom occurs.

**Comment by ThierBug** [comment]
[_Komga_logs.txt](https://github.com/gotson/komga/files/10529514/_Komga_logs.txt)

Thank you very much
I have submitted the logs from the start of the container to the error message of the gui (while trying to delete a book).
I can't scan a library either.

I tried to replace all the config files with the old ones from a backup. Same errors.

Komga has always worked very well for months without errors: all my metadata has been created and I was afraid to lose hours of work...

**Comment by gotson** [comment]
I see some out of memory exception, try to give it more ram maybe

**Comment by ThierBug** [comment]
Weird
I have 32GB installed and Komga uses a maximum of 12GB.
my OS tells me 16GB available and I have not set any limit to Docker/Portainer.

So I restarted a new instance with a blank configuration folder and there, no worries.
Everything is working.

I think I have an error in the database...
I will have to recreate all my metadata.

**Comment by gotson** [comment]
You can try to delete the `artemis` folder

**Comment by ThierBug** [comment]
I ended up redoing everything from scratch.
a little time consuming but today everything works perfectly.
