### ISSUE TITLE
No books and comics found

### ISSUE THREAD

**Issue by Aiakio** [gotson/komga#1204]
### Steps to reproduce

Hello,

this is my docker compose code for komga:
```
    komga:
        container_name: komga
        image: gotson/komga:latest
        restart: unless-stopped
        volumes:
            - /volume1/docker/komga/config:/config
            - /volume1/Media/Books & Manga:/data
        ports:
            - 25600:25600
        user: 1026:100
        environment:
            - TZ=Europe/Berlin
```

My Books are stored at: /volume1/Media/Books & Manga/Books
and Manga are stored at: /volume1/Media/Books & Manga/Manga

Im not sure if i'm doing something wrong here, or if there is some other issue. I can access `/volume1/Media` with other docker containers just fine.

If i put `/data` in `Root folder` i can create the library, but i get a red `Unavailable` message right under it.

If i put `/data/Manga` or `/volume1/Media/Books & Manga/Manga` in `Root folder` i get a `An error occurred while trying to update library 'XXXXXXXXXXXXX': Library root folder does not exist: file:/data/Manga`

### Expected behavior

That my books and mangas would show up.

### Actual behavior

Red error message: "Unavailable".

### Logs

```
2023-08-23T12:23:12.440+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20210926222612 - authentication activity source"
2023-08-23T12:23:12.481+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20211006141333 - remove spring session"
2023-08-23T12:23:12.523+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20211206100610 - temp table ids"
2023-08-23T12:23:12.571+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20211206124920 - collection and readlist thumbnails"
2023-08-23T12:23:12.613+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20211228152113 - book metadata link"
2023-08-23T12:23:12.667+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20220101120232 - page hash"
2023-08-23T12:23:12.711+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20220105143154 - library hashing options"
2023-08-23T12:23:12.757+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20220106143755 - page file size"
2023-08-23T12:23:12.813+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20220128152310 - page hash"
2023-08-23T12:23:12.854+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20220208193203 - fix books with missing pages"
2023-08-23T12:23:12.896+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20220218111455 - historical events"
2023-08-23T12:23:12.938+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20220224112015 - series sharing labels"
2023-08-23T12:23:12.981+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20220225164240 - user restrictions"
2023-08-23T12:23:13.057+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20220715213721 - perf indices"
2023-08-23T12:23:13.105+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20230112151202 - library comicinfo append volume"
2023-08-23T12:23:13.149+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20230113140806 - series metadata link"
2023-08-23T12:23:13.192+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20230116112647 - series alternate title"
2023-08-23T12:23:13.234+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20230221170726 - readlist ordered"
2023-08-23T12:23:13.275+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20230310121946 - series metadata index"
2023-08-23T12:23:13.318+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20230626150454 - xxhash128"
2023-08-23T12:23:13.360+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20230626151717 - missing page size"
2023-08-23T12:23:13.402+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20230626170856 - page hash remove columns"
2023-08-23T12:23:13.450+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20230629114356 - remove library scandeep column"
2023-08-23T12:23:13.499+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20230711173700 - read announcements"
2023-08-23T12:23:13.542+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20230724114349 - oneshots"
2023-08-23T12:23:13.588+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "main" to version "20230801104436 - fix incorrect language codes"
2023-08-23T12:23:13.628+02:00  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Successfully applied 66 migrations to schema "main", now at version v20230801104436 (execution time 00:03.493s)
2023-08-23T12:23:16.271+02:00  INFO 1 --- [           main] c.g.g.n.j.i.plugins.JxlImageReaderSpi    : Loaded libjxl v0.8.1
2023-08-23T12:23:16.309+02:00  INFO 1 --- [           main] o.g.k.i.image.ImageConverter             : Supported read formats: [JPEG 2000, JPG, tiff, PCX, bmp, wbp, bigtiff, gif, WBMP, PNG, RAW, JPEG, PNM, BigTIFF, tif, TIFF, wbmp, jpeg, jxl, jpeg-lossless, jbig2, jpg, JPEG2000, pcx, BMP, WBP, GIF, Jpeg XL, png, raw, BIGTIFF, webp, JPEG-LOSSLESS, JBIG2, pnm, TIF, jpeg2000, WEBP, jpeg 2000]
2023-08-23T12:23:16.322+02:00  INFO 1 --- [           main] o.g.k.i.image.ImageConverter             : Supported read mediaTypes: [image/vnd.wap.wbmp, image/jpeg, image/x-portable-graymap, image/bmp, image/x-windows-pcx, image/gif, image/x-pc-paintbrush, image/x-raw, image/webp, image/x-pcx, image/x-portable-bitmap, image/x-jb2, image/png, image/pcx, image/x-windows-bmp, image/x-webp, image/jpeg2000, image/jp2, image/x-bmp, image/x-png, image/x-portable-pixmap, image/tiff, image/x-jbig2, image/x-tiff, image/x-portable-anymap, image/jxl]
2023-08-23T12:23:16.325+02:00  INFO 1 --- [           main] o.g.k.i.image.ImageConverter             : Supported write formats: [JPG, JPEG 2000, tiff, bmp, PCX, bigtiff, gif, WBMP, PNG, RAW, JPEG, PNM, BigTIFF, tif, TIFF, jpeg, wbmp, jpg, JPEG2000, BMP, pcx, GIF, png, BIGTIFF, raw, pnm, TIF, jpeg2000, jpeg 2000]
2023-08-23T12:23:16.339+02:00  INFO 1 --- [           main] o.g.k.i.image.ImageConverter             : Supported write mediaTypes: [image/png, image/vnd.wap.wbmp, image/jpeg, image/x-portable-graymap, image/bmp, image/pcx, image/gif, image/x-windows-pcx, image/x-windows-bmp, image/jpeg2000, image/x-pc-paintbrush, image/x-raw, image/jp2, image/x-pcx, image/x-bmp, image/x-png, image/x-portable-bitmap, image/x-portable-pixmap, image/tiff, image/x-tiff, image/x-portable-anymap]
2023-08-23T12:23:16.944+02:00  INFO 1 --- [           main] o.a.l.s.MemorySegmentIndexInputProvider  : Using MemorySegmentIndexInput with Java 19; to disable start with -Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false
2023-08-23T12:23:19.369+02:00  INFO 1 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [public/index.html]
2023-08-23T12:23:20.150+02:00  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 18 endpoint(s) beneath base path '/actuator'
2023-08-23T12:23:20.276+02:00  INFO 1 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Or [Mvc [pattern='/api/**'], Mvc [pattern='/opds/**'], Mvc [pattern='/sse/**'], Mvc [pattern='/oauth2/authorization/**'], Mvc [pattern='/login/oauth2/code/**'], EndpointRequestMatcher includes=[*], excludes=[], includeLinks=true] with [org.springframework.security.web.session.DisableEncodeUrlFilter@7fdf32a4, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@23471b2f, org.springframework.security.web.context.SecurityContextHolderFilter@32a7c583, org.springframework.security.web.header.HeaderWriterFilter@5ea9f2f3, org.springframework.web.filter.CorsFilter@19d75d3c, org.springframework.security.web.authentication.logout.LogoutFilter@3f1eb1bc, org.springframework.security.web.session.ConcurrentSessionFilter@65067d90, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@7bd4f212, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@679f3e12, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@5b285847, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@5c3cc103, org.springframework.security.web.session.SessionManagementFilter@19266ca3, org.springframework.security.web.access.ExceptionTranslationFilter@52aa84ef, org.springframework.security.web.access.intercept.AuthorizationFilter@3df2f4ab]
2023-08-23T12:23:21.292+02:00  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 25600 (http) with context path ''
2023-08-23T12:23:21.537+02:00  INFO 1 --- [   scheduling-1] .AuthenticationActivityCleanupController : Remove authentication activity older than 2023-07-23T10:23:21.534769468 (UTC)
2023-08-23T12:23:21.539+02:00  INFO 1 --- [           main] org.gotson.komga.ApplicationKt           : Started ApplicationKt in 24.467 seconds (process running for 25.49)
2023-08-23T12:23:22.385+02:00  INFO 1 --- [           main] o.g.k.i.scheduler.SearchIndexController  : Lucene index not found, trigger rebuild
2023-08-23T12:23:22.388+02:00  INFO 1 --- [           main] o.g.komga.application.tasks.TaskEmitter  : Sending task: RebuildIndex(priority='8',entities='null')
2023-08-23T12:23:22.503+02:00  INFO 1 --- [ntContainer#1-1] o.g.komga.application.tasks.TaskHandler  : Executing task: RebuildIndex(priority='8',entities='null')
2023-08-23T12:23:22.514+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.i.search.SearchIndexLifecycle      : Rebuild index for: [book, series, collection, readlist]
2023-08-23T12:23:22.516+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.i.search.SearchIndexLifecycle      : Rebuilding index for Book
2023-08-23T12:23:22.667+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.i.search.SearchIndexLifecycle      : Number of entities: 0
2023-08-23T12:23:22.871+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.i.search.SearchIndexLifecycle      : Wrote Book index in 7.056524ms
2023-08-23T12:23:22.940+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.i.search.SearchIndexLifecycle      : Rebuilding index for Series
2023-08-23T12:23:23.031+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.i.search.SearchIndexLifecycle      : Number of entities: 0
2023-08-23T12:23:23.047+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.i.search.SearchIndexLifecycle      : Wrote Series index in 111.346us
2023-08-23T12:23:23.049+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.i.search.SearchIndexLifecycle      : Rebuilding index for Collection
2023-08-23T12:23:23.058+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.i.search.SearchIndexLifecycle      : Number of entities: 0
2023-08-23T12:23:23.061+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.i.search.SearchIndexLifecycle      : Wrote Collection index in 101.056us
2023-08-23T12:23:23.063+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.i.search.SearchIndexLifecycle      : Rebuilding index for ReadList
2023-08-23T12:23:23.070+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.i.search.SearchIndexLifecycle      : Number of entities: 0
2023-08-23T12:23:23.098+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.i.search.SearchIndexLifecycle      : Wrote ReadList index in 89.854us
2023-08-23T12:23:23.359+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.i.search.LuceneHelper              : Lucene index version: 8
2023-08-23T12:23:23.360+02:00  INFO 1 --- [ntContainer#1-1] o.g.komga.application.tasks.TaskHandler  : Task RebuildIndex(priority='8',entities='null') executed in 854.551976ms
2023-08-23T12:24:37.264+02:00  INFO 1 --- [io-25600-exec-3] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-08-23T12:24:37.266+02:00  INFO 1 --- [io-25600-exec-3] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-08-23T12:24:37.278+02:00  INFO 1 --- [io-25600-exec-3] o.s.web.servlet.DispatcherServlet        : Completed initialization in 6 ms
2023-08-23T12:26:37.158+02:00  INFO 1 --- [io-25600-exec-7] o.g.k.domain.service.KomgaUserLifecycle  : User created: KomgaUser(email='[redacted]', roleAdmin=true, roleFileDownload=true, rolePageStreaming=true, sharedLibrariesIds=[], sharedAllLibraries=true, restrictions=ContentRestrictions(ageRestriction=null, labelsAllow=[], labelsExclude=[]), id='0DC71X6SS71E9', createdDate=2023-08-23T12:26:37, lastModifiedDate=2023-08-23T12:26:37)
2023-08-23T12:26:37.882+02:00  INFO 1 --- [io-25600-exec-8] o.g.k.i.security.LoginListener           : AuthenticationActivity(userId=0DC71X6SS71E9, email=[redacted], ip=[redacted], userAgent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0, success=true, error=null, dateTime=2023-08-23T12:26:37.877138346, source=Password)
2023-08-23T12:27:16.591+02:00  INFO 1 --- [io-25600-exec-3] o.g.k.domain.service.LibraryLifecycle    : Adding new library: Books with root folder: file:/data/Books
2023-08-23T12:28:51.279+02:00  INFO 1 --- [io-25600-exec-3] o.g.k.domain.service.LibraryLifecycle    : Adding new library: Books with root folder: file:/volume1/Media/Books%20&%20Manga/Books
2023-08-23T12:29:05.735+02:00  INFO 1 --- [io-25600-exec-2] o.g.k.domain.service.LibraryLifecycle    : Adding new library: Books with root folder: file:/data/
2023-08-23T12:29:05.795+02:00  INFO 1 --- [io-25600-exec-2] o.g.komga.application.tasks.TaskEmitter  : Sending task: ScanLibrary(libraryId='0DC72FC8X70PT', scanDeep='false', priority='4')
2023-08-23T12:29:05.814+02:00  INFO 1 --- [ntContainer#1-1] o.g.komga.application.tasks.TaskHandler  : Executing task: ScanLibrary(libraryId='0DC72FC8X70PT', scanDeep='false', priority='4')
2023-08-23T12:29:05.838+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.d.service.LibraryContentLifecycle  : Updating library: Library(name=Books, root=file:/data/, importComicInfoBook=true, importComicInfoSeries=true, importComicInfoCollection=true, importComicInfoReadList=true, importComicInfoSeriesAppendVolume=true, importEpubBook=true, importEpubSeries=true, importMylarSeries=true, importLocalArtwork=true, importBarcodeIsbn=false, scanForceModifiedTime=false, repairExtensions=false, convertToCbz=false, emptyTrashAfterScan=false, seriesCover=FIRST, hashFiles=true, hashPages=false, analyzeDimensions=true, oneshotsDirectory=null, unavailableDate=null, id=0DC72FC8X70PT, createdDate=2023-08-23T12:29:05, lastModifiedDate=2023-08-23T12:29:05)
2023-08-23T12:29:05.840+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.domain.service.FileSystemScanner   : Scanning folder: /data
2023-08-23T12:29:05.841+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.domain.service.FileSystemScanner   : Supported extensions: [cbz, zip, cbr, rar, pdf, epub]
2023-08-23T12:29:05.842+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.domain.service.FileSystemScanner   : Excluded patterns: [#recycle, @eaDir, @Recycle]
2023-08-23T12:29:05.843+02:00  INFO 1 --- [ntContainer#1-1] o.g.k.domain.service.FileSystemScanner   : Force directory modified time: false
2023-08-23T12:29:05.929+02:00 ERROR 1 --- [ntContainer#1-1] o.g.komga.application.tasks.TaskHandler  : Task ScanLibrary(libraryId='0DC72FC8X70PT', scanDeep='false', priority='4') execution failed
org.gotson.komga.domain.model.DirectoryNotFoundException: Folder is not accessible: /data
	at org.gotson.komga.domain.service.FileSystemScanner.scanRootFolder(FileSystemScanner.kt:60) ~[classes/:1.3.1]
	at org.gotson.komga.domain.service.LibraryContentLifecycle.scanRootFolder(LibraryContentLifecycle.kt:69) ~[classes/:1.3.1]
	at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:60) ~[classes/:1.3.1]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169) ~[spring-messaging-6.0.10.jar:6.0.10]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119) ~[spring-messaging-6.0.10.jar:6.0.10]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:110) ~[spring-jms-6.0.10.jar:6.0.10]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:84) ~[spring-jms-6.0.10.jar:6.0.10]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) ~[spring-jms-6.0.10.jar:6.0.10]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) ~[spring-jms-6.0.10.jar:6.0.10]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[spring-jms-6.0.10.jar:6.0.10]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:330) ~[spring-jms-6.0.10.jar:6.0.10]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:269) ~[spring-jms-6.0.10.jar:6.0.10]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237) ~[spring-jms-6.0.10.jar:6.0.10]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1227) ~[spring-jms-6.0.10.jar:6.0.10]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1120) ~[spring-jms-6.0.10.jar:6.0.10]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
2023-08-23T12:29:22.904+02:00  INFO 1 --- [io-25600-exec-5] o.g.k.domain.service.LibraryLifecycle    : Adding new library: Books with root folder: file:/data/
2023-08-23T12:29:30.316+02:00  WARN 1 --- [io-25600-exec-1] o.s.web.servlet.PageNotFound             : No mapping for GET /welcome
2023-08-23T12:29:38.643+02:00  INFO 1 --- [io-25600-exec-8] o.g.k.domain.service.LibraryLifecycle    : Deleting library: Library(name=Books, root=file:/data/, importComicInfoBook=true, importComicInfoSeries=true, importComicInfoCollection=true, importComicInfoReadList=true, importComicInfoSeriesAppendVolume=true, importEpubBook=true, importEpubSeries=true, importMylarSeries=true, importLocalArtwork=true, importBarcodeIsbn=false, scanForceModifiedTime=false, repairExtensions=false, convertToCbz=false, emptyTrashAfterScan=false, seriesCover=FIRST, hashFiles=true, hashPages=false, analyzeDimensions=true, oneshotsDirectory=null, unavailableDate=2023-08-23T12:29:05.844, id=0DC72FC8X70PT, createdDate=2023-08-23T12:29:05, lastModifiedDate=2023-08-23T12:29:05.858)
2023-08-23T12:29:38.649+02:00  INFO 1 --- [io-25600-exec-8] o.g.k.domain.service.SeriesLifecycle     : Delete series ids: []
2023-08-23T12:29:38.656+02:00  INFO 1 --- [io-25600-exec-8] o.g.komga.domain.service.BookLifecycle   : Delete book ids: []
2023-08-23T12:29:44.615+02:00  WARN 1 --- [io-25600-exec-1] o.s.web.servlet.PageNotFound             : No mapping for GET /libraries/all/series
```

### Komga version

v131

### Operating system

Synology DSM 7.2 / Docker

### Other details

The FAQ link is dead.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by DieselTech** [comment]
Try wrapping the path with quotes. The space and special character in the path might be throwing it off.

**Comment by Aiakio** [comment]
Thank you for your suggestion, @DieselTech.

I tried the following now:
- Removed the special characters and spaces (renamed `Media & Books` to just `Books`)
- Set the volume path in quotes

I tested both of these separately, as well as combined and redeployed the updated compose file each time accordingly, of course.

Sadly it did not help. Exactly the same issues still.

**Comment by gotson** [comment]
Logs could help.

**Comment by Aiakio** [comment]
> 

Updated the original post with the logs. Also here the log as a file:
[_komga_logs.txt](https://github.com/gotson/komga/files/12418288/_komga_logs.txt)

**Comment by gotson** [comment]
> Im not sure if i'm doing something wrong here, or if there is some other issue. I can access `/volume1/Media` with other docker containers just fine.

This cannot work, you have not mounted that folder in the container, so it won't exist inside the container.

> Folder is not accessible: /data

This probably means that the user running the container does not have access to the mounted folder.

Check that user 1026 can access this.

**Comment by Aiakio** [comment]
> > Im not sure if i'm doing something wrong here, or if there is some other issue. I can access `/volume1/Media` with other docker containers just fine.
> 
> This cannot work, you have not mounted that folder in the container, so it won't exist inside the container.

This my be a stupid question, but how do i do that exactly?
I thought `- /volume1/Media/Books & Manga:/data` mounts the folder?


> > Folder is not accessible: /data
> 
> This probably means that the user running the container does not have access to the mounted folder.
> 
> Check that user 1026 can access this.

I saw that as well, but it doesn't make sense. 1026 is my (administrator) account. My user account 1026 definitely has access rights. 1026 also works with other containers that access the /volume1/Media share.

**Comment by farahnur42** [comment]
@Aiakio 
> I thought `- /volume1/Media/Books & Manga:/data` mounts the folder?

It mounts the left-hand side directory *as* /data inside the container, so there is no /volume1/Media inside the container (it can only see /data). Having said that, your original `/data/Manga` should've worked given that you've said  `/volume1/Media/Books & Manga/Manga` is a valid folder that contains your manga outside of the container. 

> Removed the special characters and spaces (renamed Media & Books to just Books)

Wasn't this Books & Manga for your original directory?

In general, it seems like you have some permission issues to solve than anything else.

**Comment by farahnur42** [comment]
> I have figured out what the issue was. It was the user line in the docker compose file: `user: 1026:100`.

You might want to enclose the value in quotes (a la `user: "1026:100"`) and try again; and like Gotson said, the variables are unused for the Komga container so it's running as root.

**Comment by Aiakio** [comment]
Oh, i see. How do i fix this?

**Comment by Aiakio** [comment]
I figured it out. It works now with user privileges and the "user:" line.
I configured a regular user account in synology dsm without admin rights and access to the media & docker share (for the komga config) and then used that one for komga.
