### ISSUE TITLE
Regression in internal-metadata pulling from an ePub

### ISSUE THREAD

**Issue by zachstultz** [gotson/komga#1311]
### Steps to reproduce

I inject my novels with metadata via calibre, and it seems something has regressed. I even took a volume that is already in my library with parsed metadata in komga and removed it, initialized a scan with komga, emptied the trash, re-added it, and it doesn't parse the metadata from that either. So it's not a change on my end.

1. Add a novel to your komga that has internal metadata that is parsable by komga.

### Expected behavior

![image](https://github.com/gotson/komga/assets/8385256/bcc58ab1-8bf2-4785-84aa-5cfb73237792)

### Actual behavior

![image](https://github.com/gotson/komga/assets/8385256/9eb48818-41af-4b0a-8d44-e28c456e5675)
![image](https://github.com/gotson/komga/assets/8385256/bb0250a0-8137-43b0-a152-05c9cbe21842)

### Logs
```
2023-11-28T15:18:05.404-06:00  INFO 1 --- [askProcessor-12] o.g.k.d.service.BookMetadataLifecycle    : Refresh metadata for book: Book(name=Our Last Crusade or the Rise of a New World v12 [2023] [Yen Press] [Stick], url=file:/novels/public/Our%20Last%20Crusade%20or%20the%20Rise%20of%20a%20New%20World/Our%20Last%20Crusade%20or%20the%20Rise%20of%20a%20New%20World%20v12%20%5B2023%5D%20%5BYen%20Press%5D%20%5BStick%5D.epub, fileLastModified=2023-11-28T15:17:55.956, fileSize=11271123, fileHash=, number=12, id=0EBJS6H3VJF3W, seriesId=06476294VG1XS, libraryId=064761317GBWH, deletedDate=null, oneshot=false, createdDate=2023-11-28T15:17:57, lastModifiedDate=2023-11-28T15:17:58.120) with capabilities: [TITLE, RELEASE_DATE, TAGS, LINKS, ISBN, AUTHORS, READ_LISTS, THUMBNAILS, SUMMARY, NUMBER_SORT, NUMBER]
2023-11-28T15:18:05.405-06:00 ERROR 1 --- [askProcessor-12] o.g.komga.application.tasks.TaskHandler  : Task RefreshBookMetadata(bookId='0EBJS6H3VJF3W', capabilities=[TITLE, RELEASE_DATE, TAGS, LINKS, ISBN, AUTHORS, READ_LISTS, THUMBNAILS, SUMMARY, NUMBER_SORT, NUMBER], priority='5') execution failed
org.gotson.komga.domain.model.MediaUnsupportedException: Epub profile does not support getting page content
	at org.gotson.komga.domain.service.BookAnalyzer.getPageContent(BookAnalyzer.kt:182) ~[classes/:1.8.2]
	at org.gotson.komga.infrastructure.metadata.barcode.IsbnBarcodeProvider.getBookMetadataFromBook(IsbnBarcodeProvider.kt:47) ~[classes/:1.8.2]
	at org.gotson.komga.domain.service.BookMetadataLifecycle.refreshMetadata(BookMetadataLifecycle.kt:50) ~[classes/:1.8.2]
	at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:101) ~[classes/:1.8.2]
	at org.gotson.komga.application.tasks.TaskProcessor.takeAndProcess(TaskProcessor.kt:60) ~[classes/:1.8.2]
	at org.gotson.komga.application.tasks.TaskProcessor.processAvailableTask$lambda$1(TaskProcessor.kt:46) ~[classes/:1.8.2]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

### Komga version

1.8.2

### Operating system

Ubuntu 23.10

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
That error is irrelevant, it's about isbn barcode scanning in the images.

**Comment by zachstultz** [comment]
> That error is irrelevant, it's about isbn barcode scanning in the images.

Ah, you're right, disabling that feature fixes it.

**Comment by gotson** [comment]
> > That error is irrelevant, it's about isbn barcode scanning in the images.
> 
> Disabling that feature fixes it. At least as a temporary solution.

Disabling what?

**Comment by zachstultz** [comment]
> > > That error is irrelevant, it's about isbn barcode scanning in the images.
> > 
> > 
> > Disabling that feature fixes it. At least as a temporary solution.
> 
> Disabling what?

"Import ISBN within barcode"
