### ISSUE TITLE
Error analyzing epub

### ISSUE THREAD

**Issue by realblack7** [gotson/komga#1379]
### Steps to reproduce

Some of my epud books cannot be analyzed (no content or cover is shown). Komga throws the error "Unknown error while analyzing book".

I tried readding, redownloading and rezipping/converting but nothing works. 

### Expected behavior

The books should be analyzed and readable.

### Actual behavior

Only the wildcard for the book is shown and you cannot open it.

### Logs

Of a file that does not work:

```
2024-01-03T18:29:40.203Z  INFO 1 --- [-25600-exec-175] o.g.komga.application.tasks.TaskEmitter  : Sending task: AnalyzeBook(bookId='0EPTGTS6WAF9N', priority='6')
2024-01-03T18:29:40.210Z  INFO 1 --- [askProcessor-40] o.g.komga.application.tasks.TaskHandler  : Executing task: AnalyzeBook(bookId='0EPTGTS6WAF9N', priority='6')
2024-01-03T18:29:40.211Z  INFO 1 --- [askProcessor-40] o.g.komga.domain.service.BookLifecycle   : Analyze and persist book: Book(name=A Certain Magical Index SS - Agnese's Magic Side Work Trial, url=file:/data/LightNovels/A%20Certain%20Magical%20Index%20-%20Side%20Stories/A%20Certain%20Magical%20Index%20SS%20-%20Agnese's%20Magic%20Side%20Work%20Trial.epub, fileLastModified=2024-01-03T17:37:57.940, fileSize=11596235, fileHash=cf27837d54f6729533eec613ec115eea, number=14, id=0EPTGTS6WAF9N, seriesId=0EPTGTS6CAAR7, libraryId=0EN45HTVSFFNX, deletedDate=null, oneshot=false, createdDate=2024-01-02T19:33:02, lastModifiedDate=2024-01-03T17:38:42.756)
2024-01-03T18:29:40.211Z  INFO 1 --- [askProcessor-40] o.g.komga.domain.service.BookAnalyzer    : Trying to analyze book: Book(name=A Certain Magical Index SS - Agnese's Magic Side Work Trial, url=file:/data/LightNovels/A%20Certain%20Magical%20Index%20-%20Side%20Stories/A%20Certain%20Magical%20Index%20SS%20-%20Agnese's%20Magic%20Side%20Work%20Trial.epub, fileLastModified=2024-01-03T17:37:57.940, fileSize=11596235, fileHash=cf27837d54f6729533eec613ec115eea, number=14, id=0EPTGTS6WAF9N, seriesId=0EPTGTS6CAAR7, libraryId=0EN45HTVSFFNX, deletedDate=null, oneshot=false, createdDate=2024-01-02T19:33:02, lastModifiedDate=2024-01-03T17:38:42.756)
2024-01-03T18:29:40.213Z  INFO 1 --- [askProcessor-40] o.g.komga.domain.service.BookAnalyzer    : Detected media type: application/epub+zip
2024-01-03T18:29:40.216Z ERROR 1 --- [askProcessor-40] o.g.komga.domain.service.BookAnalyzer    : Error while analyzing book: Book(name=A Certain Magical Index SS - Agnese's Magic Side Work Trial, url=file:/data/LightNovels/A%20Certain%20Magical%20Index%20-%20Side%20Stories/A%20Certain%20Magical%20Index%20SS%20-%20Agnese's%20Magic%20Side%20Work%20Trial.epub, fileLastModified=2024-01-03T17:37:57.940, fileSize=11596235, fileHash=cf27837d54f6729533eec613ec115eea, number=14, id=0EPTGTS6WAF9N, seriesId=0EPTGTS6CAAR7, libraryId=0EN45HTVSFFNX, deletedDate=null, oneshot=false, createdDate=2024-01-02T19:33:02, lastModifiedDate=2024-01-03T17:38:42.756)
java.io.IOException: Error on ZipFile /data/LightNovels/A Certain Magical Index - Side Stories/A Certain Magical Index SS - Agnese's Magic Side Work Trial.epub
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:698) ~[commons-compress-1.24.0.jar:1.24.0]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:577) ~[commons-compress-1.24.0.jar:1.24.0]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:551) ~[commons-compress-1.24.0.jar:1.24.0]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:462) ~[commons-compress-1.24.0.jar:1.24.0]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:448) ~[commons-compress-1.24.0.jar:1.24.0]
	at org.gotson.komga.infrastructure.mediacontainer.epub.EpubExtractor.getManifest(EpubExtractor.kt:233) ~[classes/:1.9.2]
	at org.gotson.komga.domain.service.BookAnalyzer.analyzeEpub(BookAnalyzer.kt:130) ~[classes/:1.9.2]
	at org.gotson.komga.domain.service.BookAnalyzer.analyze(BookAnalyzer.kt:78) ~[classes/:1.9.2]
	at org.gotson.komga.domain.service.BookLifecycle.analyzeAndPersist(BookLifecycle.kt:77) ~[classes/:1.9.2]
	at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:89) ~[classes/:1.9.2]
	at org.gotson.komga.application.tasks.TaskProcessor.takeAndProcess(TaskProcessor.kt:60) ~[classes/:1.9.2]
	at org.gotson.komga.application.tasks.TaskProcessor.processAvailableTask$lambda$1(TaskProcessor.kt:46) ~[classes/:1.9.2]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.io.IOException: Central directory is empty, can't expand corrupt archive.
	at org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(ZipFile.java:1080) ~[commons-compress-1.24.0.jar:1.24.0]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:691) ~[commons-compress-1.24.0.jar:1.24.0]
	... 14 common frames omitted
```
Of a file that does work from the same series and with the same structure:
```
2024-01-03T18:29:40.220Z  INFO 1 --- [askProcessor-40] o.g.komga.application.tasks.TaskHandler  : Task AnalyzeBook(bookId='0EPTGTS6WAF9N', priority='6') executed in 9.344255ms
2024-01-03T18:30:33.234Z  INFO 1 --- [-25600-exec-175] o.g.komga.application.tasks.TaskEmitter  : Sending task: AnalyzeBook(bookId='0EPTGTS6WAF9M', priority='6')
2024-01-03T18:30:33.240Z  INFO 1 --- [askProcessor-40] o.g.komga.application.tasks.TaskHandler  : Executing task: AnalyzeBook(bookId='0EPTGTS6WAF9M', priority='6')
2024-01-03T18:30:33.241Z  INFO 1 --- [askProcessor-40] o.g.komga.domain.service.BookLifecycle   : Analyze and persist book: Book(name=A Certain Magical Index SP, url=file:/data/LightNovels/A%20Certain%20Magical%20Index%20-%20Side%20Stories/A%20Certain%20Magical%20Index%20SP.epub, fileLastModified=2024-01-02T18:52:24.555, fileSize=13589598, fileHash=aabee1af7d43f84913d9a86af8dec0f0, number=13, id=0EPTGTS6WAF9M, seriesId=0EPTGTS6CAAR7, libraryId=0EN45HTVSFFNX, deletedDate=null, oneshot=false, createdDate=2024-01-02T19:33:02, lastModifiedDate=2024-01-03T17:38:42.755)
2024-01-03T18:30:33.241Z  INFO 1 --- [askProcessor-40] o.g.komga.domain.service.BookAnalyzer    : Trying to analyze book: Book(name=A Certain Magical Index SP, url=file:/data/LightNovels/A%20Certain%20Magical%20Index%20-%20Side%20Stories/A%20Certain%20Magical%20Index%20SP.epub, fileLastModified=2024-01-02T18:52:24.555, fileSize=13589598, fileHash=aabee1af7d43f84913d9a86af8dec0f0, number=13, id=0EPTGTS6WAF9M, seriesId=0EPTGTS6CAAR7, libraryId=0EN45HTVSFFNX, deletedDate=null, oneshot=false, createdDate=2024-01-02T19:33:02, lastModifiedDate=2024-01-03T17:38:42.755)
2024-01-03T18:30:33.243Z  INFO 1 --- [askProcessor-40] o.g.komga.domain.service.BookAnalyzer    : Detected media type: application/epub+zip
2024-01-03T18:30:33.268Z  INFO 1 --- [askProcessor-40] o.g.komga.application.tasks.TaskEmitter  : Sending task: GenerateBookThumbnail(bookId='0EPTGTS6WAF9M', priority='7')
2024-01-03T18:30:33.273Z  INFO 1 --- [askProcessor-40] o.g.komga.application.tasks.TaskEmitter  : Sending task: RefreshBookMetadata(bookId='0EPTGTS6WAF9M', capabilities=[TITLE, SUMMARY, NUMBER, NUMBER_SORT, RELEASE_DATE, AUTHORS, TAGS, ISBN, READ_LISTS, THUMBNAILS, LINKS], priority='7')
2024-01-03T18:30:33.275Z  INFO 1 --- [askProcessor-40] o.g.komga.application.tasks.TaskHandler  : Task AnalyzeBook(bookId='0EPTGTS6WAF9M', priority='6') executed in 34.877933ms
2024-01-03T18:30:33.283Z  INFO 1 --- [askProcessor-40] o.g.komga.application.tasks.TaskHandler  : Executing task: GenerateBookThumbnail(bookId='0EPTGTS6WAF9M', priority='7')
2024-01-03T18:30:33.284Z  INFO 1 --- [askProcessor-40] o.g.komga.domain.service.BookLifecycle   : Generate thumbnail and persist for book: Book(name=A Certain Magical Index SP, url=file:/data/LightNovels/A%20Certain%20Magical%20Index%20-%20Side%20Stories/A%20Certain%20Magical%20Index%20SP.epub, fileLastModified=2024-01-02T18:52:24.555, fileSize=13589598, fileHash=aabee1af7d43f84913d9a86af8dec0f0, number=13, id=0EPTGTS6WAF9M, seriesId=0EPTGTS6CAAR7, libraryId=0EN45HTVSFFNX, deletedDate=null, oneshot=false, createdDate=2024-01-02T19:33:02, lastModifiedDate=2024-01-03T17:38:42.755)
2024-01-03T18:30:33.285Z  INFO 1 --- [askProcessor-40] o.g.komga.domain.service.BookAnalyzer    : Generate thumbnail for book: BookWithMedia(book=Book(name=A Certain Magical Index SP, url=file:/data/LightNovels/A%20Certain%20Magical%20Index%20-%20Side%20Stories/A%20Certain%20Magical%20Index%20SP.epub, fileLastModified=2024-01-02T18:52:24.555, fileSize=13589598, fileHash=aabee1af7d43f84913d9a86af8dec0f0, number=13, id=0EPTGTS6WAF9M, seriesId=0EPTGTS6CAAR7, libraryId=0EN45HTVSFFNX, deletedDate=null, oneshot=false, createdDate=2024-01-02T19:33:02, lastModifiedDate=2024-01-03T17:38:42.755), media=Media(status=READY, mediaType=application/epub+zip, comment=null, bookId='0EPTGTS6WAF9M', createdDate=2024-01-02T19:33:02, lastModifiedDate=2024-01-03T18:30:33.263))
2024-01-03T18:30:33.370Z  INFO 1 --- [askProcessor-40] o.g.komga.application.tasks.TaskHandler  : Task GenerateBookThumbnail(bookId='0EPTGTS6WAF9M', priority='7') executed in 86.477010ms
2024-01-03T18:30:33.375Z  INFO 1 --- [askProcessor-40] o.g.komga.application.tasks.TaskHandler  : Executing task: RefreshBookMetadata(bookId='0EPTGTS6WAF9M', capabilities=[AUTHORS, SUMMARY, NUMBER_SORT, READ_LISTS, THUMBNAILS, ISBN, NUMBER, TAGS, TITLE, LINKS, RELEASE_DATE], priority='7')
2024-01-03T18:30:33.376Z  INFO 1 --- [askProcessor-40] o.g.k.d.service.BookMetadataLifecycle    : Refresh metadata for book: Book(name=A Certain Magical Index SP, url=file:/data/LightNovels/A%20Certain%20Magical%20Index%20-%20Side%20Stories/A%20Certain%20Magical%20Index%20SP.epub, fileLastModified=2024-01-02T18:52:24.555, fileSize=13589598, fileHash=aabee1af7d43f84913d9a86af8dec0f0, number=13, id=0EPTGTS6WAF9M, seriesId=0EPTGTS6CAAR7, libraryId=0EN45HTVSFFNX, deletedDate=null, oneshot=false, createdDate=2024-01-02T19:33:02, lastModifiedDate=2024-01-03T17:38:42.755) with capabilities: [AUTHORS, SUMMARY, NUMBER_SORT, READ_LISTS, THUMBNAILS, ISBN, NUMBER, TAGS, TITLE, LINKS, RELEASE_DATE]
2024-01-03T18:30:33.381Z  INFO 1 --- [askProcessor-40] o.g.k.d.service.BookMetadataLifecycle    : Library is not set to import book or read lists metadata for this provider, skipping: IsbnBarcodeProvider
2024-01-03T18:30:33.399Z  INFO 1 --- [askProcessor-40] o.g.komga.application.tasks.TaskEmitter  : Sending task: RefreshSeriesMetadata(seriesId='0EPTGTS6CAAR7', priority='6')
2024-01-03T18:30:33.404Z  INFO 1 --- [askProcessor-40] o.g.komga.application.tasks.TaskHandler  : Task RefreshBookMetadata(bookId='0EPTGTS6WAF9M', capabilities=[AUTHORS, SUMMARY, NUMBER_SORT, READ_LISTS, THUMBNAILS, ISBN, NUMBER, TAGS, TITLE, LINKS, RELEASE_DATE], priority='7') executed in 28.341569ms
2024-01-03T18:30:33.408Z  INFO 1 --- [askProcessor-40] o.g.komga.application.tasks.TaskHandler  : Executing task: RefreshSeriesMetadata(seriesId='0EPTGTS6CAAR7', priority='6')
2024-01-03T18:30:33.409Z  INFO 1 --- [askProcessor-40] o.g.k.d.service.SeriesMetadataLifecycle  : Refresh metadata for series: Series(name=A Certain Magical Index - Side Stories, url=file:/data/LightNovels/A%20Certain%20Magical%20Index%20-%20Side%20Stories/, fileLastModified=2024-01-03T17:38:25.402, id=0EPTGTS6CAAR7, libraryId=0EN45HTVSFFNX, bookCount=27, deletedDate=null, oneshot=false, createdDate=2024-01-02T19:33:02, lastModifiedDate=2024-01-03T17:38:42.490)
2024-01-03T18:30:33.643Z  INFO 1 --- [askProcessor-40] o.g.komga.application.tasks.TaskEmitter  : Sending task: AggregateSeriesMetadata(seriesId='0EPTGTS6CAAR7', priority='6')
2024-01-03T18:30:33.647Z  INFO 1 --- [askProcessor-40] o.g.komga.application.tasks.TaskHandler  : Task RefreshSeriesMetadata(seriesId='0EPTGTS6CAAR7', priority='6') executed in 238.618290ms
2024-01-03T18:30:33.658Z  INFO 1 --- [askProcessor-40] o.g.komga.application.tasks.TaskHandler  : Executing task: AggregateSeriesMetadata(seriesId='0EPTGTS6CAAR7', priority='6')
2024-01-03T18:30:33.659Z  INFO 1 --- [askProcessor-40] o.g.k.d.service.SeriesMetadataLifecycle  : Aggregate book metadata for series: Series(name=A Certain Magical Index - Side Stories, url=file:/data/LightNovels/A%20Certain%20Magical%20Index%20-%20Side%20Stories/, fileLastModified=2024-01-03T17:38:25.402, id=0EPTGTS6CAAR7, libraryId=0EN45HTVSFFNX, bookCount=27, deletedDate=null, oneshot=false, createdDate=2024-01-02T19:33:02, lastModifiedDate=2024-01-03T17:38:42.490)
2024-01-03T18:30:33.671Z  INFO 1 --- [askProcessor-40] o.g.komga.application.tasks.TaskHandler  : Task AggregateSeriesMetadata(seriesId='0EPTGTS6CAAR7', priority='6') executed in 11.314278ms
```
### Komga version

1.9.2

### Operating system

Lubuntu

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
pretty explicit to me: `Caused by: java.io.IOException: Central directory is empty, can't expand corrupt archive.`
