### ISSUE TITLE
Unable to generate book thumbnail (endless loading)

### ISSUE THREAD

**Issue by chcoomilk** [gotson/komga#1407]
### Steps to reproduce

I noticed after adding libraries, the loading progress on top of the sidebar is not going away. When hovered over it says 
```
<some numbers> pending tasks
GenerateBookThumbnail <the same some numbers>
```

so I checked the log to find a clue and found out there was this recurring error message

it's running on ubuntu 23.10 wayland, I noticed it mentioned X11 and I'm running on wayland, is this related and I need to be on X11 to run this server, or is it something else?
`Caused by: java.lang.ExceptionInInitializerError: Exception java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable. [in thread "task-6"]`

### Expected behavior

Able to see my manga covers

### Actual behavior

I don't see any manga covers/thumbnails on my library

### Logs
```
Jan 24 23:17:51 chocomilk-nuc komga[2498667]: Exception in thread "taskProcessor-20" java.lang.NoClassDefFoundError: Could not initialize class java.awt.GraphicsEnvironment$LocalGE
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.desktop/java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1182)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at net.coobird.thumbnailator.resizers.AbstractResizer.createGraphics(Unknown Source)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at net.coobird.thumbnailator.resizers.ProgressiveBilinearResizer.resize(Unknown Source)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at net.coobird.thumbnailator.resizers.Resizers.resize(Unknown Source)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at net.coobird.thumbnailator.makers.ThumbnailMaker.makeThumbnail(Unknown Source)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at net.coobird.thumbnailator.makers.FixedSizeThumbnailMaker.make(Unknown Source)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at net.coobird.thumbnailator.Thumbnails$Builder.toOutputStream(Unknown Source)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at org.gotson.komga.infrastructure.image.ImageConverter.resizeImageToByteArray(ImageConverter.kt:99)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at org.gotson.komga.domain.service.BookAnalyzer.generateThumbnail(BookAnalyzer.kt:192)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at org.gotson.komga.domain.service.BookLifecycle.generateThumbnailAndPersist(BookLifecycle.kt:125)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:95)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at org.gotson.komga.application.tasks.TaskProcessor.takeAndProcess(TaskProcessor.kt:63)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at org.gotson.komga.application.tasks.TaskProcessor.processAvailableTask$lambda$1(TaskProcessor.kt:47)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.base/java.lang.Thread.run(Thread.java:1583)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]: Caused by: java.lang.ExceptionInInitializerError: Exception java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable. [in thread "task-6"]
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:105)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.desktop/sun.awt.X11GraphicsEnvironment.initStatic(X11GraphicsEnvironment.java:64)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:59)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.desktop/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:37)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:93)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:84)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:225)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(PlatformGraphicsInfo.java:41)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:595)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.desktop/java.awt.Toolkit.getEventQueue(Toolkit.java:1489)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.desktop/java.awt.EventQueue.invokeLater(EventQueue.java:1316)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.desktop/javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1421)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at org.jetbrains.skiko.SwingDispatcher.dispatch(MainUIDispatcher.awt.kt:32)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:322)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:172)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at androidx.compose.ui.window.Application_desktopKt.awaitApplication(Application.desktop.kt:198)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at androidx.compose.ui.window.Application_desktopKt$application$1.invokeSuspend(Application.desktop.kt:114)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at androidx.compose.ui.window.Application_desktopKt.application(Application.desktop.kt:113)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at androidx.compose.ui.window.Application_desktopKt.application$default(Application.desktop.kt:105)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at org.gotson.komga.application.gui.TrayIconRunner.runTray(TrayIconRunner.kt:40)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at org.gotson.komga.application.gui.TrayIconRunner.run(TrayIconRunner.kt:36)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:113)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
Jan 24 23:17:51 chocomilk-nuc komga[2498667]:         ... 3 more
```
### Komga version

v1.10.3-master

### Operating system

Distributor ID: Ubuntu Description:    Ubuntu 23.10 Release:        23.10 Codename:       mantic

### Installation method

from download.komga.org

### Other details

I was trying Kavita the other day and there's no issue generating thumbnails and all that, but Kavita can't parse my long manga folder names and the issue is not very clear so I have to hop out from there

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [x] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Java may not be Wayland ready?

Are you using the deb file because you have a Linux desktop computer, or do you have a linux headless server and you use the deb for convenience ?

**Comment by gotson** [comment]
AWT / Swing does not work on Wayland yet: https://wiki.openjdk.org/display/wakefield

As an alternative you can run the jar file or the Docker image.

**Comment by chcoomilk** [comment]
> Are you using the deb file because you have a Linux desktop computer, or do you have a linux headless server and you use the deb for convenience ?

forgive me but, mostly for convenience sake.. I'm a lazy bum and figured running `komga` is much shorter than `java -jar /.../komga.jar` plus I thought there's ppa repo or something so updating is way easier to do by doing apt update and upgrade, so I followed and continued that path

> As an alternative you can run the jar file or the Docker image

I'm running it off the jar file and everything is working perfectly fine now, thanks
