### ISSUE TITLE
[Bug] Error 400 to client and java.lang.IllegalArgumentException in log if hostname contains underscore

### ISSUE THREAD

**Issue by clach04** [gotson/komga#152]
### Komga environment
- **OS**: Windows 8 - Microsoft Windows [Version 6.3.9600]
- **Komga version**:  0.28.4
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]:  NA
- [X] **I am running Komga from the `jar`**
  - Java version: 1.8
- [X] **I have a problem in the web interface**
  - Browser (with version): Found first with OPDS support but in web site to
- [X] **I have a problem with an OPDS client application**
  - OPDS Application (with version): Firefox
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version:  NA
  - Tachiyomi extension version: NA

### Describe the bug

I have a (Windows) machine name with an underscore in it. Runs a number of different webservers with no problem. Getting errors in log when connecting to it with the valid hostname

See logfile section
### Steps to reproduce
1. I guess setup an alias for dns lookup in localhosts file
2. Use web browser to access

### Expected behavior

200 :-)

### Actual behavior
What happened instead.

400 / Crash

### Additional context

NA

### Screenshots

NA

### Log file
If applicable, add an excerpt of the log file (max 20 lines), or a link to a gist containing the log file.

    2020-05-06 21:09:19.442  INFO 7472 --- [nio-8080-exec-4] o.apache.coyote.http11.
    Http11Processor   : The host [asus_vevo:8080] is not valid
     Note: further occurrences of request parsing errors will be logged at DEBUG lev
    el.

    java.lang.IllegalArgumentException: The character [_] is never valid in a domain
     name.
            at org.apache.tomcat.util.http.parser.HttpParser$DomainParseState.next(H
    ttpParser.java:974) ~[tomcat-embed-core-9.0.33.jar!/:9.0.33]
            at org.apache.tomcat.util.http.parser.HttpParser.readHostDomainName(Http
    Parser.java:870) ~[tomcat-embed-core-9.0.33.jar!/:9.0.33]
            at org.apache.tomcat.util.http.parser.Host.parse(Host.java:71) ~[tomcat-
    embed-core-9.0.33.jar!/:9.0.33]
            at org.apache.tomcat.util.http.parser.Host.parse(Host.java:45) ~[tomcat-
    embed-core-9.0.33.jar!/:9.0.33]
            at org.apache.coyote.AbstractProcessor.parseHost(AbstractProcessor.java:
    294) ~[tomcat-embed-core-9.0.33.jar!/:9.0.33]
            at org.apache.coyote.http11.Http11Processor.prepareRequest(Http11Process
    or.java:776) [tomcat-embed-core-9.0.33.jar!/:9.0.33]
            at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java
    :349) [tomcat-embed-core-9.0.33.jar!/:9.0.33]
            at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLig
    ht.java:65) [tomcat-embed-core-9.0.33.jar!/:9.0.33]
            at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(Abstract
    Protocol.java:868) [tomcat-embed-core-9.0.33.jar!/:9.0.33]
            at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpo
    int.java:1594) [tomcat-embed-core-9.0.33.jar!/:9.0.33]
            at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBas
    e.java:49) [tomcat-embed-core-9.0.33.jar!/:9.0.33]
            at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na
    :1.8.0_66]
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [n
    a:1.8.0_66]
            at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskTh
    read.java:61) [tomcat-embed-core-9.0.33.jar!/:9.0.33]
            at java.lang.Thread.run(Unknown Source) [na:1.8.0_66]

**Comment by gotson** [comment]
`_` is not a valid character in domain names, see [here](https://stackoverflow.com/a/53877431/2041863) for details (Komga uses Spring Boot with Tomcat).

Other servers may work properly, but don't respect the specification.

You will need to change your hostname to avoid those characters.

**Comment by clach04** [comment]
Making sure I understand; this is a SpringBoot behavior (appears to have started around version 1.5.20, not present in 1.4.2). This isn't configurable so Komga has no control over this.

I can't easily change the hostname of the machine **but** I can change the hostname used in the URL :)

Thanks for the quick response!

**Comment by gotson** [comment]
It's a Tomcat issue, the servlet server used by Spring Boot. I'm using Spring Boot 2.2.x at the moment.
