### ISSUE TITLE
Media that constantly crash on scanning at startup

### ISSUE THREAD

**Issue by BDeus** [gotson/komga#1644]
### Steps to reproduce

Hi,
i have a pdf media that constently crash on startup with a `java.lang.OutOfMemoryError: Java heap space`
I increase the config to variables to `-xmx8g` but still have an error.
Is not a real issue for me, i don't care about that specific metadata is not available.
The only thing that borrow me is that the scan bar on left top constantly remains active with `RefreshBookMetadata: 1`

### Expected behavior

Is there a way to ignore scanning of specific directory or media ?

### Actual behavior

Bar on left top constantly remains active with `RefreshBookMetadata: 1`

### Logs

```
2024-08-04T09:03:00.026Z  INFO 1 --- [taskProcessor-1] o.g.k.d.service.BookMetadataLifecycle    : Refresh metadata for book: Book(...) with capabilities: [ISBN, THUMBNAILS, LINKS, TITLE, SUMMARY, RELEASE_DATE, NUMBER_SORT, AUTHORS, NUMBER, READ_LISTS, TAGS]
Exception in thread "taskProcessor-1" java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.desktop/java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.desktop/java.awt.image.BufferedImage.<init>(Unknown Source)
	at org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:304)
	at org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:247)
	at org.gotson.komga.infrastructure.mediacontainer.pdf.PdfExtractor.getPageContentAsImage(PdfExtractor.kt:48)
	at org.gotson.komga.domain.service.BookAnalyzer.getPageContent(BookAnalyzer.kt:242)
	at org.gotson.komga.infrastructure.metadata.barcode.IsbnBarcodeProvider.getBookMetadataFromBook(IsbnBarcodeProvider.kt:51)
	at org.gotson.komga.domain.service.BookMetadataLifecycle.refreshMetadata(BookMetadataLifecycle.kt:51)
	at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:100)
	at org.gotson.komga.application.tasks.TaskProcessor.takeAndProcess(TaskProcessor.kt:63)
	at org.gotson.komga.application.tasks.TaskProcessor.processAvailableTask$lambda$1(TaskProcessor.kt:47)
	at org.gotson.komga.application.tasks.TaskProcessor$$Lambda/0x00007f5bf8c29690.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.runWith(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Komga version

1.11.2

### Operating system

Linux

### Installation method

Docker

### Other details

Docker Engine 24.0.6

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
is it only 1 book or all the books ? how much ram does your system has?

**Comment by BDeus** [comment]
It is only 1 book a specific pdf one.
I think it might be corrupt in some kind of way, but i can open and read it.
The system is a docker one but the host as 16GB.

**Comment by gotson** [comment]
> I think it might be corrupt in some kind of way, but i can open and read it.

You mean you can open the file with another software/application ?

How big is the file ?
