### ISSUE TITLE
i cannot install by java

### ISSUE THREAD

**Issue by 6713lyp** [gotson/komga#1717]
### Steps to reproduce

PS C:\Users\Lenovo\komga-1.14.0> java -jar komga-1.14.0.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/springframework/boot/loader/launch/JarLauncher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

### Expected behavior

i want to install it

### Actual behavior

i do not know

### Komga version

1.14.0

### Operating system

win11

### Installation method

jar

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gameaddict2724** [comment]
according to the line this `version of the Java Runtime only recognizes class file versions up to 52.0` you are running older version of java. to run komga u will Java version 17 or newer.
read the following 
https://komga.org/docs/installation/jar

**Comment by gotson** [comment]
As mentioned in the previous comment, your Java is too old. You can check the version using `java -version`
