### ISSUE TITLE
Can't delete files or series due to java.nio.file.AccessDeniedException

### ISSUE THREAD

**Issue by Merkulese** [gotson/komga#1754]
### Steps to reproduce

1. In the web UI select book or series (same result with both)
2. click delete button
3. confirm delete by checking box on pop up
4. press delete button on pup up

### Expected behavior

files should be marked unavailable and should be removed when trash is emptied

### Actual behavior

The confirm delete pop up closes once confirmation is given and then nothing happens afterwards

### Logs

2024-10-27T09:03:55.678Z  INFO 35520 --- [taskProcessor-15] o.g.komga.application.tasks.TaskHandler  : Executing task: DeleteBook(bookId='0HMXGM0NS3627', priority='8')
2024-10-27T09:03:55.681Z ERROR 35520 --- [taskProcessor-17] o.g.komga.application.tasks.TaskHandler  : Task DeleteBook(bookId='0HMXGM0NN323Q', priority='8') execution failed

java.nio.file.AccessDeniedException: E:\Storage\Books\Tachidesk Library\downloads\mangas\MangaDex (EN)\Ninja Papa\Colourful Abyss_Vol.1 Ch.2.cbz
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[na:na]
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[na:na]
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[na:na]
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:273) ~[na:na]
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:109) ~[na:na]
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191) ~[na:na]
	at org.gotson.komga.domain.service.BookLifecycle.deleteBookFiles(BookLifecycle.kt:524) ~[komga-1.14.1-plain.jar:na]
	at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:167) ~[komga-1.14.1-plain.jar:na]
	at org.gotson.komga.application.tasks.TaskProcessor.takeAndProcess(TaskProcessor.kt:64) ~[komga-1.14.1-plain.jar:na]
	at org.gotson.komga.application.tasks.TaskProcessor.processAvailableTask$lambda$2(TaskProcessor.kt:52) ~[komga-1.14.1-plain.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

### Komga version

1.14.1

### Operating system

windows 10

### Installation method

from download.komga.org

### Other details

My komga account is an admin so should have access to the functionality and the folders in my filesystem are accessible both in komga and locally through windows wihtout issue. I've had previous version of komga installed but have only had this issue when using 1.14.1 and can't find any reason why acess would be denied

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by Merkulese** [comment]
Sorry, forgot to add that I've tested this both on my server where komga is hosted and accessing the web UI from another machine and the results are the same.

**Comment by gotson** [comment]
it means Komga does not have access to delete the file on the filesystem. Check your permissions.

**Comment by gotson** [comment]
If it says it can't access, it can't access. I can't really help more on that.

**Comment by Merkulese** [comment]
No worries, I checked all permissions and they were fine but I managed to fix it anyway by running komga as administrator instead
