### ISSUE TITLE
Komga on Linux Mint will not start since last update (1.15.1)

### ISSUE THREAD

**Issue by most-likely-2b** [gotson/komga#1799]
### Steps to reproduce

1.) Re-install Komga Linux version 1.15.1 from komga website on Linux Mint 22.
2.) Run application. 
3.) Try to access existing server via IP address and port number. 

### Expected behavior

The application should start in the system tray and the server should be accessible in the web browser.

### Actual behavior

Application will not start, and trying to access server in web browser results in an "Unable" to connect page (Firefox). 

### Logs
```
2024-12-20T17:29:03.204Z  INFO 15507 --- [main] org.gotson.komga.DesktopApplicationKt    : Starting DesktopApplicationKt using Java 22.0.2 with PID 15507 (/usr/lib/gotson/komga/lib/app/komga-tray-1.15.1.jar started by kyle in /home/kyle)
2024-12-20T17:29:03.206Z  INFO 15507 --- [main] org.gotson.komga.DesktopApplicationKt    : No active profile set, falling back to 1 default profile: "default"
2024-12-20T17:29:03.956Z  WARN 15507 --- [main] c.github.gotson.nightcompress.Archive    : Could not load libarchive. no archive in java.library.path: /usr/lib/gotson/komga/lib/app/../runtime/lib/:/usr/lib/gotson/komga/lib/app
2024-12-20T17:29:03.959Z  WARN 15507 --- [main] o.s.c.a.ConfigurationClassPostProcessor  : Cannot enhance @Configuration bean definition 'rar5Configuration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static' and/or marking the containing configuration class as 'proxyBeanMethods=false'.
```
[komga.log](https://github.com/user-attachments/files/18213640/komga.log)

### Komga version

1.15.1

### Operating system

Linux Mint 22

### Installation method

from download.komga.org

### Other details

I cannot make sense of the log; please find full log attached. 

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by Merkulese** [comment]
> ### Steps to reproduce
> 
> 1.) Re-install Komga Linux version 1.15.1 from komga website on Linux Mint 22. 2.) Run application. 3.) Try to access existing server via IP address and port number.
> ### Expected behavior
> 
> The application should start in the system tray and the server should be accessible in the web browser.
> ### Actual behavior
> 
> Application will not start, and trying to access server in web browser results in an "Unable" to connect page (Firefox).
> ### Logs
> 
> 2024-12-20T17:29:03.204Z INFO 15507 --- [main] org.gotson.komga.DesktopApplicationKt : Starting DesktopApplicationKt using Java 22.0.2 with PID 15507 (/usr/lib/gotson/komga/lib/app/komga-tray-1.15.1.jar started by kyle in /home/kyle) 2024-12-20T17:29:03.206Z INFO 15507 --- [main] org.gotson.komga.DesktopApplicationKt : No active profile set, falling back to 1 default profile: "default" 2024-12-20T17:29:03.956Z WARN 15507 --- [main] c.github.gotson.nightcompress.Archive : Could not load libarchive. no archive in java.library.path: /usr/lib/gotson/komga/lib/app/../runtime/lib/:/usr/lib/gotson/komga/lib/app 2024-12-20T17:29:03.959Z WARN 15507 --- [main] o.s.c.a.ConfigurationClassPostProcessor : Cannot enhance @configuration bean definition 'rar5Configuration' since its singleton instance has been created too early. The typical cause is a non-static @bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static' and/or marking the containing configuration class as 'proxyBeanMethods=false'. [komga.log](https://github.com/user-attachments/files/18213640/komga.log)
> ### Komga version
> 
> 1.15.1
> ### Operating system
> 
> Linux Mint 22
> ### Installation method
> 
> from download.komga.org
> ### Other details
> 
> I cannot make sense of the log; please find full log attached.
> ### Acknowledgements
> 
>     * [x]  I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
> 
>     * [x]  I have written a short but informative title.
> 
>     * [x]  I have checked the [FAQ](https://komga.org/docs/faq).
> 
>     * [x]  I have updated the app to the latest version.
> 
>     * [x]  I will fill out all of the requested information in this form.

I have the same issue on my server running Mint. I made a copy of the database.sqlite file so I didn't have to rescan and set up everything again (found in /home/USER/.komga), uninstalled and then reinstalled version 1.14.1 using the below command the command line. I took them from the official download page and just changed the version numbers so it pointed to a previous one.


```
CPU=$(dpkg --print-architecture)
wget https://download.komga.org/debian/gotson-komga_1.15.1_${CPU}.deb
sudo apt install ./gotson-komga_1.15.1_${CPU}.deb
```

It's not a fix but at least you'll be able to keep using it until Gotson is able to get around to making any changes, but I would assume they're taking a well deserved break for Christmas and new year

**Comment by gotson** [comment]
the logs show that the app is started and running, nothing unusual

**Comment by most-likely-2b** [comment]
What do you recommend my next steps should be? The application is still not starting and I still can't access my server in the browser.

**Comment by most-likely-2b** [comment]
As posted above by Merkulese, rolling back to version 1.14.1 has fixed the behaviour, so I can confirm that something in versions 1.15.0 and beyond is causing this issue.

**Comment by aqiarch27** [comment]
I am also having the issue. Linux Mint 21.3 
Rolling back to 1.14.1 worked for a while but then komga updated automatically and stopped working again. Application does not start in system tray and is not accessible through browser.

**Comment by gotson** [comment]
> What do you recommend my next steps should be? The application is still not starting and I still can't access my server in the browser.

the application does start, the logs say so.

> but then komga updated automatically

Komga does not auto update on Linux, you probably updated using `apt`

**Comment by Merkulese** [comment]
I've got some info that might help point us in the right direction: As Gotson and the logs show, the app does start but in my observations using system monitor (task manager) I can see when it loads up, uses resources and then after a minute or two reduces all resource usage to nothing and then closes. Unfortunately I've not been able to find out exactly why it happens but it does so every time the app is started. For updating, the latest version of komga appears in the update manager and the issue only started on my server after updating to 1.15.1. I tried rolling back to 1.15.0 but that also had the same issue of the app opening and then auto-closing after a short time.

I've just seen the 1.16.0 update and haven't tested it yet but will check at some point in the next day or so and feedback the results here

**Comment by Merkulese** [comment]
Issue remains on 1.16.0. app runs for a moment and then auto-closes so I've rolled back to 1.14.1 again

**Comment by Merkulese** [comment]
Tested a clean install of version 1.17 and am getting the same result. I've put the log below but the only thing I can see in it that might be relevant is a task rejected exception which leads to an eventual shut down

```
2025-01-10T07:44:59.142Z  INFO 1860340 --- [main] org.gotson.komga.DesktopApplicationKt    : Starting DesktopApplicationKt using Java 22.0.2 with PID 1860340 (/usr/lib/gotson/komga/lib/app/komga-tray-1.17.0.jar started by flameingskull in /home/flameingskull)
2025-01-10T07:44:59.147Z  INFO 1860340 --- [main] org.gotson.komga.DesktopApplicationKt    : No active profile set, falling back to 1 default profile: "default"
2025-01-10T07:45:01.495Z  WARN 1860340 --- [main] c.github.gotson.nightcompress.Archive    : Could not load libarchive. no archive in java.library.path: /usr/lib/gotson/komga/lib/app/../runtime/lib/:/usr/lib/gotson/komga/lib/app
2025-01-10T07:45:01.501Z  WARN 1860340 --- [main] o.s.c.a.ConfigurationClassPostProcessor  : Cannot enhance @Configuration bean definition 'rar5Configuration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static' and/or marking the containing configuration class as 'proxyBeanMethods=false'.
2025-01-10T07:45:02.171Z  INFO 1860340 --- [main] com.zaxxer.hikari.HikariDataSource       : SqliteMainPool - Starting...
2025-01-10T07:45:02.342Z  INFO 1860340 --- [main] com.zaxxer.hikari.pool.HikariPool        : SqliteMainPool - Added connection org.sqlite.jdbc4.JDBC4Connection@1c512bb
2025-01-10T07:45:02.344Z  INFO 1860340 --- [main] com.zaxxer.hikari.HikariDataSource       : SqliteMainPool - Start completed.
2025-01-10T07:45:02.537Z  INFO 1860340 --- [main] org.flywaydb.core.FlywayExecutor         : Database: jdbc:sqlite:/home/flameingskull/.komga/database.sqlite (SQLite 3.47)
2025-01-10T07:45:02.629Z  INFO 1860340 --- [main] o.f.core.internal.command.DbValidate     : Successfully validated 88 migrations (execution time 00:00.064s)
2025-01-10T07:45:02.638Z  INFO 1860340 --- [main] o.f.core.internal.command.DbMigrate      : Current version of schema "main": 20250108172343
2025-01-10T07:45:02.642Z  INFO 1860340 --- [main] o.f.core.internal.command.DbMigrate      : Schema "main" is up to date. No migration necessary.
2025-01-10T07:45:03.628Z  INFO 1860340 --- [main] o.j.i.D.logVersionSupport                : Version                  : Database version is supported by dialect SQLITE: 3.47.1
2025-01-10T07:45:03.857Z  INFO 1860340 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 25600 (http)
2025-01-10T07:45:03.870Z  INFO 1860340 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-01-10T07:45:03.870Z  INFO 1860340 --- [main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.33]
2025-01-10T07:45:03.919Z  INFO 1860340 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-01-10T07:45:03.920Z  INFO 1860340 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 4726 ms
2025-01-10T07:45:04.418Z  INFO 1860340 --- [main] o.g.k.i.kobo.KepubConverter              : Kepub conversion unavailable. kepubify path is not set
2025-01-10T07:45:04.461Z  WARN 1860340 --- [main] c.g.g.n.h.i.plugins.HeifImageReaderSpi   : Could not load libheif, plugin will be disabled. no heif in java.library.path: /usr/lib/gotson/komga/lib/app/../runtime/lib/:/usr/lib/gotson/komga/lib/app
2025-01-10T07:45:04.462Z  INFO 1860340 --- [main] c.g.g.n.h.i.plugins.HeifImageReaderSpi   : Deregistering service provider
2025-01-10T07:45:04.467Z  WARN 1860340 --- [main] c.g.g.n.w.i.plugins.WebpImageReaderSpi   : Could not load libwebp, plugin will be disabled. no webp in java.library.path: /usr/lib/gotson/komga/lib/app/../runtime/lib/:/usr/lib/gotson/komga/lib/app
2025-01-10T07:45:04.468Z  INFO 1860340 --- [main] c.g.g.n.w.i.plugins.WebpImageReaderSpi   : Deregistering service provider
2025-01-10T07:45:04.481Z  WARN 1860340 --- [main] c.g.g.n.j.i.plugins.JxlImageReaderSpi    : Could not load libjxl, plugin will be disabled. no jxl in java.library.path: /usr/lib/gotson/komga/lib/app/../runtime/lib/:/usr/lib/gotson/komga/lib/app
2025-01-10T07:45:04.482Z  INFO 1860340 --- [main] c.g.g.n.j.i.plugins.JxlImageReaderSpi    : Deregistering service provider
2025-01-10T07:45:04.484Z  INFO 1860340 --- [main] o.g.k.i.image.ImageConverter             : Supported read formats: [JPEG 2000, JPG, tiff, bmp, bigtiff, PCX, wbp, gif, WBMP, PNG, RAW, JPEG, PNM, BigTIFF, tif, TIFF, wbmp, jpeg, jbig2, jpeg-lossless, jpg, JPEG2000, BMP, pcx, WBP, GIF, png, BIGTIFF, raw, JPEG-LOSSLESS, webp, JBIG2, pnm, TIF, jpeg2000, WEBP, jpeg 2000]
2025-01-10T07:45:04.484Z  INFO 1860340 --- [main] o.g.k.i.image.ImageConverter             : Supported read mediaTypes: [image/vnd.wap.wbmp, image/jpeg, image/x-portable-graymap, image/bmp, image/x-windows-pcx, image/gif, image/x-pc-paintbrush, image/x-raw, image/webp, image/x-pcx, image/x-portable-bitmap, image/png, image/x-jb2, image/pcx, image/x-windows-bmp, image/x-webp, image/jpeg2000, image/x-bmp, image/jp2, image/x-png, image/x-portable-pixmap, image/tiff, image/x-tiff, image/x-jbig2, image/x-portable-anymap]
2025-01-10T07:45:04.484Z  INFO 1860340 --- [main] o.g.k.i.image.ImageConverter             : Supported write formats: [JPEG 2000, JPG, tiff, PCX, bmp, bigtiff, gif, WBMP, PNG, RAW, JPEG, PNM, BigTIFF, tif, TIFF, jpeg, wbmp, jpg, JPEG2000, pcx, BMP, GIF, png, raw, BIGTIFF, pnm, TIF, jpeg2000, jpeg 2000]
2025-01-10T07:45:04.485Z  INFO 1860340 --- [main] o.g.k.i.image.ImageConverter             : Supported write mediaTypes: [image/png, image/vnd.wap.wbmp, image/jpeg, image/x-portable-graymap, image/pcx, image/bmp, image/x-windows-pcx, image/x-windows-bmp, image/gif, image/x-pc-paintbrush, image/jpeg2000, image/x-raw, image/x-pcx, image/jp2, image/x-bmp, image/x-png, image/x-portable-bitmap, image/x-portable-pixmap, image/tiff, image/x-tiff, image/x-portable-anymap]
2025-01-10T07:45:04.634Z  INFO 1860340 --- [main] com.zaxxer.hikari.HikariDataSource       : SqliteTasksPool - Starting...
2025-01-10T07:45:04.635Z  INFO 1860340 --- [main] com.zaxxer.hikari.pool.HikariPool        : SqliteTasksPool - Added connection org.sqlite.jdbc4.JDBC4Connection@60ddad4
2025-01-10T07:45:04.636Z  INFO 1860340 --- [main] com.zaxxer.hikari.HikariDataSource       : SqliteTasksPool - Start completed.
2025-01-10T07:45:04.654Z  INFO 1860340 --- [main] org.flywaydb.core.FlywayExecutor         : Database: jdbc:sqlite:/home/flameingskull/.komga/tasks.sqlite (SQLite 3.47)
2025-01-10T07:45:04.661Z  INFO 1860340 --- [main] o.f.core.internal.command.DbValidate     : Successfully validated 1 migration (execution time 00:00.004s)
2025-01-10T07:45:04.663Z  INFO 1860340 --- [main] o.f.core.internal.command.DbMigrate      : Current version of schema "main": 20231013114850
2025-01-10T07:45:04.663Z  INFO 1860340 --- [main] o.f.core.internal.command.DbMigrate      : Schema "main" is up to date. No migration necessary.
2025-01-10T07:45:04.984Z  WARN 1860340 --- [main] org.apache.lucene.store.MMapDirectory    : You are running with Java 22 or later. To make full use of MMapDirectory, please update Apache Lucene.
2025-01-10T07:45:06.094Z  INFO 1860340 --- [main] eAuthenticationProviderManagerConfigurer : Global AuthenticationManager configured with AuthenticationProvider bean with name apiKeyAuthenticationProvider
2025-01-10T07:45:06.161Z  INFO 1860340 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [public/index.html]
2025-01-10T07:45:06.579Z  INFO 1860340 --- [main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 19 endpoints beneath base path '/actuator'
2025-01-10T07:45:07.152Z  INFO 1860340 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 25600 (http) with context path '/'
2025-01-10T07:45:07.155Z  INFO 1860340 --- [main] org.gotson.komga.DesktopApplicationKt    : Started DesktopApplicationKt in 8.461 seconds (process running for 8.817)
2025-01-10T07:45:07.165Z  INFO 1860340 --- [scheduling-1] .AuthenticationActivityCleanupController : Remove authentication activity older than 2024-12-10T07:45:07.164414245 (UTC)
2025-01-10T07:45:07.168Z  INFO 1860340 --- [task-2] g.k.i.s.ThumbnailMetadataFixerController : Find and fix thumbnails without metadata
2025-01-10T07:45:07.170Z  INFO 1860340 --- [task-7] o.g.k.i.scheduler.SearchIndexController  : Lucene index not found, trigger rebuild
2025-01-10T07:45:07.171Z  INFO 1860340 --- [task-2] o.g.komga.application.tasks.TaskEmitter  : Sending task: FixThumbnailsWithoutMetadata(priority='0')
2025-01-10T07:45:07.171Z  INFO 1860340 --- [task-7] o.g.komga.application.tasks.TaskEmitter  : Sending task: RebuildIndex(priority='8',entities='null')
2025-01-10T07:45:07.418Z  INFO 1860340 --- [SpringApplicationShutdownHook] o.s.b.w.e.tomcat.GracefulShutdown        : Commencing graceful shutdown. Waiting for active requests to complete
2025-01-10T07:45:07.464Z  INFO 1860340 --- [tomcat-shutdown] o.s.b.w.e.tomcat.GracefulShutdown        : Graceful shutdown complete
2025-01-10T07:45:07.729Z  INFO 1860340 --- [taskProcessor-1] o.g.komga.application.tasks.TaskHandler  : Executing task: RebuildIndex(priority='8',entities='null')
2025-01-10T07:45:07.734Z  INFO 1860340 --- [taskProcessor-1] o.g.k.i.search.SearchIndexLifecycle      : Rebuild index for: [book, series, collection, readlist]
2025-01-10T07:45:07.736Z  INFO 1860340 --- [taskProcessor-1] o.g.k.i.search.SearchIndexLifecycle      : Rebuilding index for Book
2025-01-10T07:45:07.866Z  INFO 1860340 --- [taskProcessor-1] o.g.k.i.search.SearchIndexLifecycle      : Number of entities: 0
2025-01-10T07:45:07.894Z ERROR 1860340 --- [taskProcessor-1] o.g.komga.application.tasks.TaskHandler  : Task RebuildIndex(priority='8',entities='null') execution failed

org.springframework.core.task.TaskRejectedException: ExecutorService in shutdown state did not accept task: org.gotson.komga.infrastructure.search.LuceneHelper$$Lambda/0x000000004ca7d4e0@7b179cf
	at org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler.schedule(ThreadPoolTaskScheduler.java:430) ~[spring-context-6.2.0.jar:6.2.0]
	at org.gotson.komga.infrastructure.search.LuceneHelper.commitAndMaybeRefresh(LuceneHelper.kt:139) ~[komga-1.17.0-plain.jar:na]
	at org.gotson.komga.infrastructure.search.LuceneHelper.deleteDocuments(LuceneHelper.kt:125) ~[komga-1.17.0-plain.jar:na]
	at org.gotson.komga.infrastructure.search.SearchIndexLifecycle.rebuildIndex(SearchIndexLifecycle.kt:69) ~[komga-1.17.0-plain.jar:na]
	at org.gotson.komga.infrastructure.search.SearchIndexLifecycle.rebuildIndex(SearchIndexLifecycle.kt:46) ~[komga-1.17.0-plain.jar:na]
	at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:164) ~[komga-1.17.0-plain.jar:na]
	at org.gotson.komga.application.tasks.TaskProcessor.takeAndProcess(TaskProcessor.kt:65) ~[komga-1.17.0-plain.jar:na]
	at org.gotson.komga.application.tasks.TaskProcessor.processAvailableTask$lambda$1(TaskProcessor.kt:48) ~[komga-1.17.0-plain.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[na:na]
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2d00add[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@5ee1522e[Wrapped task = DelegatingErrorHandlingRunnable for org.gotson.komga.infrastructure.search.LuceneHelper$$Lambda/0x000000004ca7d4e0@7b179cf]] rejected from org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler$1@cf933b1[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562) ~[na:na]
	at org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler.schedule(ThreadPoolTaskScheduler.java:427) ~[spring-context-6.2.0.jar:6.2.0]
	... 10 common frames omitted

2025-01-10T07:45:08.063Z  INFO 1860340 --- [taskProcessor-1] o.g.komga.application.tasks.TaskHandler  : Executing task: FixThumbnailsWithoutMetadata(priority='0')
2025-01-10T07:45:08.094Z  INFO 1860340 --- [taskProcessor-1] o.g.k.domain.service.ThumbnailLifecycle  : Fetched 0 ThumbnailBook to fix, total: 0
2025-01-10T07:45:08.101Z  INFO 1860340 --- [taskProcessor-1] o.g.k.domain.service.ThumbnailLifecycle  : Fixed 0 ThumbnailBook in 32.318398ms
2025-01-10T07:45:08.106Z  INFO 1860340 --- [taskProcessor-1] o.g.k.domain.service.ThumbnailLifecycle  : Fetched 0 ThumbnailSeries to fix, total: 0
2025-01-10T07:45:08.107Z  INFO 1860340 --- [taskProcessor-1] o.g.k.domain.service.ThumbnailLifecycle  : Fixed 0 ThumbnailSeries in 4.496227ms
2025-01-10T07:45:08.112Z  INFO 1860340 --- [taskProcessor-1] o.g.k.domain.service.ThumbnailLifecycle  : Fetched 0 ThumbnailSeriesCollection to fix, total: 0
2025-01-10T07:45:08.113Z  INFO 1860340 --- [taskProcessor-1] o.g.k.domain.service.ThumbnailLifecycle  : Fixed 0 ThumbnailSeriesCollection in 4.469365ms
2025-01-10T07:45:08.117Z  INFO 1860340 --- [taskProcessor-1] o.g.k.domain.service.ThumbnailLifecycle  : Fetched 0 ThumbnailReadList to fix, total: 0
2025-01-10T07:45:08.117Z  INFO 1860340 --- [taskProcessor-1] o.g.k.domain.service.ThumbnailLifecycle  : Fixed 0 ThumbnailReadList in 3.499275ms
2025-01-10T07:45:08.118Z  INFO 1860340 --- [taskProcessor-1] o.g.komga.application.tasks.TaskHandler  : Task FixThumbnailsWithoutMetadata(priority='0') executed in 53.984453ms
2025-01-10T07:45:37.473Z  INFO 1860340 --- [SpringApplicationShutdownHook] o.s.c.support.DefaultLifecycleProcessor  : Shutdown phase 1073741823 ends with 1 bean still running after timeout of 30000ms: [applicationTaskExecutor]
2025-01-10T07:45:39.527Z  INFO 1860340 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : SqliteTasksPool - Shutdown initiated...
2025-01-10T07:45:39.531Z  INFO 1860340 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : SqliteTasksPool - Shutdown completed.
2025-01-10T07:45:39.535Z  INFO 1860340 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : SqliteMainPool - Shutdown initiated...
2025-01-10T07:45:39.536Z  INFO 1860340 --- [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : SqliteMainPool - Shutdown completed.
```

**Comment by Snd-R** [comment]
The reason it doesn't work anymore is because jdk removed system tray support for systems below gnome 45 https://github.com/openjdk/jdk/pull/17860 
[UNIXToolkit.java#L236](https://github.com/openjdk/jdk/blob/10f7142dce296fedbb4d945378473d44ecde34b7/src/java.desktop/unix/classes/sun/awt/UNIXToolkit.java#L236) 
This was backported to all previous jdk major versions so downgrading jdk isn't a good option
From my tests Mint 22 this still has this issue and tray icon is displayed in top right of the desktop instead of proper place  in bottom right panel

Since Cinnamon (don't know if MATE is affected) is based on GNOME there are some environment variables that were used to detect it as GNOME
if `GNOME_DESKTOP_SESSION_ID` variable is set then the code path will treat it as GNOME desktop [UNIXToolkit.java#L113](https://github.com/openjdk/jdk/blob/10f7142dce296fedbb4d945378473d44ecde34b7/src/java.desktop/unix/classes/sun/awt/UNIXToolkit.java#L113) 
Then it'll try to execute gnome-shell command to detect version but will fail since there's no such executable on Cinnamon, and that is treated as unsupported version [UNIXToolkit.java#L261 ](https://github.com/openjdk/jdk/blob/10f7142dce296fedbb4d945378473d44ecde34b7/src/java.desktop/unix/classes/sun/awt/UNIXToolkit.java#L261) 
As a workaround you can unset `GNOME_DESKTOP_SESSION_ID` environment variable when you launch komga and this will bypass the detection
`env -u GNOME_DESKTOP_SESSION_ID komga`

**Comment by DRWAUN** [comment]
I updated my Komga yesterday and am unfortunately running into the same issue now.

**Comment by gotson** [comment]
Closing this as Linux desktop app support will be discontinued on the next release.
