### ISSUE TITLE
[Bug] Backtrace when trying to generate cover for CBZ containing WEBP

### ISSUE THREAD

**Issue by grim7reaper** [gotson/komga#205]
### Komga environment
- **OS**: Archlinux
- **Komga version**: 0.39.0.
- [x] **I am running Komga from the `jar`**
  - Java version: openjdk 14.0.1 2020-04-14

### Describe the bug

When trying to generate the cover for a book, it fails with a java.io.EOFException and the cover isn't generated.

### Steps to reproduce
1. Add a CBZ whose first file is a WEBP image
2. Cover isn't generated, you have a backtrace in the logs

### Expected behavior
Cover is correctly generated.

### Actual behavior
Backtrace in the log + no cover generated.

### Additional context
The book itself is a CBZ containing WEBP images.
I've managed to reproduce the bug with a CBZ containing only the first image, I can upload it somehwere if you need it to reproduce.
Other than that, the book is correctly imported and can be read in the WebReader.

### Log file

```
2020-06-12 16:16:13.027  INFO 208561 --- [enerContainer-1] o.g.komga.domain.service.BookAnalyzer    : Trying to generate cover for book: Book(name=BUG, url=file:/home/grim7reaper/Documents/Livres/Mangas/BUG.cbz, fileLastModified=2020-06-12T16:10:15.211883, fileSize=263996, number=1, id=881, seriesId=880, libraryId=2, createdDate=2020-06-12T16:15:01.841706, lastModifiedDate=2020-06-12T16:15:01.976764)
java.io.EOFException
        at java.desktop/javax.imageio.stream.ImageInputStreamImpl.readUnsignedByte(ImageInputStreamImpl.java:222)
        at net.sf.javavp8decoder.vp8Decoder.BoolDecoder.initBoolDecoder(BoolDecoder.java:40)
        at net.sf.javavp8decoder.vp8Decoder.BoolDecoder.<init>(BoolDecoder.java:32)
        at net.sf.javavp8decoder.vp8Decoder.VP8Frame.setupTokenDecoder(VP8Frame.java:1070)
        at net.sf.javavp8decoder.vp8Decoder.VP8Frame.decodeFrame(VP8Frame.java:268)
        at net.sf.javavp8decoder.imageio.WebPImageReader.readHeader(WebPImageReader.java:217)
        at net.sf.javavp8decoder.imageio.WebPImageReader.readMetadata(WebPImageReader.java:240)
        at net.sf.javavp8decoder.imageio.WebPImageReader.getImageMetadata(WebPImageReader.java:85)
        at net.coobird.thumbnailator.util.exif.ExifUtils.getExifOrientation(Unknown Source)
        at net.coobird.thumbnailator.tasks.io.InputStreamImageSource.read(Unknown Source)
        at net.coobird.thumbnailator.tasks.SourceSinkThumbnailTask.read(Unknown Source)
        at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source)
        at net.coobird.thumbnailator.Thumbnails$Builder.toOutputStream(Unknown Source)
        at org.gotson.komga.infrastructure.image.ImageConverter.resizeImage(ImageConverter.kt:54)
        at org.gotson.komga.domain.service.BookAnalyzer.generateThumbnail(BookAnalyzer.kt:103)
        at org.gotson.komga.domain.service.BookAnalyzer.analyze(BookAnalyzer.kt:72)
        at org.gotson.komga.domain.service.BookLifecycle.analyzeAndPersist(BookLifecycle.kt:34)
        at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:44)
```

**Comment by gotson** [comment]
The webp library used in Komga is limited and cannot process all kind of webp. The webreader is not an accurate comparison because it will serve webp directly without processing them because your browser can decode them.

Most likely your first image has webp transparency or webp lossless features, which are not supported by the library. 

The only solution for now if you want a cover is to replace the first image with something Komga can process properly.

**Comment by grim7reaper** [comment]
Indeed, it's a lossless WEBP.

Which library is used by Komga for WEBP ? I can open a bug report over there.

**Comment by gotson** [comment]
That's the thing, it's not maintained, there's not even a github.

Google only provides C libraries for webp and native executables, but that's painful to use with Komga which aims to be multi OS and multi platform, hence the use of this library that works well for 90% of the time.

There's an open source project doing various image support for Java where the project owner is relying on external contributions to add new features, that would be the best candidate IMHO. I've set up a donation page for Komga (sponsor button at the top) and I plan to give the extra money to that project so we can get proper webp support.
