### ISSUE TITLE
[Bug] library not loading

### ISSUE THREAD

**Issue by binyaminyblatt** [gotson/komga#215]
java.nio.file.NoSuchFileException: D:\YAC\James Bond 
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[na:1.8.0_251]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[na:1.8.0_251]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[na:1.8.0_251]
	at sun.nio.fs.WindowsFileSystemProvider.isHidden(Unknown Source) ~[na:1.8.0_251]
	at java.nio.file.Files.isHidden(Unknown Source) ~[na:1.8.0_251]
	at org.gotson.komga.domain.service.FileSystemScanner$scanRootFolder$5$1$2.invoke(FileSystemScanner.kt:41) ~[classes!/:na]
	at org.gotson.komga.domain.service.FileSystemScanner$scanRootFolder$5$1$2.invoke(FileSystemScanner.kt:22) ~[classes!/:na]
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:133) ~[kotlin-stdlib-1.3.72.jar!/:1.3.72-release-468 (1.3.72)]
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156) ~[kotlin-stdlib-1.3.72.jar!/:1.3.72-release-468 (1.3.72)]
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:131) ~[kotlin-stdlib-1.3.72.jar!/:1.3.72-release-468 (1.3.72)]
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156) ~[kotlin-stdlib-1.3.72.jar!/:1.3.72-release-468 (1.3.72)]
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:131) ~[kotlin-stdlib-1.3.72.jar!/:1.3.72-release-468 (1.3.72)]
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156) ~[kotlin-stdlib-1.3.72.jar!/:1.3.72-release-468 (1.3.72)]
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:176) ~[kotlin-stdlib-1.3.72.jar!/:1.3.72-release-468 (1.3.72)]
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:131) ~[kotlin-stdlib-1.3.72.jar!/:1.3.72-release-468 (1.3.72)]
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156) ~[kotlin-stdlib-1.3.72.jar!/:1.3.72-release-468 (1.3.72)]
	at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:419) ~[kotlin-stdlib-1.3.72.jar!/:1.3.72-release-468 (1.3.72)]
	at kotlin.collections.MapsKt__MapsKt.toMap(Maps.kt:587) ~[kotlin-stdlib-1.3.72.jar!/:1.3.72-release-468 (1.3.72)]
	at kotlin.collections.MapsKt__MapsKt.toMap(Maps.kt:581) ~[kotlin-stdlib-1.3.72.jar!/:1.3.72-release-468 (1.3.72)]
	at org.gotson.komga.domain.service.FileSystemScanner.scanRootFolder(FileSystemScanner.kt:77) ~[classes!/:na]
	at org.gotson.komga.domain.service.LibraryScanner.scanRootFolder(LibraryScanner.kt:28) ~[classes!/:na]
	at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:38) ~[classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_251]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) [spring-messaging-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) [spring-messaging-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114) [spring-jms-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77) [spring-jms-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) [spring-jms-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) [spring-jms-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) [spring-jms-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) [spring-jms-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) [spring-jms-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189) [spring-jms-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179) [spring-jms-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076) [spring-jms-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_251]

whndows 10
komga v0.40.1-master

**Comment by gotson** [comment]
Please use the issue templates
