### ISSUE TITLE
[Bug] Docker pull crapped out existing install

### ISSUE THREAD

**Issue by gerroon** [gotson/komga#240]
### Komga environment
- **OS**:  Debian

- **Komga version**:  I cant tant tell since I cant start the container

- [ ] **I am running Komga with Docker**

  - Docker image tag [e.g. latest, beta]:  image: gotson/komga (using docker-compose)

### Describe the bug
I just did `docker pull gotson/komga` and the container does not start anymore.

### Expected behavior
It should run as usual I guess.

### Actual behavior
It seems like there is an issue with database upgrade?

I have been uisng this with this kind of docker pull for a while.. This is the first time I am having this issue.

### Log file

```
cat docker-compose.yml 

---
version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /media/komga/config
        target: /config
      - type: bind
        source: /media/Books
        target: /books
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
    ports:
      - 2200:8080
    user: "1000:1000"
    environment:
      - KOMGA_LIBRARIES_SCAN_DIRECTORY_EXCLUSIONS=#recycle,@eaDir
      - JVM_OPTS=-Xmx1g -Xms1g
      - JAVA_TOOL_OPTIONS=-Xmx1600m
    restart: unless-stopped


```

```
ole principal classes: ""
komga    | 2020-07-18 00:03:17.941  INFO 1 --- [           main] o.g.k.i.image.ImageConverter             : Supported read formats: [JPEG 2000, JPG, tiff, bmp, PCX, bigtiff, gif, WBMP, PNG, RAW, JPEG, PNM, BigTI
FF, tif, TIFF, wbmp, jpeg, jbig2, jpeg-lossless, jpg, JPEG2000, BMP, pcx, GIF, png, raw, BIGTIFF, webp, JPEG-LOSSLESS, JBIG2, pnm, TIF, jpeg2000, jpeg 2000]
komga    | 2020-07-18 00:03:17.942  INFO 1 --- [           main] o.g.k.i.image.ImageConverter             : Supported read mediaTypes: [, image/vnd.wap.wbmp, image/png, image/x-jb2, image/jpeg, image/x-portable-
graymap, image/bmp, image/pcx, image/gif, image/x-windows-pcx, image/x-windows-bmp, image/jpeg2000, image/x-pc-paintbrush, image/webp, image/jp2, image/x-pcx, image/x-bmp, image/x-png, image/x-portable-bitmap, i
mage/x-portable-pixmap, image/tiff, image/x-tiff, image/x-jbig2, image/x-portable-anymap]
komga    | 2020-07-18 00:03:17.942  INFO 1 --- [           main] o.g.k.i.image.ImageConverter             : Supported write formats: [JPEG 2000, JPG, tiff, PCX, bmp, gif, WBMP, PNG, RAW, JPEG, PNM, tif, TIFF, jp
eg, wbmp, jpg, JPEG2000, pcx, BMP, GIF, png, raw, pnm, TIF, jpeg2000, jpeg 2000]
komga    | 2020-07-18 00:03:17.943  INFO 1 --- [           main] o.g.k.i.image.ImageConverter             : Supported write mediaTypes: [, image/png, image/vnd.wap.wbmp, image/jpeg, image/x-portable-graymap, ima
ge/pcx, image/bmp, image/gif, image/x-windows-pcx, image/x-windows-bmp, image/x-pc-paintbrush, image/jpeg2000, image/x-pcx, image/jp2, image/x-bmp, image/x-png, image/x-portable-bitmap, image/x-portable-pixmap, 
image/tiff, image/x-tiff, image/x-portable-anymap]
komga    | 2020-07-18 00:03:18.235  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Initiating database migration from H2 to SQLite
komga    | 2020-07-18 00:03:18.236  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : H2 url: jdbc:h2:/config/database.h2
komga    | 2020-07-18 00:03:18.251  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : H2 database file: /config/database.h2.mv.db
komga    | 2020-07-18 00:03:18.339  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Perform a specific backup of the H2 database to: /config/database.h2.mv.db.backup.2020-07-18.00-03-18.z
ip
komga    | 2020-07-18 00:03:18.341  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-2 - Starting...
komga    | 2020-07-18 00:03:20.650 ERROR 1 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-2 - Exception during pool initialization.
komga    | 
komga    | org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: Chunk 11039 not found [1.4.200/9]" [50000-200]
komga    |      at org.h2.message.DbException.getJdbcSQLException(DbException.java:505) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.message.DbException.get(DbException.java:194) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.message.DbException.convert(DbException.java:347) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.engine.Database.openDatabase(Database.java:333) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.engine.Database.<init>(Database.java:301) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.engine.Engine.openSession(Engine.java:74) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.engine.Engine.openSession(Engine.java:192) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.engine.Engine.createSession(Engine.java:166) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.engine.Engine.createSession(Engine.java:29) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.Driver.connect(Driver.java:69) ~[h2-1.4.200.jar:1.4.200]
komga    |      at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-3.4.2.jar:na]
komga    |      at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354) ~[HikariCP-3.4.2.jar:na]
komga    |      at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202) ~[HikariCP-3.4.2.jar:na]
komga    |      at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473) ~[HikariCP-3.4.2.jar:na]
komga    |      at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554) ~[HikariCP-3.4.2.jar:na]
komga    |      at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-3.4.2.jar:na] 
komga    |      at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-3.4.2.jar:na]
komga    |      at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158) ~[spring-jdbc-5.2.5.RELEASE.jar:5.2.5.RELEASE]
komga    |      at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116) ~[spring-jdbc-5.2.5.RELEASE.jar:5.2.5.RELEASE]
komga    |      at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79) ~[spring-jdbc-5.2.5.RELEASE.jar:5.2.

```

```
komga    |      at org.h2.mvstore.db.LobStorageMap.init(LobStorageMap.java:87) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.engine.Database.open(Database.java:791) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.engine.Database.openDatabase(Database.java:307) ~[h2-1.4.200.jar:1.4.200]
komga    |      ... 49 common frames omitted
komga    | 
komga    | 2020-07-18 00:03:20.654  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Deleting H2 migrated file if exists
komga    | 2020-07-18 00:03:20.663  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'databaseMigration': Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanInitializationException: Migration failed
komga    | 2020-07-18 00:03:20.987  INFO 1 --- [           main] org.apache.activemq.artemis.core.server  : AMQ221002: Apache ActiveMQ Artemis Message Broker version 2.10.1 [d70fd599-8f56-11ea-b77a-0242ac170002] stopped, uptime 2 minutes
komga    | 2020-07-18 00:03:20.989  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
komga    | 2020-07-18 00:03:20.993  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
komga    | 2020-07-18 00:03:21.126  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
komga    | 2020-07-18 00:03:21.135  INFO 1 --- [           main] io.hawt.web.auth.AuthenticationFilter    : Destroying hawtio authentication filter
komga    | 2020-07-18 00:03:21.136  INFO 1 --- [           main] io.hawt.HawtioContextListener            : Destroying hawtio services
komga    | 2020-07-18 00:03:21.253  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 
komga    | 
komga    | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
komga    | 2020-07-18 00:03:21.258 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
komga    | 
komga    | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'databaseMigration': Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanInitializationException: Migration failed
komga    |      at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
komga    |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
komga    |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
komga    |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
komga    |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
komga    |      at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
komga    |      at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
komga    |      at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
komga    |      at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
komga    |      at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
komga    |      at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
komga    |      at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
komga    |      at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
komga    |      at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
komga    |      at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
komga    |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
komga    |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
komga    |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
komga    |      at org.gotson.komga.ApplicationKt.main(Application.kt:15) ~[app/:na]
komga    | Caused by: org.springframework.beans.factory.BeanInitializationException: Migration failed
komga    |      at org.gotson.komga.infrastructure.datasource.DatabaseMigration.init(DatabaseMigration.kt:132) ~[app/:na]
komga    |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
komga    |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
komga    |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
komga    |      at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
komga    |      at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
komga    |      at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
komga    |      at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
komga    |      ... 18 common frames omitted
komga    | 
komga exited with code 1

```

**Comment by gotson** [comment]
Please provide a complete log file

**Comment by gerroon** [comment]
H
There is a backup zip but not dated. I recovered the database from that one and it is still giving similar  erorrs

```
omga    | 2020-07-18 14:23:56.932  INFO 1 --- [           main] o.g.k.i.image.ImageConverter             : Supported read mediaTypes: [, image/vnd.wap.wbmp, image/png, image/x-jb2, image/jpeg, image/x-[196/326]
graymap, image/bmp, image/pcx, image/x-windows-pcx, image/gif, image/x-windows-bmp, image/jpeg2000, image/x-pc-paintbrush, image/webp, image/jp2, image/x-pcx, image/x-bmp, image/x-png, image/x-portable-bitmap, i
mage/x-portable-pixmap, image/tiff, image/x-tiff, image/x-jbig2, image/x-portable-anymap]
komga    | 2020-07-18 14:23:56.932  INFO 1 --- [           main] o.g.k.i.image.ImageConverter             : Supported write formats: [JPEG 2000, JPG, tiff, PCX, bmp, gif, WBMP, PNG, RAW, JPEG, PNM, tif, TIFF, jp
eg, wbmp, jpg, JPEG2000, pcx, BMP, GIF, png, raw, pnm, TIF, jpeg2000, jpeg 2000]
komga    | 2020-07-18 14:23:56.933  INFO 1 --- [           main] o.g.k.i.image.ImageConverter             : Supported write mediaTypes: [, image/png, image/vnd.wap.wbmp, image/jpeg, image/x-portable-graymap, ima
ge/pcx, image/bmp, image/x-windows-pcx, image/x-windows-bmp, image/gif, image/x-pc-paintbrush, image/jpeg2000, image/x-pcx, image/jp2, image/x-bmp, image/x-png, image/x-portable-bitmap, image/x-portable-pixmap, 
image/tiff, image/x-tiff, image/x-portable-anymap]
komga    | 2020-07-18 14:23:57.155  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Initiating database migration from H2 to SQLite
komga    | 2020-07-18 14:23:57.155  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : H2 url: jdbc:h2:/config/database.h2
komga    | 2020-07-18 14:23:57.171  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : H2 database file: /config/database.h2.mv.db
komga    | 2020-07-18 14:23:57.221  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Perform a specific backup of the H2 database to: /config/database.h2.mv.db.backup.2020-07-18.14-23-57.z
ip
komga    | 2020-07-18 14:23:57.223  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-2 - Starting...
komga    | 2020-07-18 14:23:59.793 ERROR 1 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-2 - Exception during pool initialization.
komga    | 
komga    | org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: Chunk 11039 not found [1.4.200/9]" [50000-200]
komga    |      at org.h2.message.DbException.getJdbcSQLException(DbException.java:505) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.message.DbException.get(DbException.java:194) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.message.DbException.convert(DbException.java:347) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.engine.Database.openDatabase(Database.java:333) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.engine.Database.<init>(Database.java:301) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.engine.Engine.openSession(Engine.java:74) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.engine.Engine.openSession(Engine.java:192) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.engine.Engine.createSession(Engine.java:166) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.engine.Engine.createSession(Engine.java:29) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340) ~[h2-1.4.200.jar:1.4.200]
komga    |      at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173) ~[h2-1.4.200.jar:1.4.200]

```

**Comment by gerroon** [comment]
Ok here is more info. The upgrader fails right at the end. I recovered a backup from 2 weeks old and it is script borking the database. Please see the log


```
komga    | 2020-07-18 14:31:46.060  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Insert batch #2 (500 rows)                                                                             
komga    | 2020-07-18 14:31:46.061  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Insert batch #3 (500 rows)                                                                             
komga    | 2020-07-18 14:31:46.063  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Insert batch #4 (500 rows)                                                                             
komga    | 2020-07-18 14:31:46.064  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Insert batch #5 (284 rows)                                                                             
komga    | 2020-07-18 14:31:46.064  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Migrate table: BOOK_METADATA                                                                           
komga    | 2020-07-18 14:31:46.426  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Insert batch #1 (500 rows)                                                                             
komga    | 2020-07-18 14:31:46.432  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Insert batch #2 (500 rows)                                                                             
komga    | 2020-07-18 14:31:46.439  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Insert batch #3 (500 rows)                                                                             
komga    | 2020-07-18 14:31:46.446  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Insert batch #4 (500 rows)                                                                             
komga    | 2020-07-18 14:31:46.457  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Insert batch #5 (500 rows)                                                                             
komga    | 2020-07-18 14:31:46.465  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Insert batch #6 (500 rows)                                                                             
komga    | 2020-07-18 14:31:46.471  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Insert batch #7 (500 rows)                                                                             
komga    | 2020-07-18 14:31:46.479  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Insert batch #8 (500 rows)                                                                             
komga    | 2020-07-18 14:31:46.489  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Insert batch #9 (500 rows)                                                                             
komga    | 2020-07-18 14:31:46.494  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Insert batch #10 (224 rows)                                                                            
komga    | 2020-07-18 14:31:46.494  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Migrate table: BOOK_METADATA_AUTHOR                                                                    
komga    | 2020-07-18 14:31:46.515  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Insert batch #1 (500 rows)                                                                             
komga    | 2020-07-18 14:31:46.518  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Insert batch #2 (391 rows)                                                                             
komga    | 2020-07-18 14:31:46.518  INFO 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Migrate table: READ_PROGRESS                                                                           
komga    | 2020-07-18 14:31:47.214 ERROR 1 --- [           main] o.g.k.i.datasource.DatabaseMigration     : Migration failed                                                                                       
komga    |                                                                                                                                                                                                         
komga    | org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: READ_PROGRESS.BOOK_ID, READ_PROGRESS.USER_ID)                                    
komga    |      at org.sqlite.core.DB.newSQLException(DB.java:1010) ~[sqlite-jdbc-3.32.3.jar:na]                                                                                                                   
komga    |      at org.sqlite.core.DB.newSQLException(DB.java:1022) ~[sqlite-jdbc-3.32.3.jar:na]                                                                                                                   
komga    |      at org.sqlite.core.DB.throwex(DB.java:987) ~[sqlite-jdbc-3.32.3.jar:na]                                                                                                                            
komga    |      at org.sqlite.core.DB.executeBatch(DB.java:812) ~[sqlite-jdbc-3.32.3.jar:na]                                                                                                                       
komga    |      at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:72) ~[sqlite-jdbc-3.32.3.jar:na]              
komga    |      at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[HikariCP-3.4.2.jar:na]                        
komga    |      at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.2.jar:na]
komga    |      at org.gotson.komga.infrastructure.datasource.DatabaseMigration.transferH2DataToSqlite(DatabaseMigration.kt:205) ~[app/:na]
komga    |      at org.gotson.komga.infrastructure.datasource.DatabaseMigration.init(DatabaseMigration.kt:105) ~[app/:na]
komga    |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
komga    |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
komga    |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
komga    |      at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
komga    |      at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.2.5.RELEASE.jar:5.
2.5.RELEASE]
komga    |      at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.2.5.RE
LEASE.jar:5.2.5.RELEASE]
komga    |      at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.2.5.RELEAS
E.jar:5.2.5.RELEASE]
komga    |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416) ~[spring-beans-5.2.5.RELEA
SE.jar:5.2.5.RELEASE]
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

**Comment by gotson** [comment]
The first one indeed is a database corruption (`Chunk 11039 not found`).

The second one, it's probably an older bug that generated incorrect data for the read progress.

From there, you can do different things:
- if you don't care much about the data you have (users, metadata you may have changed, read progress), you can wipe the database and start fresh in `0.48.0` with the new SQLite database.
- if you care about your data, we will need to fix your old H2 database so it can be migrated. The problem is in the read progress, we can either use SQL to try and locate the problematic data and remove it, or remove all read progress (which is easier).

If your database is quite small in size, and if you are OK to trust me with the data, you could send me the database file, i could try fixing it and sending the SQLite equivalent database back.

Let me know what you want to do.

**Comment by gerroon** [comment]
Thanks for looking into it.

I would like to maybe try the second option myself here. Is it easy to do so? I will start over again if I have no other option. 
thanks

**Comment by gotson** [comment]
We can fix it, no problem.

Though i don't know exactly what's the problem in the database, do you have much read progress in Komga that you want to keep, or you don't care about it ?

I will try a command line tool that can perform SQL on the H2 database, and we can do some back and forth to try and fix it.

Are you on Discord by any chance? That would make the conversation and the fixing easier.

**Comment by gotson** [comment]
Good news, the H2 distribution comes with the web console with an easy to use script.

Go here and download the platform independent zip for version 1.4.200: http://www.h2database.com/html/download.html

You can unzip it, then in the bin folder there is a bat or sh file you can run, it will open the web console in a browser. 

From there just put the absolute path of your database after `jdbc:h2:` and connect.

You should see a web console with all the tables on the left. 

If you managed to get up to there we can start checking what's wrong in the data 😀

**Comment by gerroon** [comment]
Thanks for the info. I am in I guess. What do I do from here ?

**Comment by gotson** [comment]
Type the following query and click `Run`:

```sql
select b.id, b.name, u.id, u.email, count(p.book_id) as count
from read_progress p left join user u on p.user_id = u.id left join book b on p.book_id = b.id
group by b.id, b.name, u.id, u.email
having count(p.book_id) > 1;
```

That will list the pairs of (book, user) that have multiple read progress stored, which shouldn't happen. You will have an idea of how much data is incorrect.

Then you can run this query to remove the incorrect data:

```sql
delete from read_progress
where (book_id , user_id) in
(select b.id, u.id
from read_progress p left join user u on p.user_id = u.id left join book b on p.book_id = b.id
group by b.id, u.id
having count(p.book_id) > 1);
```

This will remove __all__ read progress for the pairs (book, user) listed in the first query, so you will lose some read progress, but not everything.

I couldn't manage to make a SQL query that would get rid of all but the last one, unfortunately. As the first query lists the books and users involved, you can always add it manually afterwards.

Once that is done, you can try to migrate again

**Comment by gerroon** [comment]
Hi

```
delete from read_progress
where (book_id , user_id) in
(select b.id, u.id
from read_progress p left join user u on p.user_id = u.id left join book b on p.book_id = b.id
group by b.id, u.id
having count(p.book_id) > 1);
Table "READ_PROGRESS" not found; SQL statement:
delete from read_progress
where (book_id , user_id) in
(select b.id, u.id
from read_progress p left join user u on p.user_id = u.id left join book b on p.book_id = b.id
group by b.id, u.id
having count(p.book_id) > 1) [42102-199] 42S02/42102 (Help)

```

**Comment by gotson** [comment]
can you run the following query: `show tables`

**Comment by gerroon** [comment]
Hi

Thanks for the help. I think that I wil go ahead and start from scratch, I will loose some stuff for sure but not worth the trouble of wasting time on this.
