### ISSUE TITLE
[Bug] Komga returns errors "1-based index not found: 58" and "COSDictionary expected, but got null" when scanning a specific PDF file

### ISSUE THREAD

**Issue by whalehub** [gotson/komga#278]
### Komga environment
- **OS**: Debian 10
- **Komga version**: 0.57.0
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [x] **I am running Komga from the `jar`**
  - Java version: 11.0.8
- [ ] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
Komga returns the error messages `1-based index not found: 58` and `COSDictionary expected, but got null` when scanning a library that contains the affected PDF file.

### Steps to reproduce
1. Download the PDF file from here: [Barry Reid - The Paper Trip II.pdf](https://github.com/gotson/komga/files/5102097/Barry.Reid.-.The.Paper.Trip.II.pdf)
2. Add the PDF file to a library.
3. Initiate a scan on the library.
4. See error messages in the Web UI and logs.

### Expected behavior
Komga successfully scans the PDF file, displays the number of pages and a thumbnail for it in the Web UI and allows users to read it.

### Actual behavior
Komga fails to scan the PDF file, displays "0 pages" and a blank thumbnail for it in the Web UI and greys out the read button.

### Additional context
The exact same PDF file worked in previous versions Komga. I set up Komga from scratch recently (a few weeks after SQLite became the default database type) and first observed the issue at that time. If necessary, I can try to narrow it down to a specific version of Komga where this PDF file stopped working.

### Screenshots

![error](https://xbb.datahoarder.dev/VUSu3/MAMeJIdo38.png/raw)

### Log file

**Book analysis error**

<details>
  <summary>Spoiler</summary>
<p></p>

```
2020-08-20 11:37:11.982  INFO 11770 --- [DefaultMessageListenerContainer-1] o.g.komga.application.tasks.TaskHandler  : Executing task: AnalyzeBook(bookId=02ASMYGD9SGJG)
2020-08-20 11:37:11.985  INFO 11770 --- [DefaultMessageListenerContainer-1] o.g.komga.domain.service.BookLifecycle   : Analyze and persist book: Book(name=Barry Reid - The Paper Trip II, url=file:/mnt/storage/media/literature/Books/Non-Fiction/Barry%20Reid%20-%20The%20Paper%20Trip%20II.pdf, fileLastModified=2019-11-16T04:57:26.133, fileSize=8186978, number=1, id=02ASMYGD9SGJG, seriesId=02ASMYGDDSRHE, libraryId=02ASMYFRHSHT7, createdDate=2020-08-20T11:37:11, lastModifiedDate=2020-08-20T11:37:11.873)
2020-08-20 11:37:11.987  INFO 11770 --- [DefaultMessageListenerContainer-1] o.g.komga.domain.service.BookAnalyzer    : Trying to analyze book: Book(name=Barry Reid - The Paper Trip II, url=file:/mnt/storage/media/literature/Books/Non-Fiction/Barry%20Reid%20-%20The%20Paper%20Trip%20II.pdf, fileLastModified=2019-11-16T04:57:26.133, fileSize=8186978, number=1, id=02ASMYGD9SGJG, seriesId=02ASMYGDDSRHE, libraryId=02ASMYFRHSHT7, createdDate=2020-08-20T11:37:11, lastModifiedDate=2020-08-20T11:37:11.873)
2020-08-20 11:37:12.035  INFO 11770 --- [DefaultMessageListenerContainer-1] o.g.komga.domain.service.BookAnalyzer    : Detected media type: application/pdf
2020-08-20 11:37:12.128  INFO 11770 --- [http-nio-7264-exec-1] o.g.komga.domain.service.BookLifecycle   : House keeping thumbnails for book: 02ASMYGD9SGJG
2020-08-20 11:37:13.151  WARN 11770 --- [DefaultMessageListenerContainer-1] org.apache.pdfbox.pdmodel.PDPageTree     : COSDictionary expected, but got null [note: this messages is printed over 2,000 times before returning the next lines]
2020-08-20 11:37:13.364 ERROR 11770 --- [DefaultMessageListenerContainer-1] o.g.komga.domain.service.BookAnalyzer    : Error while analyzing book: Book(name=Barry Reid - The Paper Trip II, url=file:/mnt/storage/media/literature/Books/Non-Fiction/Barry%20Reid%20-%20The%20Paper%20Trip%20II.pdf, fileLastModified=2019-11-16T04:57:26.133, fileSize=8186978, number=1, id=02ASMYGD9SGJG, seriesId=02ASMYGDDSRHE, libraryId=02ASMYFRHSHT7, createdDate=2020-08-20T11:37:11, lastModifiedDate=2020-08-20T11:37:11.873)

java.lang.IllegalStateException: 1-based index not found: 58
	at org.apache.pdfbox.pdmodel.PDPageTree.get(PDPageTree.java:303) ~[pdfbox-2.0.19.jar!/:2.0.19]
	at org.apache.pdfbox.pdmodel.PDPageTree.get(PDPageTree.java:232) ~[pdfbox-2.0.19.jar!/:2.0.19]
	at org.apache.pdfbox.pdmodel.PDDocument.getPage(PDDocument.java:1483) ~[pdfbox-2.0.19.jar!/:2.0.19]
	at org.gotson.komga.infrastructure.mediacontainer.PdfExtractor.getEntries(PdfExtractor.kt:33) ~[classes!/:na]
	at org.gotson.komga.domain.service.BookAnalyzer.analyze(BookAnalyzer.kt:42) ~[classes!/:na]
	at org.gotson.komga.domain.service.BookLifecycle.analyzeAndPersist(BookLifecycle.kt:42) ~[classes!/:na]
	at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:44) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) ~[spring-messaging-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) ~[spring-messaging-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```
</details>

**Thumbnail generation error**

<details>
  <summary>Spoiler</summary>
<p></p>

```
2020-08-20 11:37:13.655  INFO 11770 --- [DefaultMessageListenerContainer-1] o.g.komga.application.tasks.TaskHandler  : Executing task: GenerateBookThumbnail(bookId=02ASMYGD9SGJG)
2020-08-20 11:37:13.657  INFO 11770 --- [DefaultMessageListenerContainer-1] o.g.komga.domain.service.BookLifecycle   : Generate thumbnail and persist for book: Book(name=Barry Reid - The Paper Trip II, url=file:/mnt/storage/media/literature/Books/Non-Fiction/Barry%20Reid%20-%20The%20Paper%20Trip%20II.pdf, fileLastModified=2019-11-16T04:57:26.133, fileSize=8186978, number=1, id=02ASMYGD9SGJG, seriesId=02ASMYGDDSRHE, libraryId=02ASMYFRHSHT7, createdDate=2020-08-20T11:37:11, lastModifiedDate=2020-08-20T11:37:11.873)
2020-08-20 11:37:13.658  INFO 11770 --- [DefaultMessageListenerContainer-1] o.g.komga.domain.service.BookAnalyzer    : Generate thumbnail for book: Book(name=Barry Reid - The Paper Trip II, url=file:/mnt/storage/media/literature/Books/Non-Fiction/Barry%20Reid%20-%20The%20Paper%20Trip%20II.pdf, fileLastModified=2019-11-16T04:57:26.133, fileSize=8186978, number=1, id=02ASMYGD9SGJG, seriesId=02ASMYGDDSRHE, libraryId=02ASMYFRHSHT7, createdDate=2020-08-20T11:37:11, lastModifiedDate=2020-08-20T11:37:11.873)
2020-08-20 11:37:13.661  WARN 11770 --- [DefaultMessageListenerContainer-1] o.g.komga.domain.service.BookAnalyzer    : Book media is not ready, cannot generate thumbnail. Book: Book(name=Barry Reid - The Paper Trip II, url=file:/mnt/storage/media/literature/Books/Non-Fiction/Barry%20Reid%20-%20The%20Paper%20Trip%20II.pdf, fileLastModified=2019-11-16T04:57:26.133, fileSize=8186978, number=1, id=02ASMYGD9SGJG, seriesId=02ASMYGDDSRHE, libraryId=02ASMYFRHSHT7, createdDate=2020-08-20T11:37:11, lastModifiedDate=2020-08-20T11:37:11.873)
2020-08-20 11:37:13.662 ERROR 11770 --- [DefaultMessageListenerContainer-1] o.g.komga.domain.service.BookLifecycle   : Error while creating thumbnail

org.gotson.komga.domain.model.MediaNotReadyException: null
	at org.gotson.komga.domain.service.BookAnalyzer.generateThumbnail(BookAnalyzer.kt:85) ~[classes!/:na]
	at org.gotson.komga.domain.service.BookLifecycle.generateThumbnailAndPersist(BookLifecycle.kt:60) ~[classes!/:na]
	at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:51) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) ~[spring-messaging-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) ~[spring-messaging-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```
</details>

**Comment by whalehub** [comment]
I had a closer look at the affected PDF file and noticed that it has two issues even when opened in Acrobat DC:

- pages 57-92 are empty/broken
- page 55 is partially corrupted/missing "page information"

After removing those pages from the PDF, Komga is able to successfully scan it.

![error](https://xbb.datahoarder.dev/VUSu3/poMANiNi52.png/raw)
