### ISSUE TITLE
Rar 5

### ISSUE THREAD

**Issue by Joinatic** [gotson/komga#52]
Hi, whats the solution to get CBR Comics/Mangas of RAR Version 5 to work?

System: Raspbian
Error Log:

2020-01-03 11:47:13.876  INFO 27592 --- [analyzeBookTaskExecutor-1] o.g.komga.domain.service.BookLifecycle   : Analyze and persist book: /path/to/manga.cbr
2020-01-03 11:47:13.877  INFO 27592 --- [analyzeBookTaskExecutor-1] o.g.komga.domain.service.BookAnalyzer    : Trying to analyze book: /path/to/manga.cbr
2020-01-03 11:47:13.911  INFO 27592 --- [analyzeBookTaskExecutor-1] o.g.komga.domain.service.BookAnalyzer    : Detected media type: application/x-rar-compressed
2020-01-03 11:47:13.916  WARN 27592 --- [analyzeBookTaskExecutor-1] com.github.junrar.Archive                : Support for rar version 5 is not yet implemented!
2020-01-03 11:47:13.918  WARN 27592 --- [analyzeBookTaskExecutor-1] com.github.junrar.Archive                : exception in archive constructor maybe file is encrypted, corrupt or support not yet implemented

com.github.junrar.exception.RarException: unsupportedRarArchive
	at com.github.junrar.Archive.readHeaders(Archive.java:298) [junrar-4.0.0.jar!/:na]
	at com.github.junrar.Archive.setFile(Archive.java:169) [junrar-4.0.0.jar!/:na]
	at com.github.junrar.Archive.setVolume(Archive.java:648) [junrar-4.0.0.jar!/:na]
	at com.github.junrar.Archive.<init>(Archive.java:124) [junrar-4.0.0.jar!/:na]
	at com.github.junrar.Archive.<init>(Archive.java:160) [junrar-4.0.0.jar!/:na]
	at org.gotson.komga.infrastructure.archive.RarExtractor.getPagesList(RarExtractor.kt:15) [classes!/:na]
	at org.gotson.komga.domain.service.BookAnalyzer.analyze(BookAnalyzer.kt:48) [classes!/:na]
	at org.gotson.komga.domain.service.BookLifecycle.analyzeAndPersist(BookLifecycle.kt:35) [classes!/:na]
	at org.gotson.komga.domain.service.BookLifecycle$$FastClassBySpringCGLIB$$6608c007.invoke(<generated>) [classes!/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) [spring-aop-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) [spring-aop-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366) ~[spring-tx-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99) ~[spring-tx-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) [spring-aop-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_232]

2020-01-03 11:47:13.933 ERROR 27592 --- [analyzeBookTaskExecutor-1] o.g.komga.domain.service.BookLifecycle   : Error while parsing. Book: /path/to/manga.cbr

**Comment by Joinatic** [comment]
Installed UnRar 5.8.5 bit it still doesnt work
http://www.linuxfromscratch.org/blfs/view/svn/general/unrar.html

**Comment by gotson** [comment]
Hi,

Unfortunately there is no Java library that can extract rar 5 archives. 

See here : https://stackoverflow.com/questions/56700651/is-there-a-solution-to-read-the-rar-files-of-version-5-using-junrar-library

And the rar library I use in Komga : https://github.com/junrar/junrar/issues/23

One solution would be to use an external tool to perform the extract, but it would be platform specific, so difficult to maintain, while the current library is native Java and portable.

Rar 5 should be fairly uncommon, given the lack of support for the format in general. 

In case there is a native Java library implementing it, then I would add it of course.

**Comment by Neiko2002** [comment]
What about https://formats.kaitai.io/rar/index.html? It seems to me they can at least read rar v5. But have not tried it.

**Comment by gotson** [comment]
> What about https://formats.kaitai.io/rar/index.html? It seems to me they can at least read rar v5. But have not tried it.

I have seen this one indeed, but Kaitai is only describing how a file is built/formed, it doesn't have the algorithm to uncompress rar5 files.

**Comment by Neiko2002** [comment]
I see. When I upload a rar v5 to their IDE https://ide.kaitai.io/ it crashes when parsing the archive. Looks like its not stable now.
