### ISSUE TITLE
[Bug] analysis stops without progress

### ISSUE THREAD

**Issue by xtra-be** [gotson/komga#522]
### Komga environment
- **OS**: 
- **Komga version**: 
v0.90.0-master -  docker

### Describe the bug
I have a large collection I want to add to Komga
this is a directory with about 5000+ items
I have experienced quite a few that Komga stop the analysis 
even after restarting it keeps waiting indefinitely.
the log show no indications what's happening
even after trying increasing log level I see no indication that something is happening (docker image seems to ignore debug or trace env)
the only way I seem to be able to unstuck the queue is halting the container and removing the Artemis folder

### Steps to reproduce
1. Add new library 
2. this library is about 300 folders
3. around 5000 issues
4. start the scan
5. monitor the log file
6. after a while observe
2021-05-02 12:45:00.001  INFO 1 --- [scheduling-1] o.g.k.i.s.PeriodicScannerController      : Periodic libraries scan starting
2021-05-02 12:45:00.004  INFO 1 --- [scheduling-1] o.g.k.application.tasks.TaskReceiver     : Sending task: ScanLibrary(libraryId=04TP3W37F47AC)
2021-05-02 12:45:00.106  INFO 1 --- [scheduling-1] o.g.k.application.tasks.TaskReceiver     : Sending task: ScanLibrary(libraryId=04TP4ZRM34AKR)
2021-05-02 12:45:00.172  INFO 1 --- [scheduling-1] o.g.k.application.tasks.TaskReceiver     : Sending task: ScanLibrary(libraryId=04TYS46Z8YXZZ)
2021-05-02 12:45:00.206  INFO 1 --- [scheduling-1] o.g.k.application.tasks.TaskReceiver     : Sending task: ScanLibrary(libraryId=04V6K9SG8YJST)
2021-05-02 12:45:00.250  INFO 1 --- [scheduling-1] o.g.k.application.tasks.TaskReceiver     : Sending task: ScanLibrary(libraryId=04W0WAZEMPEWJ)
2021-05-02 12:45:00.317  INFO 1 --- [scheduling-1] o.g.k.application.tasks.TaskReceiver     : Sending task: ScanLibrary(libraryId=04W6MP1VC1QDX)
2021-05-02 12:45:00.372  INFO 1 --- [scheduling-1] o.g.k.application.tasks.TaskReceiver     : Sending task: ScanLibrary(libraryId=04W8GDH2M1KDF)
2021-05-02 12:45:00.428  INFO 1 --- [scheduling-1] o.g.k.application.tasks.TaskReceiver     : Sending task: ScanLibrary(libraryId=04WA2MMVDYG0M)
2021-05-02 12:45:00.482  INFO 1 --- [scheduling-1] o.g.k.application.tasks.TaskReceiver     : Sending task: ScanLibrary(libraryId=04WCGX3GBBWMV)
2021-05-02 12:45:00.537  INFO 1 --- [scheduling-1] o.g.k.application.tasks.TaskReceiver     : Sending task: ScanLibrary(libraryId=04WG5FXVKBKKE)
2021-05-02 12:45:00.584  INFO 1 --- [scheduling-1] o.g.k.application.tasks.TaskReceiver     : Sending task: ScanLibrary(libraryId=04WM7QM5NN7W1)
2021-05-02 12:45:00.628  INFO 1 --- [scheduling-1] o.g.k.application.tasks.TaskReceiver     : Sending task: ScanLibrary(libraryId=04WTERAPNVBHY)
nothing further happens

### Expected behavior
Komga scans and analyses the new library

### Actual behavior
After a while analysis stop and only way to get it going appear to be removal of the Artemis folder

### Additional context
I have experienced already several times. manual selecting soms series and doing them in batch seems to help but even then after a while it stops
### Log file
nothing really :-(
would like to increase debugging to try and find out what's happening but docker seems to be ignoring trace/debug

**Comment by xtra-be** [comment]
container env
LC_ALL=en_US.UTF-8                                                                                                                   
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;4
1:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31
:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=
01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01
;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;3
1:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=0
1;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=
01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v
=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=
01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;
36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;3
6:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:                                                                                 
SERVER_SERVLET_CONTEXT_PATH=/komga2                                                                                                  
LANG=en_US.UTF-8                                                                                                                     
HOSTNAME=gotson-komga1                                                                                                               
SPRING_DATASOURCE_URL=jdbc:h2:/config/database.h2                                                                                    
JAVA_HOME=/opt/java/openjdk                                                                                                          
KOMGA_DATABASE_FILE=/config/database.sqlite                                                                                          
JAVA_VERSION=jdk-11.0.8+10                                                                                                           
KOMGA_DATABASE_BACKUP_PATH=/config/database-backup.zip                                                                               
SPRING_ARTEMIS_EMBEDDED_DATA_DIRECTORY=/config/artemis                                                                               
PWD=/app                                                                                                                             
HOME=/root                                                                                                                           
TERM=xterm                                                                                                                           
SHLVL=1                                                                                                                              
LANGUAGE=en_US:en                                                                                                                    
LOGGING_LEVEL_ORG_GOTSON_KOMGA=TRACE                                                                                                 
LOGGING_FILE_NAME=/config/logs/komga.log                                                                                             
PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                                              
_=/usr/bin/env

**Comment by gotson** [comment]
Please provide a full log file.

**Comment by gotson** [comment]
Please also provide how you start the container, or your compose file.

**Comment by xtra-be** [comment]
I run the container from the Synology docker env
attached is the json config file
also attached is a log file

[gotson-komga1.txt](https://github.com/gotson/komga/files/6411466/gotson-komga1.txt)

[komga-3.log](https://github.com/gotson/komga/files/6411465/komga-3.log)

I thing the library is to big to handle and processing get's stuck

**Comment by gotson** [comment]
> I thing the library is to big to handle and processing get's stuck

Komga handles libraries as big as 50TB.

---

Thanks for the log file, from the looks of it there's an exception while trying to get the dimensions of one of the image in a RAR file. This should not block the queue, this behaviour has been tested in the past, and i tested again. The task queue is pretty resilient and should not stop dequeuing tasks.

While looking at the problem, I uncovered some incorrect code in the stream handling for the RAR extractor, that could lead to those SOF stream errors you can see in your logs. I managed to fix it, which will make the RAR extractor more robust and better than before. Hopefully this will also fix your problem.

A release is on the way, please try `0.90.1` when it is out.

**Comment by xtra-be** [comment]
installed 0.90.1

still the same

also the exception is still there

2021-05-03 08:18:04.012  WARN 1 --- [DefaultMessageListenerContainer-1] o.g.k.i.image.ImageAnalyzer              : Could not get image dimensions

javax.imageio.IIOException: No SOF segment in stream
        at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getSOF(JPEGImageReader.java:886) ~[imageio-jpeg-3.7.0.jar:3.7.0]
        at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getWidth(JPEGImageReader.java:184) ~[imageio-jpeg-3.7.0.jar:3.7.0]
        at org.gotson.komga.infrastructure.image.ImageAnalyzer.getDimension(ImageAnalyzer.kt:25) ~[classes/:na]
        at org.gotson.komga.infrastructure.mediacontainer.RarExtractor.getEntries(RarExtractor.kt:36) ~[classes/:na]
        at org.gotson.komga.domain.service.BookAnalyzer.analyze(BookAnalyzer.kt:42) ~[classes/:na]
        at org.gotson.komga.domain.service.BookLifecycle.analyzeAndPersist(BookLifecycle.kt:42) ~[classes/:na]
        at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:47) ~[classes/:na]
        at jdk.internal.reflect.GeneratedMethodAccessor263.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) ~[spring-messaging-5.3.4.jar:5.3.4]
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) ~[spring-messaging-5.3.4.jar:5.3.4]
        at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114) ~[spring-jms-5.3.4.jar:5.3.4]
        at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77) ~[spring-jms-5.3.4.jar:5.3.4]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) ~[spring-jms-5.3.4.jar:5.3.4]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) ~[spring-jms-5.3.4.jar:5.3.4]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[spring-jms-5.3.4.jar:5.3.4]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) ~[spring-jms-5.3.4.jar:5.3.4]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) ~[spring-jms-5.3.4.jar:5.3.4]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189) ~[spring-jms-5.3.4.jar:5.3.4]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179) ~[spring-jms-5.3.4.jar:5.3.4]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076) ~[spring-jms-5.3.4.jar:5.3.4]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

i did notice that the library i added yesterday eventualy did finish his analysis after the night

**Comment by gotson** [comment]
Would you be able to provide me with the file that has this error ? A Google or Dropbox link would be fine.

**Comment by gotson** [comment]
There's 2 things in your issue:
- one RAR file for which Komga can't get dimensions for some of the images. This should not be blocking and could happen with corrupt images. If I can get hold of the original file, I may find something more to fix it.
- the fact that the task queue seems not to be consumed, but the fact that you say the library eventually did finish contradicts that point. However the logs you provided yesterday were not showing any consumption of tasks, which seemed weird.

**Comment by xtra-be** [comment]
https://www.dropbox.com/s/0r9d0xt7au2mdmg/De%20Kanjers%20-%2001%20-%20Hihahondekul%21.cbr?dl=0

i will remove the link this evening

indeed seems to be 2 distinct problems
would you like to split it in 2 issues?

**Comment by gotson** [comment]
> i will remove the link this evening

I have the file, thanks

**Comment by gotson** [comment]
I have no problem with this file. Are you sure that's the one generating exceptions?

**Comment by xtra-be** [comment]
yes that's one of the files 
i also see this on the issue itself
COMMENT
Some entries could not be analyzed [img-101.jpg, img-103.jpg, img-107.jpg, img-108.jpg, img-111.jpg, img-112.jpg, img-115.jpg, img-116.jpg, img-117.jpg, img-135.jpg]

i'l look for some other ones

**Comment by gotson** [comment]
> yes that's one of the files
> i also see this on the issue itself
> COMMENT
> Some entries could not be analyzed [img-101.jpg, img-103.jpg, img-107.jpg, img-108.jpg, img-111.jpg, img-112.jpg, img-115.jpg, img-116.jpg, img-117.jpg, img-135.jpg]
> 
> i'l look for some other ones

This was fixed in the `0.90.1`, you can re-analyze the files and that should fix it.

**Comment by xtra-be** [comment]
i'm running v0.90.1-master

i recreated the complete container and it's showing me v0.90.1

here's a link to another archive that's was giving the errors (or at least i think it was)
https://www.dropbox.com/s/99bk08q6ejgklo8/archive.zip?dl=0

**Comment by gotson** [comment]
> here's a link to another archive that's was giving the errors (or at least i think it was)

that's 2.5GB ?!

**Comment by xtra-be** [comment]
well the total folder structure is much much bigger 
so it will be a good test :-)
updated to v0.90.3-master

for the scanning bit. i think i was just to impatient.
it seems analysis starts
runs for a while stops
and after a while it starts again
and so bit by bit it adds to the library.
i can see it that some issues get their thumbnail than an hour or so nothing
and then after a while new issues get done.

**Comment by gotson** [comment]
looks like there is something going on with Artemis on your system. Can you provide a bit of information on your underlying OS and system in general ?

You can also try to go to `/actuator/hawtio/jmx/attributes?nid=root-org.apache.activemq.artemis-localhost-addresses-tasks.background-queues-anycast-tasks.background` on your server. This is an admin console to monitor ActiveMQ Artemis. You should be able to see the `message count` and see if it is changing. That's the number of tasks in the queue.

**Comment by xtra-be** [comment]
Attribute | Value
-- | --
Acknowledge attempts | 10308
Address | tasks.background
Configuration managed | true
Consumer count | 1
Dead letter address | DLQ
Delivering count | 1
Delivering size | 524
Durable | true
Durable delivering count | 1
Durable delivering size | 524
Durable message count | 817
Durable persistent size | 437611
Durable scheduled count | 0
Durable scheduled size | 0
Enabled | true
Exclusive | false
Expiry address | ExpiryQueue
Filter |  
First message age | 11630042
First message as json | [{"durable":true,"unique_id":"ANALYZE_BOOK_04XEM9YP7R2RH","address":"tasks.background","__AMQ_CID":"f90d7f9b-aca3-11eb-b580-0242ac110002","_AMQ_ROUTING_TYPE":1,"messageID":5473,"expiration":0,"type":2,"priority":4,"userID":"ID:5de43f57-aca6-11eb-b580-0242ac110002","timestamp":1620111610472}]
First message timestamp | 1620111610472
Group buckets | -1
Group count | 0
Group first key |  
Group rebalance | false
Group rebalance pause dispatch | false
Id | 11
Last value | true
Max consumers | -1
Message count | 816
Messages acknowledged | 6027
Messages added | 6844
Messages expired | 0
Messages killed | 0
Name | tasks.background
Object Name | org.apache.activemq.artemis:broker="localhost",component=addresses,address="tasks.background",subcomponent=queues,routing-type="anycast",queue="tasks.background"
Paused | false
Persistent size | 437611
Produced rate | 0
Purge on no consumers | false
Retroactive resource | false
Ring size | -1
Routing type | ANYCAST
Scheduled count | 0
Scheduled size | 0
Temporary | false
User

os is synology ( rs 2414 )  dsm 6.2.3 on intel x86

**Comment by xtra-be** [comment]
i have been monitoring it now for close to an hour
and the message count stay's the same

**Comment by gotson** [comment]
From the counts above it seems some messages are received, which you confirmed by saying that some thumbnails have been generated. However it seems the tasks are not processed as fast as it should, or not all the time.

Can you set the following environment variable ? `LOGGING_LEVEL_ORG_APACHE_ACTIVEMQ=DEBUG`

This will generate very verbose logs, I don't need so much of them, maybe let it run for a few minutes. I am in uncharted waters here, but I should be able to compare your logs to ones of a working instance and see if I can find any hints.

**Comment by xtra-be** [comment]
after running debug

the last line that keep repeating are the following ones

2021-05-04 15:14:51.405 DEBUG 1 --- [Thread-4 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e159116)] o.a.a.a.c.s.impl.QueueMessageMetrics     : QueuePendingMessageMetrics[queue=tasks.background, name=pending] increment messageCount to 1794: org.apache.activemq.artemis.core.server.impl.LastValueQueue$HolderReference@14da45dc
2021-05-04 15:14:51.404  INFO 1 --- [http-nio-8080-exec-34] o.g.k.application.tasks.TaskReceiver     : Sending task: AnalyzeBook(bookId='04XEM9WFVR6WF', priority='6')
2021-05-04 15:14:51.406 DEBUG 1 --- [Thread-4 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e159116)] o.a.a.a.c.s.impl.ServerConsumerImpl      : ServerConsumerImpl [id=0, filter=FilterImpl [sfilterString=type = 'task'], binding=LocalQueueBinding [address=tasks.background, queue=QueueImpl[name=tasks.background, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=e3a800dc-acd2-11eb-868b-0242ac110002], temp=false]@1d1b3620, filter=null, name=tasks.background, clusterName=tasks.backgrounde3a800dc-acd2-11eb-868b-0242ac110002]] is busy for the lack of credits. Current credits = 0 Can't receive reference org.apache.activemq.artemis.core.server.impl.LastValueQueue$HolderReference@359bf85a
2021-05-04 15:14:51.406 DEBUG 1 --- [Thread-4 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e159116)] o.a.a.a.core.server.impl.QueueImpl       : QueueImpl[name=tasks.background, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=e3a800dc-acd2-11eb-868b-0242ac110002], temp=false]@1d1b3620::All the consumers were busy, giving up now
2021-05-04 15:14:51.437 DEBUG 1 --- [Thread-4 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e159116)] o.a.a.a.core.server.impl.QueueImpl       : QueueImpl[name=tasks.background, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=e3a800dc-acd2-11eb-868b-0242ac110002], temp=false]@1d1b3620 doing deliver. messageReferences=1794
2021-05-04 15:14:51.438  INFO 1 --- [http-nio-8080-exec-34] o.g.k.application.tasks.TaskReceiver     : Sending task: AnalyzeBook(bookId='04XEM9WFVR6WG', priority='6')
2021-05-04 15:14:51.438 DEBUG 1 --- [Thread-4 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e159116)] o.a.a.a.c.s.impl.QueueMessageMetrics     : QueuePendingMessageMetrics[queue=tasks.background, name=pending] increment messageCount to 1795: org.apache.activemq.artemis.core.server.impl.LastValueQueue$HolderReference@5db4bf44
2021-05-04 15:14:51.438 DEBUG 1 --- [Thread-4 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e159116)] o.a.a.a.c.s.impl.ServerConsumerImpl      : ServerConsumerImpl [id=0, filter=FilterImpl [sfilterString=type = 'task'], binding=LocalQueueBinding [address=tasks.background, queue=QueueImpl[name=tasks.background, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=e3a800dc-acd2-11eb-868b-0242ac110002], temp=false]@1d1b3620, filter=null, name=tasks.background, clusterName=tasks.backgrounde3a800dc-acd2-11eb-868b-0242ac110002]] is busy for the lack of credits. Current credits = 0 Can't receive reference org.apache.activemq.artemis.core.server.impl.LastValueQueue$HolderReference@359bf85a
2021-05-04 15:14:51.439 DEBUG 1 --- [Thread-4 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e159116)] o.a.a.a.core.server.impl.QueueImpl       : QueueImpl[name=tasks.background, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=e3a800dc-acd2-11eb-868b-0242ac110002], temp=false]@1d1b3620::All the consumers were busy, giving up now


if needed i can post the full log files

**Comment by xtra-be** [comment]
[komga.zip](https://github.com/gotson/komga/files/6422125/komga.zip)

**Comment by gotson** [comment]
Thanks, unfortunately i cannot find what's the problem :(

**Comment by xtra-be** [comment]
using hawtio i purged all messages
i then started analysis of a small series (26 issues)
i see that message count increases to 26
but messages acknowledged stay at 0 (i reset all counters also to 0)
so i have the impression that the queue get's populated correctly but that the consumer has issues
is there a way using hawtio to restart the consumer?

**Comment by gotson** [comment]
> is there a way using hawtio to restart the consumer?

I think you can `pause` and `resume` the queue.

**Comment by xtra-be** [comment]
seems to be working on v0.92.0-master

thnx for the help
