### ISSUE TITLE
[Bug] org.jooq.exception.DataAccessException on rebuilding Full Text Index

### ISSUE THREAD

**Issue by valdearg** [gotson/komga#608]
### Komga environment
- **OS**: Ubuntu 20.04
- **Komga version**: v0.116.0-master
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [x] **I am running Komga from the `jar`**
  - Java version: openjdk 11.0.11 2021-04-20
- [ ] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
When running the latest JAR file I noticed that the following error when rebuilding the full text search index:

```2021-08-10 22:23:20.597 ERROR 3962054 --- [ntContainer#2-1] o.g.komga.application.tasks.TaskHandler  : Task RebuildIndex(priority='8') execution failed

org.jooq.exception.DataAccessException: SQL [select distinct BOOK.ID from BOOK left outer join MEDIA on BOOK.ID = MEDIA.BOOK_ID left outer join BOOK_METADATA on BOOK.ID = BOOK_METADATA.BOOK_ID left outer join READ_PROGRESS on (BOOK.ID = READ_PROGRESS.BOOK_ID and (READ_PROGRESS.USER_ID = ? or READ_PROGRESS.USER_ID is null)) group by BOOK.ID]; SqliteUdfPool - Connection is not available, request timed out after 30001ms.
        at org.jooq_3.14.8.SQLITE.debug(Unknown Source) ~[na:na]
        at org.jooq.impl.Tools.translate(Tools.java:2903) ~[jooq-3.14.8.jar!/:na]
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:757) ~[jooq-3.14.8.jar!/:na]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:389) ~[jooq-3.14.8.jar!/:na]
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:333) ~[jooq-3.14.8.jar!/:na]
        at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2880) ~[jooq-3.14.8.jar!/:na]
        at org.gotson.komga.infrastructure.jooq.BookDtoDao.findAll(BookDtoDao.kt:110) ~[classes!/:na]
        at org.gotson.komga.infrastructure.jooq.BookDtoDao.findAll(BookDtoDao.kt:72) ~[classes!/:na]
        at org.gotson.komga.infrastructure.search.SearchIndexLifecycle$rebuildIndex$2$1.invoke(SearchIndexLifecycle.kt:44) ~[classes!/:na]
        at org.gotson.komga.infrastructure.search.SearchIndexLifecycle$rebuildIndex$2$1.invoke(SearchIndexLifecycle.kt:44) ~[classes!/:na]
        at org.gotson.komga.infrastructure.search.SearchIndexLifecycle.rebuildIndex(SearchIndexLifecycle.kt:55) ~[classes!/:na]
        at org.gotson.komga.infrastructure.search.SearchIndexLifecycle.rebuildIndex(SearchIndexLifecycle.kt:44) ~[classes!/:na]
        at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:122) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) ~[spring-messaging-5.3.8.jar!/:5.3.8]
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) ~[spring-messaging-5.3.8.jar!/:5.3.8]
        at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114) ~[spring-jms-5.3.8.jar!/:5.3.8]
        at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77) ~[spring-jms-5.3.8.jar!/:5.3.8]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) ~[spring-jms-5.3.8.jar!/:5.3.8]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) ~[spring-jms-5.3.8.jar!/:5.3.8]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[spring-jms-5.3.8.jar!/:5.3.8]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) ~[spring-jms-5.3.8.jar!/:5.3.8]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) ~[spring-jms-5.3.8.jar!/:5.3.8]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237) ~[spring-jms-5.3.8.jar!/:5.3.8]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1227) ~[spring-jms-5.3.8.jar!/:5.3.8]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1120) ~[spring-jms-5.3.8.jar!/:5.3.8]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: java.sql.SQLTransientConnectionException: SqliteUdfPool - Connection is not available, request timed out after 30001ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[HikariCP-4.0.3.jar!/:na]
        at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158) ~[spring-jdbc-5.3.8.jar!/:5.3.8]
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116) ~[spring-jdbc-5.3.8.jar!/:5.3.8]
        at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:223) ~[spring-jdbc-5.3.8.jar!/:5.3.8]
        at com.sun.proxy.$Proxy173.prepareStatement(Unknown Source) ~[na:na]
        at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:109) ~[jooq-3.14.8.jar!/:na]
        at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:73) ~[jooq-3.14.8.jar!/:na]
        at org.jooq.impl.AbstractResultQuery.prepare(AbstractResultQuery.java:258) ~[jooq-3.14.8.jar!/:na]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:342) ~[jooq-3.14.8.jar!/:na]
        ... 26 common frames omitted
```

Looks like I'm unable to search after this.

### Steps to reproduce
1. Run the latest JAR file.
2. Log states that the index is being recreated, expected.
3. After a moment the error shows.

### Expected behaviour
I'd expect the index to be rebuilt and searching through the website to be possible.

### Actual behaviour
Searching gives no results and the error occurs again in the log.

**Comment by gotson** [comment]
Please provide a complete log.

**Comment by valdearg** [comment]
Thanks for taking a look, I've uploaded the relevant parts from the log file to: https://gist.github.com/valdearg/45f29e46a1216c4cf48089bc1978f670

**Comment by gotson** [comment]
It seems the database connection cannot be established. Does the application works apart from that ? Can you browse, access books, mark books as read etc?

Can you check in `~/.komga/` if there is a `lucene` directory, and if yes if there's anything in there?

**Comment by gotson** [comment]
can you try to stop Komga, delete the `lucene` dir, and start again ?

Komga will try to rebuild the Lucene index on startup if it's not present, let's see if there is still the same database exception.

**Comment by valdearg** [comment]
Aha, that seems to have got it:

```
2021-08-12 15:11:13.760  INFO 261180 --- [ntContainer#2-1] o.g.komga.application.tasks.TaskHandler  : Executing task: RebuildIndex(priority='8')
2021-08-12 15:11:13.764  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Rebuild all indexes
2021-08-12 15:11:13.765  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Rebuilding index for Book
2021-08-12 15:11:31.844  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Number of entities: 57862
2021-08-12 15:11:31.938  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Processing page 0 of 5000 elements
2021-08-12 15:11:34.182  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Processing page 1 of 5000 elements
2021-08-12 15:11:35.709  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Processing page 2 of 5000 elements
2021-08-12 15:11:36.832  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Processing page 3 of 5000 elements
2021-08-12 15:11:38.308  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Processing page 4 of 5000 elements
2021-08-12 15:11:40.197  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Processing page 5 of 5000 elements
2021-08-12 15:11:41.534  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Processing page 6 of 5000 elements
2021-08-12 15:11:42.626  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Processing page 7 of 5000 elements
2021-08-12 15:11:43.877  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Processing page 8 of 5000 elements
2021-08-12 15:11:44.592  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Processing page 9 of 5000 elements
2021-08-12 15:11:46.148  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Processing page 10 of 5000 elements
2021-08-12 15:11:47.695  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Processing page 11 of 5000 elements
2021-08-12 15:11:48.261  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Wrote Book index in 16.3s
2021-08-12 15:11:48.830  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Rebuilding index for Series
2021-08-12 15:11:48.866  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Number of entities: 2360
2021-08-12 15:11:48.873  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Processing page 0 of 5000 elements
2021-08-12 15:11:50.448  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Wrote Series index in 1.58s
2021-08-12 15:11:50.734  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Rebuilding index for Collection
2021-08-12 15:11:50.831  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Number of entities: 0
2021-08-12 15:11:50.837  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Wrote Collection index in 44.5us
2021-08-12 15:11:50.842  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Rebuilding index for ReadList
2021-08-12 15:11:50.906  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Number of entities: 78
2021-08-12 15:11:50.909  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Processing page 0 of 5000 elements
2021-08-12 15:11:50.926  INFO 261180 --- [ntContainer#2-1] o.g.k.i.search.SearchIndexLifecycle      : Wrote ReadList index in 16.5ms
2021-08-12 15:11:51.108  INFO 261180 --- [ntContainer#2-1] o.g.komga.application.tasks.TaskHandler  : Task RebuildIndex(priority='8') executed in 37.3s```

I can search within the website again. Thanks for your assistance!
