### ISSUE TITLE
[Bug] Failed To Create Session Factory ARMv7l

### ISSUE THREAD

**Issue by heisarzola** [gotson/komga#629]
### Komga environment
- **OS**: Newest Raspberry OS (05-May-2021) for armv7l device
- **Komga version**: Latest (Just downloaded 21-Aug-2021)
- [X] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest

### Describe the bug
When executing the docker image after the initial setup (the first time it booted), it gives the endless logs described below the second time onward. Basically, only works the first time. The data and config folders are both within network drives that are mounted prior to launching the app.

### Steps to reproduce
1. Ensure the target config folder is empty to start from scratch.
2. Create container wtih `docker create` (not docker-compose) with the data and config folders pointing to pre-mounted network drives and `-e KOMGA_NATIVE_WEBP=false `, and start it.
3. Initialize komga by providing a first login e-mail and password.
4. Create a new library with a small collection to test, and wait for it scan and populate the database.
5. Stop or restart the komga docker container.

### Expected behavior
The komga server launches, and loads the previous session database entries.

### Actual behavior
The komga server pseudo launches (the index/login page is accessible), but attempting to login will always end in a 500 (server) error.

### Additional context
* The device is armv71 with 1GB of ram and 20+ unused gigs of drive space.
* The way I configured the server, involves accessing files from a network drive with administrator credentials (so all shared nas folders are exposed). So the bootup look goes: Mount Drives -> Start Docker Image, works the first time as described.
   * The nas drive is mounted by editing fstab, and using the flags `users` (to allow anyone to mount them) and `nolock` (to prevent a sqlite lock error common when accessing network drive databases).
* The komga docker container is made with docker create and the `KOMGA_NATIVE_WEBP` flag set to false for good measure.
* Feel free to ask for additional info on anything.

### Log file
The error log pretty much goes forever due to unlimited retries, but the looped gist of it shows the following messages:
```
javax.jms.JMSException: Failed to create session factory
	at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnectionInternal(ActiveMQConnectionFactory.java:886) ~[artemis-jms-client-2.17.0.jar:2.17.0]
	at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:299) ~[artemis-jms-client-2.17.0.jar:2.17.0]
	at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:294) ~[artemis-jms-client-2.17.0.jar:2.17.0]
	at org.springframework.jms.connection.SingleConnectionFactory.doCreateConnection(SingleConnectionFactory.java:410) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.connection.SingleConnectionFactory.initConnection(SingleConnectionFactory.java:350) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.connection.SingleConnectionFactory.getConnection(SingleConnectionFactory.java:328) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.connection.SingleConnectionFactory.createConnection(SingleConnectionFactory.java:243) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.support.JmsAccessor.createConnection(JmsAccessor.java:196) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.AbstractJmsListeningContainer.createSharedConnection(AbstractJmsListeningContainer.java:412) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.AbstractJmsListeningContainer.refreshSharedConnection(AbstractJmsListeningContainer.java:397) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.DefaultMessageListenerContainer.refreshConnectionUntilSuccessful(DefaultMessageListenerContainer.java:985) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.DefaultMessageListenerContainer.recoverAfterListenerSetupFailure(DefaultMessageListenerContainer.java:959) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1146) ~[spring-jms-5.3.8.jar:5.3.8]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: org.apache.activemq.artemis.api.core.ActiveMQNotConnectedException: AMQ219007: Cannot connect to server(s). Tried with all available servers.
	at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl.createSessionFactory(ServerLocatorImpl.java:703) ~[artemis-core-client-2.17.0.jar:2.17.0]
	at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnectionInternal(ActiveMQConnectionFactory.java:884) ~[artemis-jms-client-2.17.0.jar:2.17.0]
	... 13 common frames omitted
		
2021-08-22 06:13:08.999 ERROR 1 --- [ntContainer#0-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'sse' - retrying using FixedBackOff{interval=5000, currentAttempts=0, maxAttempts=unlimited}. Cause: Failed to create session factory; nested exception is ActiveMQNotConnectedException[errorType=NOT_CONNECTED message=AMQ219007: Cannot connect to server(s). Tried with all available servers.]
2021-08-22 06:13:09.003 ERROR 1 --- [ntContainer#1-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'tasks.background' - retrying using FixedBackOff{interval=5000, currentAttempts=0, maxAttempts=unlimited}. Cause: Failed to create session factory; nested exception is ActiveMQNotConnectedException[errorType=NOT_CONNECTED message=AMQ219007: Cannot connect to server(s). Tried with all available servers.]
2021-08-22 06:13:14.007  INFO 1 --- [ntContainer#2-1] o.s.j.c.CachingConnectionFactory         : Encountered a JMSException - resetting the underlying JMS Connection
```

**Comment by gotson** [comment]
Please provide complete log files. Also I think it's “armv7l`, not `armv71`, no?

**Comment by gotson** [comment]
Can you provide the complete docker command you execute the first time, and the one you use to stop or restart the container?

**Comment by heisarzola** [comment]
> Can you provide the complete docker command you execute the first time, and the one you use to stop or restart the container?

```
docker create --name=komga --user 1000:1000 -p 8080:8080 --mount type=bind,source=/home/pi/TheFlower/Services/Komga,target=/config --mount type=bind,source=/home/pi/TheFlower/Media,target=/data --restart on-failure -e KOMGA_NATIVE_WEBP=false gotson/komga
```

followed by `docker start komga` and either a full system reboot or `docker stop komga` to stop.

**Comment by heisarzola** [comment]
> Please provide complete log files. Also I think it's `armv7l`, not `armv71`, no?

An yes, you're right, I always forget that's an L and not a 1

[error.log](https://github.com/gotson/komga/files/7027469/error.log)

**Comment by heisarzola** [comment]
Sorry, yea, it was a problem with my mounted drives setup after all.

I'm going to explain how I fixed it in case someone later encounters this same issue, the core things to note is that the issue stemmed from me trying to have both the data and config folder reside within the mounted network drives.

The solution is, don't have the config file be inside a network drive. You're likely gonna have a headache setting up the permissions for it to work properly, and they might not be permanent depending on your NAS setup.

My recommendation and what I ended up doing, was to keep the config folder as a local folder. Then you can just setup `crontab` to copy this local folder to the mounted folder you originally intended it to go to on `@reboot` (or periodically if you prefer).

This way you don't have to deal with permissions for files on external devices, and still keep the config data backed up.
