### ISSUE TITLE
[Bug] scan fails with exception

### ISSUE THREAD

**Issue by Kussie** [gotson/komga#663]
### Komga environment
- **OS**:
- **Komga version**:
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest

### Describe the bug
New items in one of my libraries get stuck waiting to be analyzed.  Items added at the same time in other libraries work fine.  I can also manually analyse the library and the individual files fine. 

### Log file
```
2021-09-07 12:00:54.192 ERROR 1 --- [ntContainer#1-1] o.g.komga.application.tasks.TaskHandler  : Task ScanLibrary(libraryId=0201592VZ4E6K) execution failed


org.jooq.exception.TooManyRowsException: Cursor returned more than one result

	at org.jooq_3.14.8.SQLITE.debug(Unknown Source) ~[na:na]

	at org.jooq.impl.Tools.fetchOne(Tools.java:2285) ~[jooq-3.14.8.jar:na]

	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:641) ~[jooq-3.14.8.jar:na]

	at org.jooq.impl.AbstractResultQuery.fetchOneInto(AbstractResultQuery.java:670) ~[jooq-3.14.8.jar:na]

	at org.jooq.impl.SelectImpl.fetchOneInto(SelectImpl.java:3099) ~[jooq-3.14.8.jar:na]

	at org.gotson.komga.infrastructure.jooq.BookDao.findByLibraryIdAndUrlOrNull(BookDao.kt:45) ~[classes/:na]

	at org.gotson.komga.infrastructure.jooq.BookDao$$FastClassBySpringCGLIB$$b9fe9944.invoke(<generated>) ~[classes/:na]

	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.8.jar:5.3.8]

	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.3.8.jar:5.3.8]

	at org.gotson.komga.infrastructure.jooq.BookDao$$EnhancerBySpringCGLIB$$e211e712.findByLibraryIdAndUrlOrNull(<generated>) ~[classes/:na]

	at org.gotson.komga.domain.service.LibraryContentLifecycle.scanRootFolder(LibraryContentLifecycle.kt:197) ~[classes/:na]

	at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:49) ~[classes/:na]

	at jdk.internal.reflect.GeneratedMethodAccessor119.invoke(Unknown Source) ~[na:na]

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]

	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]

	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) ~[spring-messaging-5.3.8.jar:5.3.8]

	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) ~[spring-messaging-5.3.8.jar:5.3.8]

	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114) ~[spring-jms-5.3.8.jar:5.3.8]

	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77) ~[spring-jms-5.3.8.jar:5.3.8]

	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) ~[spring-jms-5.3.8.jar:5.3.8]

	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) ~[spring-jms-5.3.8.jar:5.3.8]

	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[spring-jms-5.3.8.jar:5.3.8]

	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) ~[spring-jms-5.3.8.jar:5.3.8]

	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) ~[spring-jms-5.3.8.jar:5.3.8]

	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237) ~[spring-jms-5.3.8.jar:5.3.8]

	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1227) ~[spring-jms-5.3.8.jar:5.3.8]

	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1120) ~[spring-jms-5.3.8.jar:5.3.8]

	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by Kussie** [comment]
May have found the cause of the issue potentially.  Does the task do any grouping based on file hash by chance?  As that is the only library i have that also has a bunch of files that don't have a file hash for some reason.

**Comment by gotson** [comment]
As seen together on Discord the issue is duplicate books by url. Not sure how that came to happen, but there's no constraint in the db about it.

The exception comes from the sql query trying to find a single record, but got more than one. A fix could be to get a collection and get the first but that seems like a bad fix.

Another fix could be to add the constraint on the url field in db, but I would need to ensure there's no regression anywhere. That's most likely the best way to prevent the problem to happen again. It could lead to exceptions on insert, but those would probably be easier to understand why it's happening and fix it.

**Comment by gotson** [comment]
Turns out there _can_ be multiple series or books with the same URL in DB, if one has been deleted for example and is marked unavailable.

The repo method that throws an exception should search for undeleted stuff, so that should fix it.
