### ISSUE TITLE
Can't find the correct Nginx Reverse Proxy configuration for Komga

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [gotson/komga#690]
### Komga environment
- **OS**: Dietpi v7.6.2
- **Komga version**: 0.128.1
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]:
- [ X ] **I am running Komga from the `jar`**
  - Java version: openjdk version "17" 2021-09-14    OpenJDK Runtime Environment (build 17+35-snap)
- [ X ] **I have a problem in the web interface**
  - Browser (with version): Firefox v92.0
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version):
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version:
  - Tachiyomi extension version:

### Describe the bug

Hi,

I'm currently using an Nginx Reverse Proxy for all my services (Jellyfin, Ombi, Radarr...) and I'm looking to add Komga to it.
I've already set a subpath to Komga, by adding this line in the application.yml of Komga :

`servlet.context-path: /komga/`

The subpath looks like it's working correctly, because when accessing it locally with [localip]:2037, it automatically becomes [localip]:2037/komga/. And everything works locally.

But now I'm trying to add the Nginx configuration as Komga.conf. 

```
location /komga/ {
  proxy_http_version 1.1;
  auth_request off;
  proxy_set_header  X-Real-IP $remote_addr;
  proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header  Upgrade $http_upgrade;
  proxy_set_header  Connection "Upgrade";
  proxy_pass        http://127.0.0.1:2037/komga/;
  chunked_transfer_encoding off;
  proxy_buffering off;
  proxy_cache off;
}

location /komga/api {
	auth_request off;
	proxy_pass http://127.0.0.1:2037/komga/api;
	}
 
location /komga/opds {
	auth_request off;
	proxy_pass http://127.0.0.1:2037/komga/opds;
	}

```

I tried changing `location /komga/` to `location /komga` and similar modifications, but the problem is still the same: I get a 400 HTTP error.

Here is my full Nginx config : https://pastebin.com/DxnCzQwg

I can't manage to get this to work. I tried multiple configurations, but I can't find the solution. When trying to access [mydomain]/komga with this config, I get a HTTP Status 400 – Bad Request error. I asked the Komga discord but it looks like there is very few people using Nginx with Komga. So I'm asking here.

Any help, any answer is welcome.
Have a great day !

### Expected behavior

I should be able to access Komga on my reverse proxy with https like every other applications on my pi

### Actual behavior

HTTP Status 400 – Bad Request

### Log file

Full logs:
_The docs says that the log should be in .komga, there is no log files at all in .komga._

Exerpt:
(got through systemctl status komga)
```
sept. 20 12:13:54 DietPi Komga[3427]:         at org.gotson.komga.ApplicationKt.main(Application.kt:16)
sept. 20 12:13:54 DietPi Komga[3427]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)
sept. 20 12:13:54 DietPi Komga[3427]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMe
thodAccessorImpl.java:77)
sept. 20 12:13:54 DietPi Komga[3427]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Dele
gatingMethodAccessorImpl.java:43)
sept. 20 12:13:54 DietPi Komga[3427]:         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
sept. 20 12:13:54 DietPi Komga[3427]:         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.j
ava:49)
sept. 20 12:13:54 DietPi Komga[3427]:         at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
sept. 20 12:13:54 DietPi Komga[3427]:         at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
sept. 20 12:13:54 DietPi Komga[3427]:         at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
sept. 20 12:13:55 DietPi Komga[3427]: 2021-09-20 12:13:55.011  WARN 3427 --- [           main] o.g.k.i.image.ImageConver
ter             : Could not load native WebP library
```

**Comment by Kussie** [comment]
You shouldn't need to change the config in Komga to add /komga should be able to be done via the reverse proxy itself.

Taken from SWAGs default reverse proxy config for subfolder based proxy, so you will need to remove the non applicable items (DO NOT COPY AND PASTE):

```
## Version 2021/06/06
# First make sure your Container has set an Baseurl set via docker-compose File "envirnoment: SERVER_SERVLET_CONTEXT_PATH=/komga" and recreate the container.

location /komga {
    return 301 $scheme://$host/komga/;
}

location ^~ /komga/ {
    set $upstream_app komga;
    set $upstream_port 8080 ;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

}

 location ^~ /komga/api {
     set $upstream_app komga;
     set $upstream_port 8080;
     set $upstream_proto http;
     proxy_pass $upstream_proto://$upstream_app:$upstream_port;
 }
```

**Comment by LeVraiRoiDHyrule** [comment]
> 
> 
> `servlet.context-path: /komga/` should be `servlet.context-path: /komga`
> 
> Taken from SWAGs default reverse proxy config for subfolder based proxy, so you will need to remove/add where needed (DO NOT COPY AND PASTE):
> 
> ```
> ## Version 2021/06/06
> # First make sure your Container has set an Baseurl set via docker-compose File "envirnoment: SERVER_SERVLET_CONTEXT_PATH=/komga" and recreate the container.
> 
> location /komga {
>     return 301 $scheme://$host/komga/;
> }
> 
> location ^~ /komga/ {
>     include /config/nginx/proxy.conf;  # This has all the proxy related headers, such as upgrade etc
>     set $upstream_app komga;
>     set $upstream_port 8080 ;
>     set $upstream_proto http;
>     proxy_pass $upstream_proto://$upstream_app:$upstream_port;
> 
> }
> 
>  location ^~ /komga/api {
>      include /config/nginx/proxy.conf;
>      set $upstream_app komga;
>      set $upstream_port 8080;
>      set $upstream_proto http;
>      proxy_pass $upstream_proto://$upstream_app:$upstream_port;
>  }
> ```

Thanks for your answer.
I'm sorry, but it looks like this config doesn't work. I am trying to adapt it step by step (to avoid trying everything at once). But as soon as I test this (to really keep it simple):

```
location /komga {
	return 301 https://[mydomaincensoredhere]/komga;
}

location ^~ /komga/ {
    #include /config/nginx/proxy.conf;  # This has all the proxy related headers, such as upgrade etc
    proxy_pass http://localhost:2037/komga/

}

 location ^~ /komga/api {
     #include /config/nginx/proxy.conf;
     proxy_pass http://localhost:2037/komga/
 }
```

Nginx crashes right away with this config. If it helps, here are examples of other config files on my server that works:

 ```
   location ~ ^/accounts(.*)$ {
        
        # Remove the CSP header set for Jellyfin
        proxy_hide_header Content-Security-Policy;
        add_header Content-Security-Policy "";
       
        # For versions <= v0.3.0
        proxy_pass http://localhost:8056; # Change as you need
        # For versions > v0.3.0
        # proxy_pass http://localhost:8056/accounts; # Change as you need
        http2_push_preload on; 

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        # Disable buffering when the nginx proxy gets very resource heavy upon streaming
        proxy_buffering off;
    }
```
```
   location /radarr {
           proxy_pass http://127.0.0.1:7878/radarr;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header X-Forwarded-Proto $scheme;
           proxy_http_version 1.1;
           proxy_no_cache $cookie_session;
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection $http_connection;
           # Allow the Radarr API
           location /radarr/api { auth_request off;
                   proxy_pass http://127.0.0.1:7878/radarr/api;
           }
           
   }
```
```
    location /ombi {
       proxy_pass http://localhost:5000;
    client_max_body_size 10m;
    client_body_buffer_size 128k;

    # Timeout if the real server is dead
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

    # Advanced Proxy Config
    send_timeout 5m;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
    proxy_connect_timeout 240;

    # Basic Proxy Config
    proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_redirect  http://  $scheme://;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 32 4k;
    proxy_redirect http://localhost:5000 https://$host;
    }

    # This allows access to the actual api
    location /ombi/api {
       proxy_pass http://localhost:5000;
    }
    # This allows access to the documentation for the api
    location /ombi/swagger {
        proxy_pass http://localhost:5000;
    }
```

I'm trying my best to adapt the Komga config so it looks like the working configs that I already have, but I'm stuck here.

**Comment by Kussie** [comment]
As per the sample config.

```
location /komga {
	return 301 https://[mydomaincensoredhere]/komga;
}

location ^~ /komga/ {
    #include /config/nginx/proxy.conf;  # This has all the proxy related headers, such as upgrade etc
    proxy_pass http://localhost:2037/komga/

}

 location ^~ /komga/api {
     #include /config/nginx/proxy.conf;
     proxy_pass http://localhost:2037/komga/
 }
```
The above is wrong you dont need to add /komga to the proxy pass directive.....  You are also missing a number of semi colons and have to add the proxy_set_headers directives.

It should be something like:
```
location /komga {
	return 301 https://[mydomaincensoredhere]/komga;
}

location ^~ /komga/ {
    proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_redirect  http://  $scheme://;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 32 4k;
    proxy_pass http://127.0.0.1:2037;

}

 location ^~ /komga/api {
     proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_redirect  http://  $scheme://;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 32 4k;
     proxy_pass http://127.0.0.1:2037;
 }
```

**Comment by LeVraiRoiDHyrule** [comment]
Thanks again for your answer.
The missing semicolons where because I copied it badly and I'm not used to github' text formating.
But yes, there was probably a lot of errors.

Thanks a lot for your config. It doesn't give any error when restarting nginx. 
Unfortunately, it still gaves me a 400 bad request error when trying to access komga on the reverse proxy.

I already considered using Nginx Proxy Manager, but I dropped using it for 3 reasons:
- All the softwares I was using until then where providing ready-to-use Nginx configs so that wasn't too hard for a newbie like me
- Most of these configs where requiring complex settings where it was much easier to just add a line in the config file than adding it through Nginx Proxy Manager, so most of the time file editing was still necessary (or faster)
- It requires Docker, which none of my other app requires, so that's a lot of stuff for just 1 config tool

**Comment by MichaIng** [comment]
It works well here with the most simple proxy config:
```sh
2021-09-27 20:01:21 root@VM-Bullseye:~# cat /etc/nginx/sites-enabled/default
#D I E T - P I
# /etc/nginx/sites-available/default

server {

        listen 80 default_server;
        listen [::]:80 default_server;

        location /komga {
                proxy_pass http://127.0.0.1:2037/komga;
        }

        root /var/www;
        index index.php index.html index.htm index.nginx-debian.html;

        server_name "$hostname";

        include /etc/nginx/sites-dietpi/*.conf;

        location / {
                try_files $uri $uri/ =404;
        }

        location ~ \.php(?:$|/) {
                include snippets/fastcgi-php.conf;
                fastcgi_pass php;
        }

}
2021-09-27 20:02:25 root@VM-Bullseye:~# cat /mnt/dietpi_userdata/komga/application.yml
komga:
  libraries-scan-startup: true # Scan libraries at startup
  libraries-scan-cron: "* 2 * * * *" # Scan libraries periodically every hour at :02
  file-hashing: false # Compute a filehash for your files. This is required for the trash bin functionality to work, but can consume lots of resources on large libraries or slow hardware
  database:
    file: /mnt/dietpi_userdata/komga/database.sqlite
  remember-me:
    key: 6a28750d5def336736d7b7194b5268e4cf6a2b50a049c415f7e64e12736438f2
logging:
  file:
    name: "" # Disable file logging, use: "journalctl -u komga"
  level:
    root: INFO # TRACE DEBUG INFO WARN ERROR
server:
  port: 2037
  servlet.context-path: /komga
```
But this does not involve HTTPS termination yet.

**Comment by MichaIng** [comment]
Works well here with HTTPS termination, including HTTP => HTTPS redirects as well:
```
2021-09-27 20:17:17 root@VM-Bullseye:~# cat /etc/nginx/sites-enabled/default
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        return 301 https://$host$request_uri;
}
2021-09-27 20:17:37 root@VM-Bullseye:~# cat /etc/nginx/sites-enabled/ssl
server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        root /var/www;
        index index.php index.html index.htm index.nginx-debian.html;
        location / {try_files $uri $uri/ =404;}

        location /komga {
                proxy_pass http://127.0.0.1:2037/komga;
        }

        ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
        ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
}
```
