### ISSUE TITLE
[Bug] Short description

### ISSUE THREAD

**Issue by JamesDAdams** [gotson/komga#705]
### Komga environment
- **OS**: Unraid
- **Komga version**: v0.132.0-master 
- [X] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: **gotson/komga:0.132.0**
- [ ] **I am running Komga from the `jar`**
  - Java version:
- [ ] **I have a problem in the web interface**
  - Browser (with version):
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version):
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version:
  - Tachiyomi extension version:

### Describe the bug
Error for reading a manga : Unknown error while analyzing book

### Steps to reproduce
1. Scan the librairi 

### Expected behavior
Be able to read my manga

### Actual behavior
the manga is not readable **error:** Unknown error while analyzing book

### Additional context
The file work with cbz reader

### Screenshots
![image](https://user-images.githubusercontent.com/20860324/136582452-83284d76-d303-4f16-b9e4-3b33bbd2349e.png)

![image](https://user-images.githubusercontent.com/20860324/136582504-c4f3e4d5-dbe9-4891-980d-6ef6cccc77bb.png)

### Error in LOG
2021-10-08 17:15:58.804 ERROR 1 --- [ntContainer#1-1] o.g.komga.domain.service.BookAnalyzer : Error while analyzing book: Book(name=Detective Conan T78, url=file:/books/Comics/Mangas/Detective%20Conan/Detective%20Conan%20T78.cbr, fileLastModified=2018-08-02T15:50, fileSize=84090546, fileHash=4mara2, number=78, id=02MZB8F50YMKR, seriesId=02MZB8F50YMM9, libraryId=02MZB8F30YMHQ, deletedDate=2021-10-03T16:45:01.554, createdDate=2020-09-21T02:32:58, lastModifiedDate=2021-10-08T17:15:31.670)

java.nio.file.NoSuchFileException: /books/Comics/Mangas/Detective Conan/Detective Conan T78.cbr
at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[na:na]
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[na:na]
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[na:na]
at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source) ~[na:na]
at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source) ~[na:na]
at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source) ~[na:na]
at java.base/java.nio.file.Files.readAttributes(Unknown Source) ~[na:na]
at java.base/java.nio.file.Files.size(Unknown Source) ~[na:na]
at org.apache.tika.io.TikaInputStream.get(TikaInputStream.java:234) ~[tika-core-1.26.jar:1.26]
at org.apache.tika.io.TikaInputStream.get(TikaInputStream.java:216) ~[tika-core-1.26.jar:1.26]
at org.gotson.komga.infrastructure.mediacontainer.ContentDetector.detectMediaType(ContentDetector.kt:24) ~[classes/:na]
at org.gotson.komga.domain.service.BookAnalyzer.analyze(BookAnalyzer.kt:36) ~[classes/:na]
at org.gotson.komga.domain.service.BookLifecycle.analyzeAndPersist(BookLifecycle.kt:50) ~[classes/:na]
at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:64) ~[classes/:na]
at jdk.internal.reflect.GeneratedMethodAccessor287.invoke(Unknown Source) ~[na:na]
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169) ~[spring-messaging-5.3.10.jar:5.3.10]
at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119) ~[spring-messaging-5.3.10.jar:5.3.10]
at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114) ~[spring-jms-5.3.10.jar:5.3.10]
at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77) ~[spring-jms-5.3.10.jar:5.3.10]
at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) ~[spring-jms-5.3.10.jar:5.3.10]
at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) ~[spring-jms-5.3.10.jar:5.3.10]
at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[spring-jms-5.3.10.jar:5.3.10]
at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) ~[spring-jms-5.3.10.jar:5.3.10]
at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) ~[spring-jms-5.3.10.jar:5.3.10]
at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237) ~[spring-jms-5.3.10.jar:5.3.10]
at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1227) ~[spring-jms-5.3.10.jar:5.3.10]
at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1120) ~[spring-jms-5.3.10.jar:5.3.10]
at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

**Comment by gotson** [comment]
The book is not there anymore : `java.nio.file.NoSuchFileException: /books/Comics/Mangas/Detective Conan/Detective Conan T78.cbr`
