### ISSUE TITLE
[Bug] Deletes of objects with file missing fails due to failure to delete file

### ISSUE THREAD

**Issue by dsm1212** [gotson/komga#782]
### Komga environment
- **OS**: debian buster
- **Komga version**: 0.145-master
I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest
- [ ] **I have a problem in the web interface**
  - Browser (with version): Chrome

### Describe the bug
I deleted a file which had been imported incorrectly. It was a cover only file rather than an issue. But I deleted in file system. When I rescan library I have an entry which says "Unavailable". When I try to delete the log shows a stack trace when the file is not found. The item doesn't delete from the database. I futzed around with recreating this file. Nothing quite worked an now I have 3 of these unavailables, none of which will delete. 

### Steps to reproduce
Have a series with just one issue. Go to filesystem, delete the issue file. Rescan library. Try to delete the series or the issue which says Unavailable. 

### Expected behavior
If the file is already gone then skip deleting it and proceed with the removal.

### Actual behavior
Errors on removing the file which is already not there.

### Additional context
When I put the file back it still doesn't delete correctly. It's like it tries to delete it twice actually. But maybe something is wrong in my metadata at this point.

### Log file
2022-01-27 12:05:34.778 ERROR 1 --- [org.springframework.jms.JmsListenerEndpointContainer#1-1] o.g.komga.application
.tasks.TaskHandler  : Task DeleteBook(bookId='07KVXTRC1P22Y', priority='8') execution failed

org.gotson.komga.domain.model.CodedException: java.io.FileNotFoundException: File is not accessible : /books/Saga (2
012)/Saga 01 (2012) (Image Firsts Variant Cover) (Chairmen-Novus-HD).cbz
        at org.gotson.komga.domain.model.ExceptionsKt.withCode(Exceptions.kt:15) ~[classes/:na]
        at org.gotson.komga.domain.service.BookLifecycle.deleteBookFiles(BookLifecycle.kt:331) ~[classes/:na]
        at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:135) ~[classes/:na]
        at jdk.internal.reflect.GeneratedMethodAccessor373.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.j
ava:169) ~[spring-messaging-5.3.14.jar:5.3.14]
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.jav
a:119) ~[spring-messaging-5.3.14.jar:5.3.14]
        at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageLi
stenerAdapter.java:114) ~[spring-jms-5.3.14.jar:5.3.14]
        at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListen
erAdapter.java:77) ~[spring-jms-5.3.14.jar:5.3.14]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListene
rContainer.java:736) ~[spring-jms-5.3.14.jar:5.3.14]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerC
ontainer.java:696) ~[spring-jms-5.3.14.jar:5.3.14]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[spring-jms-5.3.14.jar:5.3.14]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) ~[spring-jms-5.3.14.jar:5.3.14]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) ~[spring-jms-5.3.14.jar:5.3.14]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237) ~[spring-jms-5.3.14.jar:5.3.14]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1227) ~[spring-jms-5.3.14.jar:5.3.14]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1120) ~[spring-jms-5.3.14.jar:5.3.14]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.io.FileNotFoundException: File is not accessible : /books/Saga (2012)/Saga 01 (2012) (Image Firsts Variant Cover) (Chairmen-Novus-HD).cbz
        ... 18 common frames omitted

**Comment by gotson** [comment]
Please read the documentation https://komga.org/guides/trash.html
