### ISSUE TITLE
[Docs] Add additional development requirements

### ISSUE THREAD

**Issue by svew** [gotson/komga#799]
### Steps to reproduce

1. Clone repo on a brand new machine/VM
2. Install Java JDK 8+ and NodeJs 16+ per the development instructions
3. Run `npm install` on root, no issues
4. Run `npm install` on `/komga-webui`, see failure to install due to lack of Python & Visual Studio installation

### Expected behavior

Docs describe all required machine installs to successfully install npm packages

### Actual behavior

Errors that packages can't find Python & Visual Studio installs

### Logs

Error for Python:
```
6384 verbose node v17.4.0
6385 verbose npm  v8.3.1
6386 error code 1
6387 error path C:\Dev\komga\komga-webui\node_modules\deasync
6388 error command failed
6389 error command C:\Windows\system32\cmd.exe /d /s /c node ./build.js
6390 error gyp info it worked if it ends with ok
6390 error gyp info using node-gyp@8.4.1
6390 error gyp info using node@17.4.0 | win32 | x64
6390 error gyp ERR! find Python 
6390 error gyp ERR! find Python Python is not set from command line or npm configuration
6390 error gyp ERR! find Python Python is not set from environment variable PYTHON
6390 error gyp ERR! find Python checking if "python3" can be used
6390 error gyp ERR! find Python - "python3" is not in PATH or produced an error
6390 error gyp ERR! find Python checking if "python" can be used
6390 error gyp ERR! find Python - "python" is not in PATH or produced an error
6390 error gyp ERR! find Python checking if Python is C:\Users\wsven\AppData\Local\Programs\Python\Python39\python.exe
6390 error gyp ERR! find Python - "C:\Users\wsven\AppData\Local\Programs\Python\Python39\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Program Files\Python39\python.exe
6390 error gyp ERR! find Python - "C:\Program Files\Python39\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Users\wsven\AppData\Local\Programs\Python\Python39-32\python.exe
6390 error gyp ERR! find Python - "C:\Users\wsven\AppData\Local\Programs\Python\Python39-32\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Program Files\Python39-32\python.exe
6390 error gyp ERR! find Python - "C:\Program Files\Python39-32\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python39-32\python.exe
6390 error gyp ERR! find Python - "C:\Program Files (x86)\Python39-32\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Users\wsven\AppData\Local\Programs\Python\Python38\python.exe
6390 error gyp ERR! find Python - "C:\Users\wsven\AppData\Local\Programs\Python\Python38\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Program Files\Python38\python.exe
6390 error gyp ERR! find Python - "C:\Program Files\Python38\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Users\wsven\AppData\Local\Programs\Python\Python38-32\python.exe
6390 error gyp ERR! find Python - "C:\Users\wsven\AppData\Local\Programs\Python\Python38-32\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Program Files\Python38-32\python.exe
6390 error gyp ERR! find Python - "C:\Program Files\Python38-32\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python38-32\python.exe
6390 error gyp ERR! find Python - "C:\Program Files (x86)\Python38-32\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Users\wsven\AppData\Local\Programs\Python\Python37\python.exe
6390 error gyp ERR! find Python - "C:\Users\wsven\AppData\Local\Programs\Python\Python37\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Program Files\Python37\python.exe
6390 error gyp ERR! find Python - "C:\Program Files\Python37\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Users\wsven\AppData\Local\Programs\Python\Python37-32\python.exe
6390 error gyp ERR! find Python - "C:\Users\wsven\AppData\Local\Programs\Python\Python37-32\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Program Files\Python37-32\python.exe
6390 error gyp ERR! find Python - "C:\Program Files\Python37-32\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python37-32\python.exe
6390 error gyp ERR! find Python - "C:\Program Files (x86)\Python37-32\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Users\wsven\AppData\Local\Programs\Python\Python36\python.exe
6390 error gyp ERR! find Python - "C:\Users\wsven\AppData\Local\Programs\Python\Python36\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Program Files\Python36\python.exe
6390 error gyp ERR! find Python - "C:\Program Files\Python36\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Users\wsven\AppData\Local\Programs\Python\Python36-32\python.exe
6390 error gyp ERR! find Python - "C:\Users\wsven\AppData\Local\Programs\Python\Python36-32\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Program Files\Python36-32\python.exe
6390 error gyp ERR! find Python - "C:\Program Files\Python36-32\python.exe" could not be run
6390 error gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python36-32\python.exe
6390 error gyp ERR! find Python - "C:\Program Files (x86)\Python36-32\python.exe" could not be run
6390 error gyp ERR! find Python checking if the py launcher can be used to find Python 3
6390 error gyp ERR! find Python - "py.exe" is not in PATH or produced an error
6390 error gyp ERR! find Python 
6390 error gyp ERR! find Python **********************************************************
6390 error gyp ERR! find Python You need to install the latest version of Python.
6390 error gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
6390 error gyp ERR! find Python you can try one of the following options:
6390 error gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
6390 error gyp ERR! find Python   (accepted by both node-gyp and npm)
6390 error gyp ERR! find Python - Set the environment variable PYTHON
6390 error gyp ERR! find Python - Set the npm configuration variable python:
6390 error gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
6390 error gyp ERR! find Python For more information consult the documentation at:
6390 error gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
6390 error gyp ERR! find Python **********************************************************
6390 error gyp ERR! find Python 
6390 error gyp ERR! configure error 
6390 error gyp ERR! stack Error: Could not find any Python installation to use
6390 error gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:330:47)
6390 error gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:159:21)
6390 error gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:228:18)
6390 error gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:294:16)
6390 error gyp ERR! stack     at exithandler (node:child_process:406:5)
6390 error gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:418:5)
6390 error gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
6390 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
6390 error gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
6390 error gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
6390 error gyp ERR! System Windows_NT 10.0.19044
6390 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
6390 error gyp ERR! cwd C:\Dev\komga\komga-webui\node_modules\deasync
6390 error gyp ERR! node -v v17.4.0
6390 error gyp ERR! node-gyp -v v8.4.1
6390 error gyp ERR! not ok 
6390 error Build failed
6391 verbose exit 1
```

Error for Visual Studio, after installing Python:
```
3126 verbose cwd C:\Dev\komga\komga-webui
3127 verbose Windows_NT 10.0.19044
3128 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
3129 verbose node v17.4.0
3130 verbose npm  v8.3.1
3131 error code 1
3132 error path C:\Dev\komga\komga-webui\node_modules\deasync
3133 error command failed
3134 error command C:\Windows\system32\cmd.exe /d /s /c node ./build.js
3135 error gyp info it worked if it ends with ok
3135 error gyp info using node-gyp@8.4.1
3135 error gyp info using node@17.4.0 | win32 | x64
3135 error gyp info find Python using Python version 3.10.2 found at "C:\Users\wsven\AppData\Local\Programs\Python\Python310\python.exe"
3135 error gyp http GET https://nodejs.org/download/release/v17.4.0/node-v17.4.0-headers.tar.gz
3135 error gyp http 200 https://nodejs.org/download/release/v17.4.0/node-v17.4.0-headers.tar.gz
3135 error gyp http GET https://nodejs.org/download/release/v17.4.0/SHASUMS256.txt
3135 error gyp http GET https://nodejs.org/download/release/v17.4.0/win-x86/node.lib
3135 error gyp http GET https://nodejs.org/download/release/v17.4.0/win-x64/node.lib
3135 error gyp http GET https://nodejs.org/download/release/v17.4.0/win-arm64/node.lib
3135 error gyp http 200 https://nodejs.org/download/release/v17.4.0/SHASUMS256.txt
3135 error gyp http 404 https://nodejs.org/download/release/v17.4.0/win-arm64/node.lib
3135 error gyp http 200 https://nodejs.org/download/release/v17.4.0/win-x86/node.lib
3135 error gyp http 200 https://nodejs.org/download/release/v17.4.0/win-x64/node.lib
3135 error gyp ERR! find VS 
3135 error gyp ERR! find VS msvs_version not set from command line or npm config
3135 error gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
3135 error gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
3135 error gyp ERR! find VS looking for Visual Studio 2015
3135 error gyp ERR! find VS - not found
3135 error gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
3135 error gyp ERR! find VS 
3135 error gyp ERR! find VS **************************************************************
3135 error gyp ERR! find VS You need to install the latest version of Visual Studio
3135 error gyp ERR! find VS including the "Desktop development with C++" workload.
3135 error gyp ERR! find VS For more information consult the documentation at:
3135 error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
3135 error gyp ERR! find VS **************************************************************
3135 error gyp ERR! find VS 
3135 error gyp ERR! configure error 
3135 error gyp ERR! stack Error: Could not find any Visual Studio installation to use
3135 error gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
3135 error gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
3135 error gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
3135 error gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
3135 error gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
3135 error gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
3135 error gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
3135 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:406:5)
3135 error gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
3135 error gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
3135 error gyp ERR! System Windows_NT 10.0.19044
3135 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
3135 error gyp ERR! cwd C:\Dev\komga\komga-webui\node_modules\deasync
3135 error gyp ERR! node -v v17.4.0
3135 error gyp ERR! node-gyp -v v8.4.1
3135 error gyp ERR! not ok 
3135 error Build failed
3136 verbose exit 1
```

### Komga version

0.148.3

### Operating system

Windows 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
That's implementation details specific to Windows. If you are a developer you should be able to address such things, given the error messages are quite explicit.
