### ISSUE TITLE
Failure to delete Page

### ISSUE THREAD

**Issue by WorldEntityGravity** [gotson/komga#801]
### Steps to reproduce

Go to Server Settings -> Duplicate Pages and locate a file you want to delete.
Either click Manual delete or click on # Matches and delete a induvidual file, both generates the bug for me.

The log will indicate that the file is already in use, but this is false as only Komga accesses the file during that time.

### Expected behavior

A tmp-file should be created for the book, the page removed from the tmp-file and then the book is replaced by the tmp-file.

### Actual behavior

When deleting a single page from the "Matches" interface the tmp-file is created but is unable to replace the cbz-file (I think thats what is happening) leaving both the original cbz-file and the tmp-file in the folder.

When using the "Manual delete" button to delete all current instances of a page, not only does it fail to replace the cbz-file with the tmp-file, but it deletes the cbz-file too. So you are just left with the tmp-files.

### Logs

```
2022-02-08 17:54:02.496  INFO 4860 --- [http-nio-8443-exec-9] o.g.k.application.tasks.TaskReceiver     : Sending task: RemoveHashedPages(bookId='070WSFC97K8D3', priority='4')
2022-02-08 17:54:02.576  INFO 4860 --- [org.springframework.jms.JmsListenerEndpointContainer#1-1] o.g.komga.application.tasks.TaskHandler  : Executing task: RemoveHashedPages(bookId='070WSFC97K8D3', priority='4')
2022-02-08 17:54:02.607  INFO 4860 --- [org.springframework.jms.JmsListenerEndpointContainer#1-1] o.g.komga.domain.service.BookPageEditor  : Start removal of 1 pages for book: Book(name=74 - Vol. 4 Ch. 74 - Work74, url=file://Y.Y.Y.Y/Media/Comics/Servant%20X%20Service/74%20-%20Vol.%204%20Ch.%2074%20-%20Work74.cbz, fileLastModified=2021-12-16T22:06:52.303, fileSize=3694024, fileHash=10uq2j, number=77, id=070WSFC97K8D3, seriesId=05HVDVEHF73T8, libraryId=05GKQ5F1EW4J2, deletedDate=null, createdDate=2021-11-29T18:46:33, lastModifiedDate=2021-12-18T10:44:18.038)
2022-02-08 17:54:02.607  INFO 4860 --- [org.springframework.jms.JmsListenerEndpointContainer#1-1] o.g.komga.domain.service.BookPageEditor  : Creating new file: \\Y.Y.Y.Y\Media\Comics\Servant X Service\komga_page_removal_1608458074091136764.tmp
2022-02-08 17:54:03.236  INFO 4860 --- [org.springframework.jms.JmsListenerEndpointContainer#1-1] o.g.komga.domain.service.BookAnalyzer    : Trying to analyze book: Book(name=komga_page_removal_1608458074091136764, url=file://Y.Y.Y.Y/Media/Comics/Servant%20X%20Service/komga_page_removal_1608458074091136764.tmp, fileLastModified=2022-02-08T17:54:03.247891, fileSize=3753525, fileHash=, number=0, id=070WSFC97K8D3, seriesId=05HVDVEHF73T8, libraryId=05GKQ5F1EW4J2, deletedDate=null, createdDate=2022-02-08T17:54:03.236, lastModifiedDate=2022-02-08T17:54:03.236)
2022-02-08 17:54:03.283  INFO 4860 --- [org.springframework.jms.JmsListenerEndpointContainer#1-1] o.g.komga.domain.service.BookAnalyzer    : Detected media type: application/zip
2022-02-08 17:54:03.346  INFO 4860 --- [org.springframework.jms.JmsListenerEndpointContainer#1-1] o.g.komga.domain.service.BookAnalyzer    : Book has 12 pages
2022-02-08 17:54:03.361 ERROR 4860 --- [org.springframework.jms.JmsListenerEndpointContainer#1-1] o.g.komga.application.tasks.TaskHandler  : Task RemoveHashedPages(bookId='070WSFC97K8D3', priority='4') execution failed
java.nio.file.FileSystemException: \\Y.Y.Y.Y\Media\Comics\Servant X Service\komga_page_removal_1608458074091136764.tmp -> \\Y.Y.Y.Y\Media\Comics\Servant X Service\74 - Vol. 4 Ch. 74 - Work74.cbz: The process cannot access the file because it is being used by another process.
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[na:1.8.0_311]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[na:1.8.0_311]
	at sun.nio.fs.WindowsFileCopy.move(Unknown Source) ~[na:1.8.0_311]
	at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source) ~[na:1.8.0_311]
	at java.nio.file.Files.move(Unknown Source) ~[na:1.8.0_311]
	at org.gotson.komga.domain.service.BookPageEditor.removeHashedPages(BookPageEditor.kt:135) ~[classes!/:na]
	at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:126) ~[classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_311]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_311]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169) [spring-messaging-5.3.14.jar!/:5.3.14]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119) [spring-messaging-5.3.14.jar!/:5.3.14]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114) [spring-jms-5.3.14.jar!/:5.3.14]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77) [spring-jms-5.3.14.jar!/:5.3.14]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) [spring-jms-5.3.14.jar!/:5.3.14]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) [spring-jms-5.3.14.jar!/:5.3.14]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) [spring-jms-5.3.14.jar!/:5.3.14]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) [spring-jms-5.3.14.jar!/:5.3.14]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) [spring-jms-5.3.14.jar!/:5.3.14]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237) [spring-jms-5.3.14.jar!/:5.3.14]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1227) [spring-jms-5.3.14.jar!/:5.3.14]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1120) [spring-jms-5.3.14.jar!/:5.3.14]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_311]
```

### Komga version

0.149.2

### Operating system

Windows Server 2016 (10.14393.4886)

### Other details

Im running Komga on a Windows server 2016 VM using a service account that has a file server connected that hosts all my books. The account the service account uses to connect to the file server has full permisions to the file share (confirmed since Komga manages to delete some cbz-files).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> The log will indicate that the file is already in use, but this is false as only Komga accesses the file during that time.

Komga holds the zip file into a cache for quicker access.

Could you try 2 things :
1. After the card is shown with the thumbnail, wait 2 minutes, and try to delete matches
2. Completely out of Komga, try to open a zip (with 7zip or any other), and then while it's opened, try to overwrite the file with another file.

I'm thinking it's a windows specific bug, but I don't have access to a windows system to do further checks.

**Comment by WorldEntityGravity** [comment]
> 1. After the card is shown with the thumbnail, wait 2 minutes, and try to delete matches
> 2. Completely out of Komga, try to open a zip (with 7zip or any other), and then while it's opened, try to overwrite the file with another file.

1. I did open the Matches manu, waited for 15 min before clicking on the trashcan to delete one page and got the same error
2. Stopped the Komga service, made a backup of a file locally, opened the original file on the fileshare in 7Zip, tried to copy the backup file back and got a "file in use" error. Closed 7Zip, tried again and it worked.
