### ISSUE TITLE
Can't delete series

### ISSUE THREAD

**Issue by whyiseveryfuckingnameisalreadyused** [gotson/komga#807]
### Steps to reproduce

1. Open the webui
2. Select one of your libraries
3. Try to delete one of your series

### Expected behavior

It should delete the series and it's files.

### Actual behavior

It does nothing and throws errors about files not accessible in the terminal.

### Logs

```
2022-02-12 19:45:42.631  INFO 26552 --- [nio-8080-exec-7] o.g.k.application.tasks.TaskReceiver     : Sending task: DeleteSeries(seriesId='07QSEEHTMAE6B', priority='8')
2022-02-12 19:45:42.639  INFO 26552 --- [ntContainer#1-1] o.g.komga.application.tasks.TaskHandler  : Executing task: DeleteSeries(seriesId='07QSEEHTMAE6B', priority='8')
2022-02-12 19:45:42.640 ERROR 26552 --- [ntContainer#1-1] o.g.komga.application.tasks.TaskHandler  : Task DeleteSeries(seriesId='07QSEEHTMAE6B', priority='8') execution failed
org.gotson.komga.domain.model.CodedException: java.io.FileNotFoundException: File is not accessible : /mnt/btrfs/weeb/manga/Alice in Borderland (Fan-Scans)
        at org.gotson.komga.domain.model.ExceptionsKt.withCode(Exceptions.kt:15) ~[classes!/:na]
        at org.gotson.komga.domain.service.SeriesLifecycle.deleteSeriesFiles(SeriesLifecycle.kt:298) ~[classes!/:na]
        at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:142) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169) ~[spring-messaging-5.3.14.jar!/:5.3.14]
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119) ~[spring-messaging-5.3.14.jar!/:5.3.14]
        at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114) ~[spring-jms-5.3.14.jar!/:5.3.14]
        at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77) ~[spring-jms-5.3.14.jar!/:5.3.14]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) ~[spring-jms-5.3.14.jar!/:5.3.14]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) ~[spring-jms-5.3.14.jar!/:5.3.14]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[spring-jms-5.3.14.jar!/:5.3.14]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) ~[spring-jms-5.3.14.jar!/:5.3.14]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) ~[spring-jms-5.3.14.jar!/:5.3.14]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237) ~[spring-jms-5.3.14.jar!/:5.3.14]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1227) ~[spring-jms-5.3.14.jar!/:5.3.14]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1120) ~[spring-jms-5.3.14.jar!/:5.3.14]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.io.FileNotFoundException: File is not accessible : /mnt/btrfs/weeb/manga/Alice in Borderland (Fan-Scans)
        ... 19 common frames omitted
```

### Komga version

0.148.3-1

### Operating system

EndeavourOS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Can you please provide the full stack trace ? it's been truncated.

**Comment by whyiseveryfuckingnameisalreadyused** [comment]
Sure, do i need to enable it with some flag? This is all i could get with `journalctl -u komga.service --since "10 minutes ago"`.

**Comment by gotson** [comment]
You can get the actual [log files](https://komga.org/faq/#where-can-i-find-the-log-files) from Komga.

To get clean log files:
- stop Komga
- delete or rename the log file
- start Komga
- reproduce
- you should have clean logs from startup until the issue

**Comment by whyiseveryfuckingnameisalreadyused** [comment]
So i just discovered that this bug only happens when i run komga with systemd, if i just run it from the terminal it works fine. Where does komga keep the logs when i run it with systemd it doesn't seem to be in `~/.komga`.

**Comment by gotson** [comment]
> So i just discovered that this bug only happens when i run komga with systemd, if i just run it from the terminal it works fine. Where does komga keep the logs when i run it with systemd, it doesn't seem to be in `~/.komga`?

`~` is relative to the user running the application.

I guess now you know where the problem comes from: the user running Komga via systemd doesn't have write access to your files, and thus cannot delete the files.

**Comment by whyiseveryfuckingnameisalreadyused** [comment]
I edited `/lib/systemd/system/komga.service` to use my user, and i also added my user to the komga group, now it works fine.
