### ISSUE TITLE
mylar series.json throws an exception in komga

### ISSUE THREAD

**Issue by MKH-42** [gotson/komga#883]
### Steps to reproduce

Setup:
Download series.json from mylar site.
I used the example from https://github.com/mylar3/mylar3/wiki/series.json-examples
with this parameters for series.json:

```json
{
   "metadata":{
         "type":"comicSeries",
         "publisher":"DC Comics",
         "imprint":null,
         "name":"Aquaman",
         "comicid":43022,
         "year":2011,
         "description_text":"A \"New 52\" initiative title starring Aquaman and Mera as they strive to find a new life on the surface.",
         "description_formatted":null,
         "volume":5,
         "booktype":"Print",
         "collects":null,
         "ComicImage":"https://comicvine.gamespot.com/a/uploads/scale_large/6/67663/2083416-01.jpg",
         "total_issues":55,
         "publication_run":"November 2011 - July 2016",
         "status":"Ended"
      }
}
```

Result in komga.log:

```
2022-05-09 23:02:02.445 ERROR 1 --- [org.springframework.jms.JmsListenerEndpointContainer#1-1] o.g.k.i.m.mylar.MylarSeriesProvider      : Error while retrieving metadata from series.json

com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class org.gotson.komga.infrastructure.metadata.mylar.dto.MylarMetadata] value failed for JSON property cid due to missing (therefore NULL) value for creator parameter comicId which is a non-nullable type
 at [Source: (File); line: 18, column: 7] (through reference chain: org.gotson.komga.infrastructure.metadata.mylar.dto.Series["metadata"]->org.gotson.komga.infrastructure.metadata.mylar.dto.MylarMetadata["cid"])
	at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:116) ~[jackson-module-kotlin-2.12.6.jar:2.12.6]
```

Result in UI: 
The series.json data wasn't take over into komga.

It looks like that komga looks for a "cid" and mylar defined a comicid.

In schema definition from series.json also no cid but a comicid is defined:
https://github.com/mylar3/mylar3/wiki/series.json-schema-%28version-1.0.1%29

### Expected behavior

Komga don't use comicid or cid. in best case it doesn't look for this entry and ignore it.

Other case komga should use comicid 

### Actual behavior

At the moment komga ignore the complete series.json files.

### Logs

```
2022-05-09 23:02:02.445 ERROR 1 --- [org.springframework.jms.JmsListenerEndpointContainer#1-1] o.g.k.i.m.mylar.MylarSeriesProvider      : Error while retrieving metadata from series.json

com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class org.gotson.komga.infrastructure.metadata.mylar.dto.MylarMetadata] value failed for JSON property cid due to missing (therefore NULL) value for creator parameter comicId which is a non-nullable type
 at [Source: (File); line: 18, column: 7] (through reference chain: org.gotson.komga.infrastructure.metadata.mylar.dto.Series["metadata"]->org.gotson.komga.infrastructure.metadata.mylar.dto.MylarMetadata["cid"])
	at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:116) ~[jackson-module-kotlin-2.12.6.jar:2.12.6]
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202) ~[jackson-databind-2.12.6.1.jar:2.12.6.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:520) ~[jackson-databind-2.12.6.1.jar:2.12.6.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405) ~[jackson-databind-2.12.6.1.jar:2.12.6.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362) ~[jackson-databind-2.12.6.1.jar:2.12.6.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195) ~[jackson-databind-2.12.6.1.jar:2.12.6.1]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542) ~[jackson-databind-2.12.6.1.jar:2.12.6.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:565) ~[jackson-databind-2.12.6.1.jar:2.12.6.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449) ~[jackson-databind-2.12.6.1.jar:2.12.6.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405) ~[jackson-databind-2.12.6.1.jar:2.12.6.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362) ~[jackson-databind-2.12.6.1.jar:2.12.6.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195) ~[jackson-databind-2.12.6.1.jar:2.12.6.1]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[jackson-databind-2.12.6.1.jar:2.12.6.1]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593) ~[jackson-databind-2.12.6.1.jar:2.12.6.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3413) ~[jackson-databind-2.12.6.1.jar:2.12.6.1]
	at org.gotson.komga.infrastructure.metadata.mylar.MylarSeriesProvider.getSeriesMetadata(MylarSeriesProvider.kt:32) ~[classes/:na]
	at org.gotson.komga.domain.service.SeriesMetadataLifecycle.refreshMetadata(SeriesMetadataLifecycle.kt:79) ~[classes/:na]
	at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:116) ~[classes/:na]
	at jdk.internal.reflect.GeneratedMethodAccessor306.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169) ~[spring-messaging-5.3.18.jar:5.3.18]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119) ~[spring-messaging-5.3.18.jar:5.3.18]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114) ~[spring-jms-5.3.18.jar:5.3.18]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77) ~[spring-jms-5.3.18.jar:5.3.18]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) ~[spring-jms-5.3.18.jar:5.3.18]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) ~[spring-jms-5.3.18.jar:5.3.18]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[spring-jms-5.3.18.jar:5.3.18]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:331) ~[spring-jms-5.3.18.jar:5.3.18]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:270) ~[spring-jms-5.3.18.jar:5.3.18]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237) ~[spring-jms-5.3.18.jar:5.3.18]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1227) ~[spring-jms-5.3.18.jar:5.3.18]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1120) ~[spring-jms-5.3.18.jar:5.3.18]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

### Komga version

0.154.0-master

### Operating system

windows 10

### Other details

Not sure this is a mylar issue (documentation could be wrong) or a komga issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I think the Mylar wiki is incorrect, during the schema change from 1.0.0 to 1.0.1 there was a change from `comicid` to `cid`, as can be seen in this [commit](https://github.com/gotson/komga/commit/0c089d73c18411284527d5b8fe91a50969e281f1).

**Comment by evilhero** [comment]
As far as the series.json - it has and will always be referenced as ``comicid` not ``cid``.  The ``cid`` thing seems to be a Komga-only field, which obviously still implies comicid, but I have no idea / involvement as to that naming aspect. 

The series.json schema for 1.0.1 for that field remains the same as it was in 1.0 - the only difference is that it changed the accepted value for comicid from text to integer.

**Comment by gotson** [comment]
Not exactly correct after our discussion on Discord. Mylar currently generate files with `cid` field instead of `comicid`.

Komga currently aligns on the file produced, not the schema, and schema and produced files are not aligned.

@MKH-42 for now using `cid` in your hand crafted files will suffice.

**Comment by MKH-42** [comment]
THX - I will create a cid and comicid in my series.json file to be ready for the future.

Thank you for clarification!

**Comment by barrelltitor** [comment]
It seems that "cid" was never actually a field, it was just a mistake, this was fixed 12 days ago https://github.com/mylar3/mylar3/commit/3edfaa17b735f3a954cafda8354dffed266c924d

Could you fix this in Komga as well @gotson ?
