### ISSUE TITLE
Unable to run without root access?

### ISSUE THREAD

**Issue by fbordwell** [gotson/komga#948]
### Steps to reproduce

I am attempting to run komga with the jar file using the command `java -jar komga.jar --logging.level.org.gotson.komga=DEBUG`. 

### Expected behavior

I expect it to be able to run without root access.

### Actual behavior

The program exits with an error as shown in the logs. This is my first time attempting to run this program. I suspect the issue is that I do not have root access on this user, but it's not clear to me how to work around this.

### Logs

```
 ____  __.
|    |/ _|____   _____    _________
|      < /  _ \ /     \  / ___\__  \
|    |  (  <_> )  Y Y  \/ /_/  > __ \_
|____|__ \____/|__|_|  /\___  (____  /
        \/           \//_____/     \/

Version: 0.157.0

2022-08-15 20:00:02.789  INFO 138406 --- [           main] org.gotson.komga.ApplicationKt           : Starting ApplicationKt using Java 18.0.2 on cupid.whatbox.ca with PID 138406 (/mnt/mpathh/nattymitch/komga/komga.jar started by nattymitch in /mnt/mpathh/nattymitch/komga)
2022-08-15 20:00:02.792 DEBUG 138406 --- [           main] org.gotson.komga.ApplicationKt           : Running with Spring Boot v2.7.1, Spring v5.3.21
2022-08-15 20:00:02.792  INFO 138406 --- [           main] org.gotson.komga.ApplicationKt           : No active profile set, falling back to 1 default profile: "default"
2022-08-15 20:00:05.267  INFO 138406 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2022-08-15 20:00:05.277  INFO 138406 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-08-15 20:00:05.277  INFO 138406 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.64]
2022-08-15 20:00:05.345  INFO 138406 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-08-15 20:00:05.345  INFO 138406 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2490 ms
2022-08-15 20:00:05.650  INFO 138406 --- [           main] com.zaxxer.hikari.HikariDataSource       : SqliteUdfPool - Starting...
2022-08-15 20:00:05.728 DEBUG 138406 --- [           main] o.g.k.i.datasource.SqliteUdfDataSource   : Adding custom REGEXP function
2022-08-15 20:00:05.728 DEBUG 138406 --- [           main] o.g.k.i.datasource.SqliteUdfDataSource   : Adding custom UDF_STRIP_ACCENTS function
2022-08-15 20:00:05.729 DEBUG 138406 --- [           main] o.g.k.i.datasource.SqliteUdfDataSource   : Adding custom COLLATION_UNICODE_3 collation
2022-08-15 20:00:05.807 DEBUG 138406 --- [           main] o.g.k.i.datasource.SqliteUdfDataSource   : Adding custom REGEXP function
2022-08-15 20:00:05.807 DEBUG 138406 --- [           main] o.g.k.i.datasource.SqliteUdfDataSource   : Adding custom UDF_STRIP_ACCENTS function
2022-08-15 20:00:05.807 DEBUG 138406 --- [           main] o.g.k.i.datasource.SqliteUdfDataSource   : Adding custom COLLATION_UNICODE_3 collation
2022-08-15 20:00:05.810  INFO 138406 --- [           main] com.zaxxer.hikari.HikariDataSource       : SqliteUdfPool - Start completed.
2022-08-15 20:00:06.100  INFO 138406 --- [           main] o.s.b.a.e.web.ServletEndpointRegistrar   : Registered '/actuator/jolokia' to jolokia-actuator-endpoint
2022-08-15 20:00:06.114  INFO 138406 --- [           main] io.hawt.HawtioContextListener            : Initialising hawtio services
2022-08-15 20:00:06.146  INFO 138406 --- [           main] io.hawt.system.ConfigManager             : Configuration will be discovered via system properties
2022-08-15 20:00:06.147  INFO 138406 --- [           main] io.hawt.jmx.JmxTreeWatcher               : Welcome to Hawtio 2.15.0
2022-08-15 20:00:06.149  INFO 138406 --- [           main] io.hawt.log.logback.LogbackLogQuery      : Connected to Logback appender to trap logs with Hawtio log plugin
2022-08-15 20:00:06.156  INFO 138406 --- [           main] i.h.w.auth.AuthenticationConfiguration   : Starting hawtio authentication filter, JAAS realm: "karaf" authorized role(s): "admin,manager,viewer" role principal classes: ""
2022-08-15 20:00:06.157 DEBUG 138406 --- [           main] rConfiguration$shallowEtagHeaderFilter$1 : Filter 'etagFilter' configured for use
2022-08-15 20:00:06.158  INFO 138406 --- [           main] io.hawt.web.auth.LoginRedirectFilter     : Hawtio loginRedirectFilter is using 1800 sec. HttpSession timeout
2022-08-15 20:00:06.303  INFO 138406 --- [           main] org.apache.activemq.artemis.core.server  : AMQ221000: live Message Broker is starting with configuration Broker Configuration (clustered=false,journalDirectory=/home/nattymitch/.komga/artemis/journal,bindingsDirectory=/home/nattymitch/.komga/artemis/bindings,largeMessagesDirectory=/home/nattymitch/.komga/artemis/largemessages,pagingDirectory=/home/nattymitch/.komga/artemis/paging)
2022-08-15 20:00:06.334  INFO 138406 --- [           main] org.apache.activemq.artemis.core.server  : AMQ221013: Using NIO Journal
2022-08-15 20:00:06.421  INFO 138406 --- [           main] org.apache.activemq.artemis.core.server  : AMQ221057: Global Max Size is being adjusted to 1/2 of the JVM max size (-Xmx). being defined as 15,837,691,904
2022-08-15 20:00:06.439  INFO 138406 --- [           main] org.apache.activemq.artemis.core.server  : AMQ221043: Protocol module found: [artemis-server]. Adding protocol support for: CORE
2022-08-15 20:00:06.498  INFO 138406 --- [           main] org.apache.activemq.artemis.core.server  : AMQ221034: Waiting indefinitely to obtain live lock
2022-08-15 20:00:06.499  INFO 138406 --- [           main] org.apache.activemq.artemis.core.server  : AMQ221035: Live Server Obtained live lock
2022-08-15 20:00:06.730  INFO 138406 --- [           main] org.apache.activemq.artemis.core.server  : AMQ221080: Deploying address DLQ supporting [ANYCAST]
2022-08-15 20:00:06.731  INFO 138406 --- [           main] org.apache.activemq.artemis.core.server  : AMQ221003: Deploying ANYCAST queue DLQ on address DLQ
2022-08-15 20:00:06.734  INFO 138406 --- [           main] org.apache.activemq.artemis.core.server  : AMQ221080: Deploying address ExpiryQueue supporting [ANYCAST]
2022-08-15 20:00:06.735  INFO 138406 --- [           main] org.apache.activemq.artemis.core.server  : AMQ221003: Deploying ANYCAST queue ExpiryQueue on address ExpiryQueue
2022-08-15 20:00:06.735  INFO 138406 --- [           main] org.apache.activemq.artemis.core.server  : AMQ221003: Deploying ANYCAST queue tasks.background on address tasks.background
2022-08-15 20:00:06.735  INFO 138406 --- [           main] org.apache.activemq.artemis.core.server  : AMQ221003: Deploying MULTICAST queue domain.events on address domain.events
2022-08-15 20:00:06.765  INFO 138406 --- [           main] org.apache.activemq.artemis.core.server  : AMQ221007: Server is now live
2022-08-15 20:00:06.766  INFO 138406 --- [           main] org.apache.activemq.artemis.core.server  : AMQ221001: Apache ActiveMQ Artemis Message Broker version 2.19.1 [localhost, nodeID=0cbb01de-1cd4-11ed-8f64-b8599fc3c6aa]
2022-08-15 20:00:06.950  INFO 138406 --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 8.5.13 by Redgate
2022-08-15 20:00:06.951  INFO 138406 --- [           main] o.f.c.internal.license.VersionPrinter    : See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.13
2022-08-15 20:00:06.951  INFO 138406 --- [           main] o.f.c.internal.license.VersionPrinter    :
2022-08-15 20:00:06.968  INFO 138406 --- [           main] o.f.c.i.database.base.BaseDatabaseType   : Database: jdbc:sqlite:/home/nattymitch/.komga/database.sqlite (SQLite 3.36)
2022-08-15 20:00:07.019  INFO 138406 --- [           main] o.f.core.internal.command.DbValidate     : Successfully validated 54 migrations (execution time 00:00.034s)
2022-08-15 20:00:07.024  INFO 138406 --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema "main": 20220715213721
2022-08-15 20:00:07.025  INFO 138406 --- [           main] o.f.core.internal.command.DbMigrate      : Schema "main" is up to date. No migration necessary.
2022-08-15 20:00:07.670  WARN 138406 --- [           main] c.g.g.n.j.i.plugins.JxlImageReaderSpi    : Missing Foreign Linker API, plugin will be disabled. Try adding JVM arguments: --add-modules jdk.incubator.foreign
2022-08-15 20:00:07.728  INFO 138406 --- [           main] o.g.k.i.image.ImageConverter             : Using native WebP library
2022-08-15 20:00:07.729  INFO 138406 --- [           main] o.g.k.i.image.ImageConverter             : Supported read formats: [JPEG 2000, JPG, tiff, bigtiff, bmp, PCX, wbp, gif, WBMP, PNG, RAW, JPEG, PNM, BigTIFF, tif, TIFF, wbmp, jpeg, jbig2, jpeg-lossless, jpg, JPEG2000, BMP, pcx, WBP, GIF, png, BIGTIFF, raw, webp, JPEG-LOSSLESS, JBIG2, pnm, TIF, jpeg2000, WEBP, WebP, jpeg 2000]
2022-08-15 20:00:07.730  INFO 138406 --- [           main] o.g.k.i.image.ImageConverter             : Supported read mediaTypes: [image/vnd.wap.wbmp, image/jpeg, image/x-portable-graymap, image/bmp, image/x-windows-pcx, image/gif, image/x-pc-paintbrush, image/x-raw, image/webp, image/x-pcx, image/x-portable-bitmap, image/x-jb2, image/png, image/pcx, image/x-windows-bmp, image/x-webp, image/jpeg2000, image/jp2, image/x-bmp, image/x-png, image/x-portable-pixmap, image/tiff, image/x-tiff, image/x-jbig2, image/x-portable-anymap]
2022-08-15 20:00:07.730  INFO 138406 --- [           main] o.g.k.i.image.ImageConverter             : Supported write formats: [JPEG 2000, JPG, tiff, bmp, PCX, bigtiff, gif, WBMP, PNG, RAW, JPEG, PNM, BigTIFF, tif, TIFF, wbmp, jpeg, jpg, JPEG2000, BMP, pcx, GIF, png, raw, BIGTIFF, webp, pnm, TIF, jpeg2000, WebP, jpeg 2000]
2022-08-15 20:00:07.730  INFO 138406 --- [           main] o.g.k.i.image.ImageConverter             : Supported write mediaTypes: [image/png, image/vnd.wap.wbmp, image/jpeg, image/x-portable-graymap, image/bmp, image/pcx, image/gif, image/x-windows-pcx, image/x-windows-bmp, image/jpeg2000, image/x-pc-paintbrush, image/x-raw, image/webp, image/jp2, image/x-pcx, image/x-bmp, image/x-png, image/x-portable-bitmap, image/x-portable-pixmap, image/tiff, image/x-tiff, image/x-portable-anymap]
2022-08-15 20:00:08.577  INFO 138406 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [public/index.html]
2022-08-15 20:00:09.272  INFO 138406 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 20 endpoint(s) beneath base path '/actuator'
2022-08-15 20:00:09.292  WARN 138406 --- [           main] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Mvc [pattern='/error**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2022-08-15 20:00:09.293  INFO 138406 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will not secure Mvc [pattern='/error**']
2022-08-15 20:00:09.293  WARN 138406 --- [           main] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Mvc [pattern='/css/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2022-08-15 20:00:09.293  INFO 138406 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will not secure Mvc [pattern='/css/**']
2022-08-15 20:00:09.293  WARN 138406 --- [           main] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Mvc [pattern='/img/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2022-08-15 20:00:09.293  INFO 138406 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will not secure Mvc [pattern='/img/**']
2022-08-15 20:00:09.294  WARN 138406 --- [           main] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Mvc [pattern='/js/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2022-08-15 20:00:09.294  INFO 138406 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will not secure Mvc [pattern='/js/**']
2022-08-15 20:00:09.294  WARN 138406 --- [           main] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Mvc [pattern='/favicon.ico']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2022-08-15 20:00:09.294  INFO 138406 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will not secure Mvc [pattern='/favicon.ico']
2022-08-15 20:00:09.294  WARN 138406 --- [           main] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Mvc [pattern='/favicon-16x16.png']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2022-08-15 20:00:09.294  INFO 138406 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will not secure Mvc [pattern='/favicon-16x16.png']
2022-08-15 20:00:09.294  WARN 138406 --- [           main] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Mvc [pattern='/favicon-32x32.png']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2022-08-15 20:00:09.294  INFO 138406 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will not secure Mvc [pattern='/favicon-32x32.png']
2022-08-15 20:00:09.294  WARN 138406 --- [           main] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Mvc [pattern='/mstile-144x144.png']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2022-08-15 20:00:09.294  INFO 138406 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will not secure Mvc [pattern='/mstile-144x144.png']
2022-08-15 20:00:09.295  WARN 138406 --- [           main] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Mvc [pattern='/apple-touch-icon.png']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2022-08-15 20:00:09.295  INFO 138406 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will not secure Mvc [pattern='/apple-touch-icon.png']
2022-08-15 20:00:09.295  WARN 138406 --- [           main] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Mvc [pattern='/apple-touch-icon-180x180.png']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2022-08-15 20:00:09.295  INFO 138406 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will not secure Mvc [pattern='/apple-touch-icon-180x180.png']
2022-08-15 20:00:09.295  WARN 138406 --- [           main] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Mvc [pattern='/android-chrome-192x192.png']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2022-08-15 20:00:09.295  INFO 138406 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will not secure Mvc [pattern='/android-chrome-192x192.png']
2022-08-15 20:00:09.295  WARN 138406 --- [           main] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Mvc [pattern='/android-chrome-512x512.png']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2022-08-15 20:00:09.295  INFO 138406 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will not secure Mvc [pattern='/android-chrome-512x512.png']
2022-08-15 20:00:09.295  WARN 138406 --- [           main] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Mvc [pattern='/manifest.json']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2022-08-15 20:00:09.295  INFO 138406 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will not secure Mvc [pattern='/manifest.json']
2022-08-15 20:00:09.295  WARN 138406 --- [           main] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Mvc [pattern='/']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2022-08-15 20:00:09.295  INFO 138406 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will not secure Mvc [pattern='/']
2022-08-15 20:00:09.295  WARN 138406 --- [           main] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Mvc [pattern='/index.html']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2022-08-15 20:00:09.295  INFO 138406 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will not secure Mvc [pattern='/index.html']
2022-08-15 20:00:09.323  INFO 138406 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure any request with [org.springframework.security.web.session.DisableEncodeUrlFilter@153d6d74, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@6c9b44bf, org.springframework.security.web.context.SecurityContextPersistenceFilter@1e3f86d5, org.springframework.security.web.header.HeaderWriterFilter@320be73, org.springframework.web.filter.CorsFilter@299b9851, org.springframework.security.web.authentication.logout.LogoutFilter@74b00247, org.springframework.security.web.session.ConcurrentSessionFilter@28fc1132, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@73a6cc79, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@4b9c411, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@233f52f8, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@191a0351, org.springframework.security.web.session.SessionManagementFilter@f5bf288, org.springframework.security.web.access.ExceptionTranslationFilter@482c351d, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@7d66e544]
2022-08-15 20:00:09.679  WARN 138406 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
2022-08-15 20:00:09.741  INFO 138406 --- [           main] org.apache.activemq.artemis.core.server  : AMQ221002: Apache ActiveMQ Artemis Message Broker version 2.19.1 [0cbb01de-1cd4-11ed-8f64-b8599fc3c6aa] stopped, uptime 3.450 seconds
2022-08-15 20:00:09.742  INFO 138406 --- [           main] com.zaxxer.hikari.HikariDataSource       : SqliteUdfPool - Shutdown initiated...
2022-08-15 20:00:09.743  INFO 138406 --- [           main] com.zaxxer.hikari.HikariDataSource       : SqliteUdfPool - Shutdown completed.
2022-08-15 20:00:09.746  INFO 138406 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-08-15 20:00:09.748  INFO 138406 --- [           main] io.hawt.web.auth.AuthenticationFilter    : Destroying hawtio authentication filter
2022-08-15 20:00:09.748  INFO 138406 --- [           main] io.hawt.HawtioContextListener            : Destroying hawtio services
2022-08-15 20:00:09.764  INFO 138406 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-08-15 20:00:09.785 ERROR 138406 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.21.jar!/:5.3.21]
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.21.jar!/:5.3.21]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.21.jar!/:5.3.21]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.21.jar!/:5.3.21]
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.21.jar!/:5.3.21]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.21.jar!/:5.3.21]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.21.jar!/:5.3.21]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.gotson.komga.ApplicationKt.main(Application.kt:16) ~[classes!/:na]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[komga.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[komga.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[komga.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[komga.jar:na]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:229) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.21.jar!/:5.3.21]
        ... 20 common frames omitted
Caused by: java.lang.IllegalArgumentException: standardService.connector.startFailed
        at org.apache.catalina.core.StandardService.addConnector(StandardService.java:238) ~[tomcat-embed-core-9.0.64.jar!/:na]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:282) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:213) ~[spring-boot-2.7.1.jar!/:2.7.1]
        ... 22 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:1077) ~[tomcat-embed-core-9.0.64.jar!/:na]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.64.jar!/:na]
        at org.apache.catalina.core.StandardService.addConnector(StandardService.java:234) ~[tomcat-embed-core-9.0.64.jar!/:na]
        ... 24 common frames omitted
Caused by: java.net.SocketException: Operation not permitted
        at java.base/sun.nio.ch.Net.bind0(Native Method) ~[na:na]
        at java.base/sun.nio.ch.Net.bind(Net.java:555) ~[na:na]
        at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337) ~[na:na]
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294) ~[na:na]
        at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:274) ~[tomcat-embed-core-9.0.64.jar!/:na]
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:229) ~[tomcat-embed-core-9.0.64.jar!/:na]
        at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1227) ~[tomcat-embed-core-9.0.64.jar!/:na]
        at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1313) ~[tomcat-embed-core-9.0.64.jar!/:na]
        at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:614) ~[tomcat-embed-core-9.0.64.jar!/:na]
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:1074) ~[tomcat-embed-core-9.0.64.jar!/:na]
        ... 26 common frames omitted
```

### Komga version

0.157.0

### Operating system

Gentoo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Looks like your user cannot open port 8080, maybe already used by another app, or lacking network permissions?

**Comment by fbordwell** [comment]
Thank you for the help. Port 8080 was in use, I fixed it by launching on a different port.

`java -jar komga.jar --server.port=8443`
