### ISSUE TITLE
mylar `series.json` parsing throwing exception

### ISSUE THREAD

**Issue by qubidt** [gotson/komga#961]
### Steps to reproduce

Like #883, parsing of `series.json` file is still throwing exception (despite the changes made for #890). example `series.json` file generated by the latest Mylar (v0.6.9):

```json
{
    "version": "1.0.1",
    "metadata": {
        "type": "comicSeries",
        "publisher": "Kodansha Comics USA",
        "imprint": null,
        "name": "Vinland Saga",
        "comicid": 69157,
        "year": 2013,
        "description_text": "English translation of Vinland Saga (ヴィンランド・サガ).Vinland Saga is the first series from Kodansha Comics USA to be released in hardcovers, each collection collects and translates two volumes of the original Japanese manga",
        "description_formatted": "English translation of Vinland Saga (ヴィンランド・サガ).Vinland Saga is the first series from Kodansha Comics USA to be released in hardcovers, each collection collects and translates two volumes of the original Japanese manga",
        "volume": null,
        "booktype": "Print",
        "age_rating": null,
        "collects": null,
        "ComicImage": "https://comicvine.gamespot.com/a/uploads/scale_large/6/67663/3439178-01.jpg",
        "total_issues": 12,
        "publication_run": "November 2013 - December 2021",
        "status": "Ended"
    }
}
```

mylar is using `comicid` (no caps):

https://github.com/mylar3/mylar3/blob/5eaffc4547aea74946e31519b4aedcaf11ad9d19/mylar/series_metadata.py#L165-L186

but Komga is expecting `comicId` (camelCase):

https://github.com/gotson/komga/blob/234dae0841159b33b5527720ea6475d1f11d77c4/komga/src/main/kotlin/org/gotson/komga/infrastructure/metadata/mylar/dto/MylarMetadata.kt#L17-L18

### Expected behavior

`series.json` file should be successfully parsed for metadata.

### Actual behavior

Due to the exception, Komga is currently ignoring the entire series.json file

### Logs

```logs
2022-08-25 06:16:04.936  INFO 1 --- [ntContainer#1-1] o.g.k.d.service.SeriesMetadataLifecycle  : Refresh metadata for series: Series(name=20th Century Boys (2000), url=file:/media/comics/Libraries/Manga/20th%20Century%20Boys%20(2000)/, fileLastModified=2022-08-25T06:14:37.564, id=09MHF5PFJKRJ1, libraryId=09MHF4X76KJ7H, bookCount=44, deletedDate=null, createdDate=2022-08-16T09:52:58, lastModifiedDate=2022-08-25T06:16:03.164)
2022-08-25 06:16:05.774 ERROR 1 --- [ntContainer#1-1] o.g.k.i.m.mylar.MylarSeriesProvider      : Error while retrieving metadata from series.json

com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class org.gotson.komga.infrastructure.metadata.mylar.dto.MylarMetadata] value failed for JSON property comicId due to missing (therefore NULL) value for creator parameter comicId which is a non-nullable type
 at [Source: (File); line: 20, column: 5] (through reference chain: org.gotson.komga.infrastructure.metadata.mylar.dto.Series["metadata"]->org.gotson.komga.infrastructure.metadata.mylar.dto.MylarMetadata["comicId"])
	...
	at org.gotson.komga.infrastructure.metadata.mylar.MylarSeriesProvider.getSeriesMetadata(MylarSeriesProvider.kt:32) ~[classes/:na]
	at org.gotson.komga.domain.service.SeriesMetadataLifecycle.refreshMetadata(SeriesMetadataLifecycle.kt:79) ~[classes/:na]
	at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:116) ~[classes/:na]
	...
```

### Komga version

v0.157.1-master

### Operating system

Linux

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Looks like no one noticed that the fix didn't fix anything !
